"""
==================================================================
Upbit Surge Monitor - History Gap Classification Review Clean V002
==================================================================

File:
    review_history_gap_classification.py

Purpose:
    Review the output generated by classify_history_gaps.py and create
    the final READ-ONLY recovery plan before historical OHLCV repair.

Clean V002 major change:
    - FULL OHLCV coverage and GAP TARGET coverage are separate concepts.
    - Full OHLCV is expected to contain 290 markets x 3 timeframes
      = 870 source CSV files/jobs.
    - Classifier output contains ONLY markets/jobs where historical
      gaps were detected.
    - Therefore classifier market/job counts MUST NOT be forced to
      equal 290 / 870.
    - Classifier coverage is validated dynamically against the source
      gap report.

This stage DOES NOT:
    - modify OHLCV
    - delete OHLCV
    - call Upbit API
    - repair gaps
    - rebuild features
    - run 256 Detector
    - create future labels
    - run prediction
    - trade
    - execute Git reset / clean / commit / push

This stage DOES:
    - discover classifier output files
    - discover source gap report
    - normalize classifier columns
    - normalize gap report columns
    - verify full OHLCV coverage independently
    - verify classifier coverage against gap report dynamically
    - verify classification rows
    - separate RECOVERABLE / STRUCTURAL / REVIEW
    - create a recovery target plan
    - create detailed review outputs
    - create persistent checkpoint/status files
    - support safe Resume
    - verify source files remain unchanged

Clean V002 principles:
    1. READ ONLY source inspection.
    2. Persistent Resume / Checkpoint.
    3. Never trust file existence alone.
    4. Resume requires fingerprint + output integrity.
    5. Atomic runtime writes.
    6. No automatic source cleanup.
    7. ASCII-safe console logging.
    8. Full OHLCV coverage != Gap target coverage.
    9. Gap target counts are derived dynamically.
   10. Never hard-code current gap counts.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import sys
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

import pandas as pd


# ============================================================
# 1. VERSION / CONSTANTS
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VERSION = "History Gap Classification Review Clean V002"

TIMEFRAMES = ("h1", "h4", "d1")

CLASS_RECOVERABLE = "RECOVERABLE"
CLASS_STRUCTURAL = "STRUCTURAL"
CLASS_REVIEW = "REVIEW"

VALID_CLASSES = {
    CLASS_RECOVERABLE,
    CLASS_STRUCTURAL,
    CLASS_REVIEW,
}

# These values apply ONLY to the full OHLCV source dataset.
DEFAULT_EXPECTED_FULL_MARKETS = 290
DEFAULT_EXPECTED_FULL_JOBS = 870

CHECKPOINT_VERSION = 2
PLAN_VERSION = 2


# ============================================================
# 2. PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent

DATA_DIR = ROOT / "data"
OHLCV_DIR = DATA_DIR / "ohlcv"

VALIDATION_DIR = DATA_DIR / "validation"
REPORT_DIR = DATA_DIR / "reports"
RECOVERY_DIR = DATA_DIR / "recovery"

CHECKPOINT_PATH = (
    VALIDATION_DIR
    / "review_history_gap_classification_checkpoint.json"
)

STATUS_PATH = (
    DATA_DIR
    / "review_history_gap_classification_status.csv"
)

SUMMARY_PATH = (
    REPORT_DIR
    / "history_gap_classification_review_summary.csv"
)

DETAIL_PATH = (
    REPORT_DIR
    / "history_gap_classification_review_detail.csv"
)

RECOVERABLE_PATH = (
    RECOVERY_DIR
    / "history_gap_recovery_targets.csv"
)

STRUCTURAL_PATH = (
    REPORT_DIR
    / "history_gap_structural.csv"
)

REVIEW_PATH = (
    REPORT_DIR
    / "history_gap_manual_review.csv"
)

RECOVERY_PLAN_JSON_PATH = (
    RECOVERY_DIR
    / "history_gap_recovery_plan.json"
)


# ============================================================
# 3. INPUT CANDIDATES
# ============================================================

CLASSIFIER_DETAIL_CANDIDATES = (
    DATA_DIR / "history_gap_classification.csv",
    DATA_DIR / "history_gap_classification_detail.csv",
    DATA_DIR / "classified_history_gaps.csv",
    DATA_DIR / "history_gap_classifier.csv",

    REPORT_DIR / "history_gap_classification.csv",
    REPORT_DIR / "history_gap_classification_detail.csv",
    REPORT_DIR / "classified_history_gaps.csv",
    REPORT_DIR / "history_gap_classifier.csv",

    REPORT_DIR
    / "history_gap_classification"
    / "history_gap_classification.csv",

    VALIDATION_DIR / "history_gap_classification.csv",
    VALIDATION_DIR / "history_gap_classification_detail.csv",
)

CLASSIFIER_SUMMARY_CANDIDATES = (
    DATA_DIR / "history_gap_classification_summary.csv",
    REPORT_DIR / "history_gap_classification_summary.csv",

    REPORT_DIR
    / "history_gap_classification"
    / "history_gap_classification_summary.csv",

    VALIDATION_DIR / "history_gap_classification_summary.csv",
)

GAP_REPORT_CANDIDATES = (
    DATA_DIR / "data_history_gap_report.csv",
    DATA_DIR / "history_gap_report.csv",

    REPORT_DIR / "data_history_gap_report.csv",
    REPORT_DIR / "history_gap_report.csv",

    REPORT_DIR
    / "history_gap"
    / "data_history_gap_report.csv",

    VALIDATION_DIR / "data_history_gap_report.csv",
    VALIDATION_DIR / "history_gap_report.csv",
)


# ============================================================
# 4. COLUMN ALIASES
# ============================================================

COLUMN_ALIASES: dict[str, tuple[str, ...]] = {
    "market": (
        "market",
        "ticker",
        "symbol",
        "code",
        "market_code",
    ),
    "timeframe": (
        "timeframe",
        "tf",
        "interval",
        "unit",
        "candle",
        "candle_type",
    ),
    "classification": (
        "classification",
        "class",
        "gap_class",
        "category",
        "gap_category",
        "status",
        "decision",
        "result",
    ),
    "gap_start": (
        "gap_start",
        "start",
        "start_time",
        "gap_start_time",
        "missing_start",
        "missing_from",
        "from_time",
        "start_timestamp",
    ),
    "gap_end": (
        "gap_end",
        "end",
        "end_time",
        "gap_end_time",
        "missing_end",
        "missing_to",
        "to_time",
        "end_timestamp",
    ),
    "missing_count": (
        "missing_count",
        "missing",
        "missing_est",
        "missing_estimate",
        "estimated_missing",
        "estimated_missing_count",
        "missing_candles",
        "gap_candles",
        "expected_missing",
    ),
    "gap_seconds": (
        "gap_seconds",
        "duration_seconds",
        "gap_duration_seconds",
        "duration",
    ),
    "reason": (
        "reason",
        "classification_reason",
        "gap_reason",
        "note",
        "notes",
        "detail",
        "message",
    ),
    "source_file": (
        "source_file",
        "file",
        "path",
        "ohlcv_file",
    ),
}


# ============================================================
# 5. DATA CLASSES
# ============================================================

@dataclass
class ReviewJob:
    job_key: str
    market: str
    timeframe: str
    row_count: int
    recoverable_rows: int
    structural_rows: int
    review_rows: int
    recoverable_missing: int
    input_sha256: str


# ============================================================
# 6. BASIC UTILITIES
# ============================================================

def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def print_line(char: str = "=", width: int = 68) -> None:
    print(char * width)


def ensure_runtime_directories() -> None:
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    RECOVERY_DIR.mkdir(parents=True, exist_ok=True)


def normalize_text(value: Any) -> str:
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    return str(value).strip()


def normalize_column_name(value: str) -> str:
    value = normalize_text(value).lower()

    for char in (" ", "-", "/"):
        value = value.replace(char, "_")

    while "__" in value:
        value = value.replace("__", "_")

    return value.strip("_")


def normalize_market(value: Any) -> str:
    return normalize_text(value).upper()


def normalize_timeframe(value: Any) -> str:
    text = normalize_text(value).lower()

    mapping = {
        "1h": "h1",
        "h1": "h1",
        "60m": "h1",
        "60min": "h1",
        "minute60": "h1",

        "4h": "h4",
        "h4": "h4",
        "240m": "h4",
        "240min": "h4",
        "minute240": "h4",

        "1d": "d1",
        "d1": "d1",
        "day": "d1",
        "daily": "d1",
        "days": "d1",
    }

    return mapping.get(text, text)


def normalize_classification(value: Any) -> str:
    text = normalize_text(value).upper()

    text = text.replace("-", "_")
    text = text.replace(" ", "_")

    mapping = {
        "RECOVERABLE": CLASS_RECOVERABLE,
        "RECOVERY": CLASS_RECOVERABLE,
        "REPAIRABLE": CLASS_RECOVERABLE,
        "REPAIR": CLASS_RECOVERABLE,
        "RESTORABLE": CLASS_RECOVERABLE,

        "STRUCTURAL": CLASS_STRUCTURAL,
        "STRUCTURE": CLASS_STRUCTURAL,
        "EXPECTED": CLASS_STRUCTURAL,
        "NORMAL": CLASS_STRUCTURAL,
        "NON_RECOVERABLE": CLASS_STRUCTURAL,
        "NOT_RECOVERABLE": CLASS_STRUCTURAL,

        "REVIEW": CLASS_REVIEW,
        "MANUAL_REVIEW": CLASS_REVIEW,
        "UNKNOWN": CLASS_REVIEW,
        "UNCERTAIN": CLASS_REVIEW,
        "CHECK": CLASS_REVIEW,
    }

    return mapping.get(text, text)


def safe_int(value: Any, default: int = 0) -> int:
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except Exception:
        pass

    text = str(value).strip()

    if not text:
        return default

    try:
        return int(float(text))
    except Exception:
        return default


# ============================================================
# 7. HASH / FINGERPRINT
# ============================================================

def sha256_file(path: Path) -> str:
    hasher = hashlib.sha256()

    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)

            if not chunk:
                break

            hasher.update(chunk)

    return hasher.hexdigest()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def stable_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")


def dataframe_sha256(df: pd.DataFrame) -> str:
    if df.empty:
        return sha256_bytes(b"")

    normalized = df.copy().fillna("")

    normalized.columns = [
        str(c)
        for c in normalized.columns
    ]

    columns = sorted(normalized.columns)

    normalized = normalized.reindex(
        columns=columns
    )

    sort_columns = [
        c
        for c in (
            "market",
            "timeframe",
            "gap_start",
            "gap_end",
            "classification",
        )
        if c in normalized.columns
    ]

    if sort_columns:
        normalized = normalized.sort_values(
            sort_columns,
            kind="stable",
        )

    csv_bytes = normalized.to_csv(
        index=False,
        lineterminator="\n",
    ).encode("utf-8")

    return sha256_bytes(csv_bytes)


def source_manifest_sha256(
    paths: Iterable[Path],
) -> str:

    manifest: list[dict[str, Any]] = []

    for path in sorted(
        paths,
        key=lambda p: str(p).lower(),
    ):
        if not path.exists():
            continue

        if not path.is_file():
            continue

        stat = path.stat()

        manifest.append(
            {
                "path": str(
                    path.relative_to(ROOT)
                ),
                "size": stat.st_size,
                "sha256": sha256_file(path),
            }
        )

    return sha256_bytes(
        stable_json_bytes(manifest)
    )


# ============================================================
# 8. ATOMIC WRITES
# ============================================================

def atomic_write_text(
    path: Path,
    text: str,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, temp_name = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(path.parent),
    )

    os.close(fd)

    temp_path = Path(temp_name)

    try:
        temp_path.write_text(
            text,
            encoding="utf-8",
            newline="\n",
        )

        os.replace(
            temp_path,
            path,
        )

    finally:
        if temp_path.exists():
            try:
                temp_path.unlink()
            except OSError:
                pass


def atomic_write_json(
    path: Path,
    value: Any,
) -> None:

    text = json.dumps(
        value,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
        default=str,
    )

    atomic_write_text(
        path,
        text + "\n",
    )


def atomic_write_dataframe(
    path: Path,
    df: pd.DataFrame,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, temp_name = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(path.parent),
    )

    os.close(fd)

    temp_path = Path(temp_name)

    try:
        df.to_csv(
            temp_path,
            index=False,
            encoding="utf-8",
            lineterminator="\n",
            quoting=csv.QUOTE_MINIMAL,
        )

        os.replace(
            temp_path,
            path,
        )

    finally:
        if temp_path.exists():
            try:
                temp_path.unlink()
            except OSError:
                pass


# ============================================================
# 9. CSV READ
# ============================================================

def read_csv_flexible(
    path: Path,
) -> pd.DataFrame:

    errors: list[str] = []

    for encoding in (
        "utf-8-sig",
        "utf-8",
        "cp949",
        "euc-kr",
    ):
        try:
            return pd.read_csv(
                path,
                encoding=encoding,
                low_memory=False,
            )

        except Exception as exc:
            errors.append(
                f"{encoding}: "
                f"{type(exc).__name__}: {exc}"
            )

    raise RuntimeError(
        "Unable to read CSV file: "
        + str(path)
        + " | "
        + " | ".join(errors)
    )


# ============================================================
# 10. FILE DISCOVERY
# ============================================================

def find_first_existing(
    candidates: Iterable[Path],
) -> Optional[Path]:

    for path in candidates:
        if path.exists() and path.is_file():
            return path

    return None


def discover_classifier_detail() -> Path:

    direct = find_first_existing(
        CLASSIFIER_DETAIL_CANDIDATES
    )

    if direct is not None:
        return direct

    found: list[Path] = []

    patterns = (
        "*classification*.csv",
        "*classifier*.csv",
        "*classified*gap*.csv",
    )

    for root in (
        DATA_DIR,
        REPORT_DIR,
        VALIDATION_DIR,
    ):
        if not root.exists():
            continue

        for pattern in patterns:
            for path in root.rglob(pattern):

                if not path.is_file():
                    continue

                if path in {
                    SUMMARY_PATH,
                    DETAIL_PATH,
                    STRUCTURAL_PATH,
                    REVIEW_PATH,
                    STATUS_PATH,
                    RECOVERABLE_PATH,
                }:
                    continue

                name = path.name.lower()

                if "summary" in name:
                    continue

                if "review" in name:
                    continue

                found.append(path)

    found = sorted(
        set(found),
        key=lambda p: (
            p.stat().st_mtime,
            str(p),
        ),
        reverse=True,
    )

    if not found:
        raise FileNotFoundError(
            "Classifier detail CSV was not found. "
            "Run classify_history_gaps.py first."
        )

    return found[0]


def discover_classifier_summary() -> Optional[Path]:

    direct = find_first_existing(
        CLASSIFIER_SUMMARY_CANDIDATES
    )

    if direct is not None:
        return direct

    found: list[Path] = []

    for root in (
        DATA_DIR,
        REPORT_DIR,
        VALIDATION_DIR,
    ):
        if not root.exists():
            continue

        for path in root.rglob(
            "*classification*summary*.csv"
        ):
            if (
                path.is_file()
                and path != SUMMARY_PATH
            ):
                found.append(path)

    if not found:
        return None

    return sorted(
        found,
        key=lambda p: (
            p.stat().st_mtime,
            str(p),
        ),
        reverse=True,
    )[0]


def discover_gap_report() -> Path:

    direct = find_first_existing(
        GAP_REPORT_CANDIDATES
    )

    if direct is not None:
        return direct

    found: list[Path] = []

    for root in (
        DATA_DIR,
        REPORT_DIR,
        VALIDATION_DIR,
    ):
        if not root.exists():
            continue

        for path in root.rglob(
            "*gap*report*.csv"
        ):
            if not path.is_file():
                continue

            name = path.name.lower()

            if "classification" in name:
                continue

            if "review" in name:
                continue

            found.append(path)

    if not found:
        raise FileNotFoundError(
            "Source history gap report was not found. "
            "Run data_history_gap_report.py first."
        )

    return sorted(
        found,
        key=lambda p: (
            p.stat().st_mtime,
            str(p),
        ),
        reverse=True,
    )[0]


# ============================================================
# 11. COLUMN RESOLUTION
# ============================================================

def resolve_column(
    df: pd.DataFrame,
    canonical_name: str,
    required: bool = False,
) -> Optional[str]:

    normalized_map = {
        normalize_column_name(str(column)):
        str(column)
        for column in df.columns
    }

    aliases = COLUMN_ALIASES.get(
        canonical_name,
        (canonical_name,),
    )

    for alias in aliases:

        key = normalize_column_name(alias)

        if key in normalized_map:
            return normalized_map[key]

    if required:
        raise RuntimeError(
            f"Required column not found: "
            f"{canonical_name}. "
            f"Available columns: "
            f"{list(df.columns)}"
        )

    return None


# ============================================================
# 12. CLASSIFIER NORMALIZATION
# ============================================================

def normalize_classifier_dataframe(
    raw_df: pd.DataFrame,
) -> pd.DataFrame:

    if raw_df.empty:
        raise RuntimeError(
            "Classifier detail CSV is empty."
        )

    market_col = resolve_column(
        raw_df,
        "market",
        required=True,
    )

    timeframe_col = resolve_column(
        raw_df,
        "timeframe",
        required=True,
    )

    class_col = resolve_column(
        raw_df,
        "classification",
        required=True,
    )

    gap_start_col = resolve_column(
        raw_df,
        "gap_start",
    )

    gap_end_col = resolve_column(
        raw_df,
        "gap_end",
    )

    missing_col = resolve_column(
        raw_df,
        "missing_count",
    )

    gap_seconds_col = resolve_column(
        raw_df,
        "gap_seconds",
    )

    reason_col = resolve_column(
        raw_df,
        "reason",
    )

    source_file_col = resolve_column(
        raw_df,
        "source_file",
    )

    normalized = pd.DataFrame()

    normalized["market"] = (
        raw_df[market_col]
        .map(normalize_market)
    )

    normalized["timeframe"] = (
        raw_df[timeframe_col]
        .map(normalize_timeframe)
    )

    normalized["classification"] = (
        raw_df[class_col]
        .map(normalize_classification)
    )

    normalized["gap_start"] = (
        raw_df[gap_start_col].map(normalize_text)
        if gap_start_col is not None
        else ""
    )

    normalized["gap_end"] = (
        raw_df[gap_end_col].map(normalize_text)
        if gap_end_col is not None
        else ""
    )

    normalized["missing_count"] = (
        raw_df[missing_col].map(safe_int)
        if missing_col is not None
        else 0
    )

    normalized["gap_seconds"] = (
        raw_df[gap_seconds_col].map(safe_int)
        if gap_seconds_col is not None
        else 0
    )

    normalized["reason"] = (
        raw_df[reason_col].map(normalize_text)
        if reason_col is not None
        else ""
    )

    normalized["source_file"] = (
        raw_df[source_file_col].map(normalize_text)
        if source_file_col is not None
        else ""
    )

    normalized["source_row"] = range(
        1,
        len(normalized) + 1,
    )

    invalid_market = (
        normalized["market"].eq("")
        | ~normalized["market"].str.startswith(
            "KRW-"
        )
    )

    if invalid_market.any():

        examples = normalized.loc[
            invalid_market,
            ["source_row", "market"],
        ].head(10).to_dict("records")

        raise RuntimeError(
            "Invalid classifier market values: "
            + json.dumps(
                examples,
                ensure_ascii=True,
            )
        )

    invalid_timeframe = (
        ~normalized["timeframe"].isin(
            TIMEFRAMES
        )
    )

    if invalid_timeframe.any():

        examples = normalized.loc[
            invalid_timeframe,
            ["source_row", "timeframe"],
        ].head(10).to_dict("records")

        raise RuntimeError(
            "Invalid classifier timeframe values: "
            + json.dumps(
                examples,
                ensure_ascii=True,
            )
        )

    invalid_class = (
        ~normalized["classification"].isin(
            VALID_CLASSES
        )
    )

    if invalid_class.any():

        examples = normalized.loc[
            invalid_class,
            [
                "source_row",
                "classification",
            ],
        ].head(20).to_dict("records")

        raise RuntimeError(
            "Unknown classification values detected. "
            "No unknown value will be silently "
            "converted. Examples: "
            + json.dumps(
                examples,
                ensure_ascii=True,
            )
        )

    if (
        normalized["missing_count"] < 0
    ).any():
        raise RuntimeError(
            "Negative classifier missing_count "
            "detected."
        )

    normalized["job_key"] = (
        normalized["timeframe"]
        + "|"
        + normalized["market"]
    )

    return normalized[
        [
            "source_row",
            "job_key",
            "market",
            "timeframe",
            "classification",
            "gap_start",
            "gap_end",
            "gap_seconds",
            "missing_count",
            "reason",
            "source_file",
        ]
    ]


# ============================================================
# 13. GAP REPORT NORMALIZATION
# ============================================================

def normalize_gap_report_dataframe(
    raw_df: pd.DataFrame,
) -> pd.DataFrame:

    if raw_df.empty:
        raise RuntimeError(
            "Source gap report CSV is empty."
        )

    market_col = resolve_column(
        raw_df,
        "market",
        required=True,
    )

    timeframe_col = resolve_column(
        raw_df,
        "timeframe",
        required=True,
    )

    gap_start_col = resolve_column(
        raw_df,
        "gap_start",
    )

    gap_end_col = resolve_column(
        raw_df,
        "gap_end",
    )

    missing_col = resolve_column(
        raw_df,
        "missing_count",
    )

    gap_seconds_col = resolve_column(
        raw_df,
        "gap_seconds",
    )

    normalized = pd.DataFrame()

    normalized["market"] = (
        raw_df[market_col]
        .map(normalize_market)
    )

    normalized["timeframe"] = (
        raw_df[timeframe_col]
        .map(normalize_timeframe)
    )

    normalized["gap_start"] = (
        raw_df[gap_start_col].map(normalize_text)
        if gap_start_col is not None
        else ""
    )

    normalized["gap_end"] = (
        raw_df[gap_end_col].map(normalize_text)
        if gap_end_col is not None
        else ""
    )

    normalized["missing_count"] = (
        raw_df[missing_col].map(safe_int)
        if missing_col is not None
        else 0
    )

    normalized["gap_seconds"] = (
        raw_df[gap_seconds_col].map(safe_int)
        if gap_seconds_col is not None
        else 0
    )

    normalized["source_row"] = range(
        1,
        len(normalized) + 1,
    )

    invalid_market = (
        normalized["market"].eq("")
        | ~normalized["market"].str.startswith(
            "KRW-"
        )
    )

    if invalid_market.any():

        examples = normalized.loc[
            invalid_market,
            ["source_row", "market"],
        ].head(10).to_dict("records")

        raise RuntimeError(
            "Invalid gap report market values: "
            + json.dumps(
                examples,
                ensure_ascii=True,
            )
        )

    invalid_timeframe = (
        ~normalized["timeframe"].isin(
            TIMEFRAMES
        )
    )

    if invalid_timeframe.any():

        examples = normalized.loc[
            invalid_timeframe,
            ["source_row", "timeframe"],
        ].head(10).to_dict("records")

        raise RuntimeError(
            "Invalid gap report timeframe values: "
            + json.dumps(
                examples,
                ensure_ascii=True,
            )
        )

    if (
        normalized["missing_count"] < 0
    ).any():
        raise RuntimeError(
            "Negative gap report missing_count "
            "detected."
        )

    normalized["job_key"] = (
        normalized["timeframe"]
        + "|"
        + normalized["market"]
    )

    return normalized[
        [
            "source_row",
            "job_key",
            "market",
            "timeframe",
            "gap_start",
            "gap_end",
            "gap_seconds",
            "missing_count",
        ]
    ]


# ============================================================
# 14. DYNAMIC CROSS VALIDATION
# ============================================================

def build_event_signature(
    df: pd.DataFrame,
) -> pd.Series:

    return (
        df["market"].map(normalize_market)
        + "|"
        + df["timeframe"].map(
            normalize_timeframe
        )
        + "|"
        + df["gap_start"].map(
            normalize_text
        )
        + "|"
        + df["gap_end"].map(
            normalize_text
        )
        + "|"
        + df["gap_seconds"].map(
            lambda x: str(safe_int(x))
        )
        + "|"
        + df["missing_count"].map(
            lambda x: str(safe_int(x))
        )
    )


def verify_classifier_against_gap_report(
    classifier_df: pd.DataFrame,
    gap_df: pd.DataFrame,
) -> dict[str, int]:

    classifier_markets = set(
        classifier_df["market"].unique()
    )

    gap_markets = set(
        gap_df["market"].unique()
    )

    classifier_jobs = set(
        classifier_df["job_key"].unique()
    )

    gap_jobs = set(
        gap_df["job_key"].unique()
    )

    if classifier_markets != gap_markets:

        missing = sorted(
            gap_markets - classifier_markets
        )

        extra = sorted(
            classifier_markets - gap_markets
        )

        raise RuntimeError(
            "Classifier market coverage mismatch "
            "against source gap report. "
            f"missing={missing[:20]}, "
            f"extra={extra[:20]}"
        )

    if classifier_jobs != gap_jobs:

        missing = sorted(
            gap_jobs - classifier_jobs
        )

        extra = sorted(
            classifier_jobs - gap_jobs
        )

        raise RuntimeError(
            "Classifier job coverage mismatch "
            "against source gap report. "
            f"missing={missing[:20]}, "
            f"extra={extra[:20]}"
        )

    classifier_signature = (
        build_event_signature(
            classifier_df
        )
        .value_counts()
        .sort_index()
    )

    gap_signature = (
        build_event_signature(
            gap_df
        )
        .value_counts()
        .sort_index()
    )

    if not classifier_signature.equals(
        gap_signature
    ):
        classifier_map = (
            classifier_signature.to_dict()
        )

        gap_map = gap_signature.to_dict()

        keys = sorted(
            set(classifier_map)
            | set(gap_map)
        )

        mismatches = []

        for key in keys:

            classifier_count = safe_int(
                classifier_map.get(key, 0)
            )

            gap_count = safe_int(
                gap_map.get(key, 0)
            )

            if classifier_count != gap_count:

                mismatches.append(
                    {
                        "signature": key,
                        "classifier": (
                            classifier_count
                        ),
                        "gap_report": (
                            gap_count
                        ),
                    }
                )

            if len(mismatches) >= 20:
                break

        raise RuntimeError(
            "Classifier gap-event coverage mismatch "
            "against source gap report. Examples: "
            + json.dumps(
                mismatches,
                ensure_ascii=True,
            )
        )

    return {
        "gap_markets": len(gap_markets),
        "gap_jobs": len(gap_jobs),
        "gap_events": len(gap_df),
    }


# ============================================================
# 15. OHLCV DISCOVERY / FULL COVERAGE
# ============================================================

def discover_ohlcv_files() -> list[Path]:

    files: list[Path] = []

    for timeframe in TIMEFRAMES:

        directory = OHLCV_DIR / timeframe

        if not directory.exists():
            continue

        files.extend(
            path
            for path in directory.glob(
                "KRW-*.csv"
            )
            if path.is_file()
        )

    return sorted(
        files,
        key=lambda p: str(p).lower(),
    )


def parse_ohlcv_identity(
    path: Path,
) -> tuple[str, str]:

    timeframe = path.parent.name.lower()
    market = path.stem.upper()

    return market, timeframe


def verify_full_ohlcv_coverage(
    ohlcv_files: list[Path],
    expected_full_markets: int,
    expected_full_jobs: int,
) -> dict[str, Any]:

    if not ohlcv_files:
        raise RuntimeError(
            "No OHLCV source files found."
        )

    identities: list[tuple[str, str]] = []

    for path in ohlcv_files:

        market, timeframe = (
            parse_ohlcv_identity(path)
        )

        if not market.startswith("KRW-"):
            raise RuntimeError(
                "Invalid OHLCV market filename: "
                + str(path)
            )

        if timeframe not in TIMEFRAMES:
            raise RuntimeError(
                "Invalid OHLCV timeframe directory: "
                + str(path)
            )

        identities.append(
            (market, timeframe)
        )

    if len(identities) != len(
        set(identities)
    ):
        raise RuntimeError(
            "Duplicate OHLCV market/timeframe "
            "identity detected."
        )

    markets = sorted(
        {
            market
            for market, _ in identities
        }
    )

    jobs = {
        f"{timeframe}|{market}"
        for market, timeframe in identities
    }

    timeframe_counts = {
        timeframe: sum(
            1
            for _, tf in identities
            if tf == timeframe
        )
        for timeframe in TIMEFRAMES
    }

    if expected_full_markets > 0:
        if len(markets) != (
            expected_full_markets
        ):
            raise RuntimeError(
                "Full OHLCV market count mismatch. "
                f"expected="
                f"{expected_full_markets}, "
                f"found={len(markets)}"
            )

    if expected_full_jobs > 0:
        if len(jobs) != expected_full_jobs:
            raise RuntimeError(
                "Full OHLCV job/file count mismatch. "
                f"expected={expected_full_jobs}, "
                f"found={len(jobs)}"
            )

    if expected_full_markets > 0:

        for timeframe in TIMEFRAMES:

            count = timeframe_counts[
                timeframe
            ]

            if count != expected_full_markets:
                raise RuntimeError(
                    "Full OHLCV timeframe coverage "
                    "mismatch. "
                    f"timeframe={timeframe}, "
                    f"expected="
                    f"{expected_full_markets}, "
                    f"found={count}"
                )

    return {
        "markets": markets,
        "market_count": len(markets),
        "job_count": len(jobs),
        "timeframe_counts": timeframe_counts,
    }


# ============================================================
# 16. CHECKPOINT
# ============================================================

def empty_checkpoint(
    input_fingerprint: str,
    classifier_path: Path,
    gap_report_path: Path,
) -> dict[str, Any]:

    return {
        "checkpoint_version":
            CHECKPOINT_VERSION,

        "program_version":
            VERSION,

        "created_at_utc":
            utc_now_iso(),

        "updated_at_utc":
            utc_now_iso(),

        "input_fingerprint":
            input_fingerprint,

        "classifier_path":
            str(
                classifier_path.relative_to(
                    ROOT
                )
            ),

        "gap_report_path":
            str(
                gap_report_path.relative_to(
                    ROOT
                )
            ),

        "completed_jobs": {},
    }


def load_checkpoint() -> Optional[
    dict[str, Any]
]:

    if not CHECKPOINT_PATH.exists():
        return None

    try:
        data = json.loads(
            CHECKPOINT_PATH.read_text(
                encoding="utf-8"
            )
        )

        if not isinstance(data, dict):
            return None

        return data

    except Exception:
        return None


def save_checkpoint(
    checkpoint: dict[str, Any],
) -> None:

    checkpoint["updated_at_utc"] = (
        utc_now_iso()
    )

    atomic_write_json(
        CHECKPOINT_PATH,
        checkpoint,
    )


def checkpoint_matches_input(
    checkpoint: Optional[
        dict[str, Any]
    ],
    input_fingerprint: str,
) -> bool:

    if checkpoint is None:
        return False

    if (
        checkpoint.get(
            "checkpoint_version"
        )
        != CHECKPOINT_VERSION
    ):
        return False

    if (
        checkpoint.get(
            "program_version"
        )
        != VERSION
    ):
        return False

    if (
        checkpoint.get(
            "input_fingerprint"
        )
        != input_fingerprint
    ):
        return False

    completed_jobs = checkpoint.get(
        "completed_jobs"
    )

    return isinstance(
        completed_jobs,
        dict,
    )


# ============================================================
# 17. JOB INTEGRITY
# ============================================================

def build_job_summary(
    job_df: pd.DataFrame,
) -> ReviewJob:

    if job_df.empty:
        raise RuntimeError(
            "Cannot build summary for empty job."
        )

    markets = sorted(
        set(job_df["market"].tolist())
    )

    timeframes = sorted(
        set(job_df["timeframe"].tolist())
    )

    job_keys = sorted(
        set(job_df["job_key"].tolist())
    )

    if len(markets) != 1:
        raise RuntimeError(
            "Job contains multiple markets: "
            f"{markets}"
        )

    if len(timeframes) != 1:
        raise RuntimeError(
            "Job contains multiple timeframes: "
            f"{timeframes}"
        )

    if len(job_keys) != 1:
        raise RuntimeError(
            "Job contains multiple keys: "
            f"{job_keys}"
        )

    recoverable = job_df[
        job_df["classification"]
        == CLASS_RECOVERABLE
    ]

    structural = job_df[
        job_df["classification"]
        == CLASS_STRUCTURAL
    ]

    review = job_df[
        job_df["classification"]
        == CLASS_REVIEW
    ]

    return ReviewJob(
        job_key=job_keys[0],
        market=markets[0],
        timeframe=timeframes[0],
        row_count=len(job_df),
        recoverable_rows=len(recoverable),
        structural_rows=len(structural),
        review_rows=len(review),
        recoverable_missing=int(
            recoverable[
                "missing_count"
            ].sum()
        ),
        input_sha256=dataframe_sha256(
            job_df
        ),
    )


def checkpoint_job_is_valid(
    stored: Any,
    current: ReviewJob,
) -> bool:

    if not isinstance(stored, dict):
        return False

    checks = (
        stored.get("job_key")
        == current.job_key,

        stored.get("market")
        == current.market,

        stored.get("timeframe")
        == current.timeframe,

        safe_int(
            stored.get("row_count"),
            -1,
        )
        == current.row_count,

        safe_int(
            stored.get(
                "recoverable_rows"
            ),
            -1,
        )
        == current.recoverable_rows,

        safe_int(
            stored.get(
                "structural_rows"
            ),
            -1,
        )
        == current.structural_rows,

        safe_int(
            stored.get(
                "review_rows"
            ),
            -1,
        )
        == current.review_rows,

        safe_int(
            stored.get(
                "recoverable_missing"
            ),
            -1,
        )
        == current.recoverable_missing,

        stored.get("input_sha256")
        == current.input_sha256,

        stored.get("completed") is True,
    )

    return all(checks)


def review_job_to_checkpoint(
    job: ReviewJob,
) -> dict[str, Any]:

    return {
        "completed": True,

        "completed_at_utc":
            utc_now_iso(),

        "job_key":
            job.job_key,

        "market":
            job.market,

        "timeframe":
            job.timeframe,

        "row_count":
            job.row_count,

        "recoverable_rows":
            job.recoverable_rows,

        "structural_rows":
            job.structural_rows,

        "review_rows":
            job.review_rows,

        "recoverable_missing":
            job.recoverable_missing,

        "input_sha256":
            job.input_sha256,
    }


# ============================================================
# 18. OUTPUT BUILDERS
# ============================================================

def build_summary_dataframe(
    detail_df: pd.DataFrame,
) -> pd.DataFrame:

    rows: list[dict[str, Any]] = []

    grouped = detail_df.groupby(
        ["timeframe", "market"],
        sort=True,
        dropna=False,
    )

    for (
        timeframe,
        market,
    ), job_df in grouped:

        recoverable = job_df[
            job_df["classification"]
            == CLASS_RECOVERABLE
        ]

        structural = job_df[
            job_df["classification"]
            == CLASS_STRUCTURAL
        ]

        review = job_df[
            job_df["classification"]
            == CLASS_REVIEW
        ]

        rows.append(
            {
                "job_key":
                    f"{timeframe}|{market}",

                "market":
                    market,

                "timeframe":
                    timeframe,

                "gap_events":
                    len(job_df),

                "recoverable_events":
                    len(recoverable),

                "structural_events":
                    len(structural),

                "review_events":
                    len(review),

                "recoverable_missing":
                    int(
                        recoverable[
                            "missing_count"
                        ].sum()
                    ),

                "total_missing_est":
                    int(
                        job_df[
                            "missing_count"
                        ].sum()
                    ),
            }
        )

    return pd.DataFrame(rows)


def build_recovery_targets(
    detail_df: pd.DataFrame,
) -> pd.DataFrame:

    targets = detail_df[
        detail_df["classification"]
        == CLASS_RECOVERABLE
    ].copy()

    targets = targets[
        [
            "source_row",
            "job_key",
            "market",
            "timeframe",
            "gap_start",
            "gap_end",
            "gap_seconds",
            "missing_count",
            "reason",
            "source_file",
        ]
    ]

    targets.insert(
        0,
        "plan_version",
        PLAN_VERSION,
    )

    targets.insert(
        1,
        "action",
        "RECOVER",
    )

    targets[
        "approved_for_recovery"
    ] = True

    targets = targets.sort_values(
        [
            "timeframe",
            "market",
            "gap_start",
            "gap_end",
            "source_row",
        ],
        kind="stable",
    ).reset_index(drop=True)

    targets.insert(
        2,
        "target_id",
        [
            f"REC-{index:06d}"
            for index in range(
                1,
                len(targets) + 1,
            )
        ],
    )

    return targets


def build_recovery_plan_json(
    targets_df: pd.DataFrame,
    classifier_path: Path,
    gap_report_path: Path,
    input_fingerprint: str,
    full_coverage: dict[str, Any],
    gap_coverage: dict[str, int],
) -> dict[str, Any]:

    target_markets = (
        sorted(
            set(
                targets_df[
                    "market"
                ].tolist()
            )
        )
        if not targets_df.empty
        else []
    )

    target_timeframes = (
        sorted(
            set(
                targets_df[
                    "timeframe"
                ].tolist()
            )
        )
        if not targets_df.empty
        else []
    )

    missing_total = (
        int(
            targets_df[
                "missing_count"
            ].sum()
        )
        if not targets_df.empty
        else 0
    )

    return {
        "plan_version":
            PLAN_VERSION,

        "program_version":
            VERSION,

        "generated_at_utc":
            utc_now_iso(),

        "input_fingerprint":
            input_fingerprint,

        "classifier_source":
            str(
                classifier_path.relative_to(
                    ROOT
                )
            ),

        "gap_report_source":
            str(
                gap_report_path.relative_to(
                    ROOT
                )
            ),

        "target_csv":
            str(
                RECOVERABLE_PATH.relative_to(
                    ROOT
                )
            ),

        "full_ohlcv_coverage": {
            "markets":
                full_coverage[
                    "market_count"
                ],

            "jobs":
                full_coverage[
                    "job_count"
                ],

            "timeframes":
                full_coverage[
                    "timeframe_counts"
                ],
        },

        "gap_coverage": {
            "markets":
                gap_coverage[
                    "gap_markets"
                ],

            "jobs":
                gap_coverage[
                    "gap_jobs"
                ],

            "events":
                gap_coverage[
                    "gap_events"
                ],
        },

        "target_count":
            len(targets_df),

        "target_markets":
            len(target_markets),

        "target_timeframes":
            target_timeframes,

        "recoverable_missing_estimate":
            missing_total,

        "safety": {
            "ohlcv_write":
                "DISABLED",

            "ohlcv_delete":
                "DISABLED",

            "gap_repair":
                "DISABLED",

            "feature_build":
                "DISABLED",

            "detector_256":
                "DISABLED",

            "future_labels":
                "DISABLED",

            "prediction":
                "DISABLED",

            "trading":
                "DISABLED",

            "git_reset":
                "DISABLED",

            "git_clean":
                "DISABLED",

            "git_commit":
                "DISABLED",

            "git_push":
                "DISABLED",
        },
    }


# ============================================================
# 19. OUTPUT INTEGRITY
# ============================================================

def verify_output_integrity(
    detail_df: pd.DataFrame,
    summary_df: pd.DataFrame,
    targets_df: pd.DataFrame,
    structural_df: pd.DataFrame,
    review_df: pd.DataFrame,
) -> None:

    total_split = (
        len(targets_df)
        + len(structural_df)
        + len(review_df)
    )

    if total_split != len(detail_df):

        raise RuntimeError(
            "Classification split row count "
            "mismatch. "
            f"detail={len(detail_df)}, "
            f"split={total_split}"
        )

    if not targets_df.empty:

        invalid_target = (
            targets_df[
                "approved_for_recovery"
            ] != True
        )

        if invalid_target.any():
            raise RuntimeError(
                "Recovery target approval "
                "integrity check failed."
            )

    expected_jobs = (
        detail_df[
            "job_key"
        ].nunique()
    )

    if len(summary_df) != expected_jobs:

        raise RuntimeError(
            "Summary job count mismatch. "
            f"expected={expected_jobs}, "
            f"found={len(summary_df)}"
        )

    duplicate_target_ids = (
        targets_df[
            "target_id"
        ].duplicated().any()
        if not targets_df.empty
        else False
    )

    if duplicate_target_ids:

        raise RuntimeError(
            "Duplicate recovery target_id "
            "detected."
        )


# ============================================================
# 20. STATUS CSV
# ============================================================

def write_status_csv(
    *,
    result: str,
    classifier_path: Path,
    gap_report_path: Path,
    detail_df: pd.DataFrame,
    summary_df: pd.DataFrame,
    targets_df: pd.DataFrame,
    structural_df: pd.DataFrame,
    review_df: pd.DataFrame,
    resumed_jobs: int,
    processed_jobs: int,
    input_fingerprint: str,
    full_coverage: dict[str, Any],
    gap_coverage: dict[str, int],
) -> None:

    status = pd.DataFrame(
        [
            {
                "project":
                    PROJECT_NAME,

                "version":
                    VERSION,

                "result":
                    result,

                "generated_at_utc":
                    utc_now_iso(),

                "classifier_file":
                    str(
                        classifier_path.relative_to(
                            ROOT
                        )
                    ),

                "gap_report_file":
                    str(
                        gap_report_path.relative_to(
                            ROOT
                        )
                    ),

                "full_ohlcv_markets":
                    full_coverage[
                        "market_count"
                    ],

                "full_ohlcv_jobs":
                    full_coverage[
                        "job_count"
                    ],

                "gap_markets":
                    gap_coverage[
                        "gap_markets"
                    ],

                "gap_jobs":
                    gap_coverage[
                        "gap_jobs"
                    ],

                "classification_rows":
                    len(detail_df),

                "gap_events":
                    gap_coverage[
                        "gap_events"
                    ],

                "review_jobs":
                    len(summary_df),

                "recoverable_events":
                    len(targets_df),

                "structural_events":
                    len(structural_df),

                "review_events":
                    len(review_df),

                "recoverable_missing":
                    (
                        int(
                            targets_df[
                                "missing_count"
                            ].sum()
                        )
                        if not targets_df.empty
                        else 0
                    ),

                "resumed_jobs":
                    resumed_jobs,

                "processed_jobs":
                    processed_jobs,

                "input_fingerprint":
                    input_fingerprint,
            }
        ]
    )

    atomic_write_dataframe(
        STATUS_PATH,
        status,
    )


# ============================================================
# 21. MAIN REVIEW
# ============================================================

def run_review(
    *,
    expected_full_markets: int,
    expected_full_jobs: int,
    checkpoint_every: int,
    force: bool,
) -> int:

    started = time.monotonic()

    ensure_runtime_directories()

    print_line()
    print(
        "FULL KRW HISTORY GAP "
        "CLASSIFICATION REVIEW"
    )
    print_line()

    print(
        f"Project              : "
        f"{PROJECT_NAME}"
    )

    print(
        f"Version              : "
        f"{VERSION}"
    )

    print(
        "Execution mode       : "
        "READ ONLY REVIEW"
    )

    print(
        f"Expected FULL markets: "
        f"{expected_full_markets}"
    )

    print(
        f"Expected FULL jobs   : "
        f"{expected_full_jobs}"
    )

    print(
        "Gap target counts    : "
        "DYNAMIC"
    )

    print_line()

    # --------------------------------------------------------
    # Discover inputs
    # --------------------------------------------------------

    classifier_path = (
        discover_classifier_detail()
    )

    classifier_summary_path = (
        discover_classifier_summary()
    )

    gap_report_path = (
        discover_gap_report()
    )

    print(
        "Classifier detail    : "
        + str(classifier_path)
    )

    if classifier_summary_path is not None:

        print(
            "Classifier summary   : "
            + str(
                classifier_summary_path
            )
        )

    else:

        print(
            "Classifier summary   : "
            "NOT REQUIRED"
        )

    print(
        "Gap report           : "
        + str(gap_report_path)
    )

    print_line("-")

    # --------------------------------------------------------
    # Record source hashes BEFORE
    # --------------------------------------------------------

    classifier_sha_before = (
        sha256_file(
            classifier_path
        )
    )

    gap_report_sha_before = (
        sha256_file(
            gap_report_path
        )
    )

    ohlcv_files = (
        discover_ohlcv_files()
    )

    ohlcv_manifest_before = (
        source_manifest_sha256(
            ohlcv_files
        )
    )

    print(
        f"OHLCV files          : "
        f"{len(ohlcv_files)}"
    )

    print(
        "Source hashes        : "
        "RECORDED"
    )

    # --------------------------------------------------------
    # Verify FULL OHLCV coverage
    # --------------------------------------------------------

    print_line("-")

    print(
        "VERIFY FULL OHLCV COVERAGE"
    )

    full_coverage = (
        verify_full_ohlcv_coverage(
            ohlcv_files,
            expected_full_markets,
            expected_full_jobs,
        )
    )

    print(
        f"Full markets         : "
        f"{full_coverage['market_count']}"
    )

    print(
        f"Full jobs/files      : "
        f"{full_coverage['job_count']}"
    )

    for timeframe in TIMEFRAMES:

        print(
            f"  {timeframe:<4}              : "
            f"{full_coverage['timeframe_counts'][timeframe]}"
        )

    print(
        "[PASS] Full OHLCV coverage "
        "verified independently."
    )

    # --------------------------------------------------------
    # Read classifier
    # --------------------------------------------------------

    raw_classifier_df = (
        read_csv_flexible(
            classifier_path
        )
    )

    detail_df = (
        normalize_classifier_dataframe(
            raw_classifier_df
        )
    )

    # --------------------------------------------------------
    # Read source gap report
    # --------------------------------------------------------

    raw_gap_df = (
        read_csv_flexible(
            gap_report_path
        )
    )

    gap_df = (
        normalize_gap_report_dataframe(
            raw_gap_df
        )
    )

    # --------------------------------------------------------
    # Dynamic cross validation
    # --------------------------------------------------------

    print_line("-")

    print(
        "VERIFY DYNAMIC GAP COVERAGE"
    )

    gap_coverage = (
        verify_classifier_against_gap_report(
            detail_df,
            gap_df,
        )
    )

    markets = sorted(
        detail_df[
            "market"
        ].unique().tolist()
    )

    jobs = sorted(
        detail_df[
            "job_key"
        ].unique().tolist()
    )

    print(
        f"Gap markets          : "
        f"{gap_coverage['gap_markets']}"
    )

    print(
        f"Gap jobs             : "
        f"{gap_coverage['gap_jobs']}"
    )

    print(
        f"Gap events           : "
        f"{gap_coverage['gap_events']}"
    )

    print(
        f"Classifier rows      : "
        f"{len(detail_df)}"
    )

    print(
        "[PASS] Classifier coverage "
        "matches source gap report."
    )

    # --------------------------------------------------------
    # Input fingerprint
    # --------------------------------------------------------

    fingerprint_payload = {
        "version":
            VERSION,

        "classifier_relative_path":
            str(
                classifier_path.relative_to(
                    ROOT
                )
            ),

        "classifier_sha256":
            classifier_sha_before,

        "gap_report_relative_path":
            str(
                gap_report_path.relative_to(
                    ROOT
                )
            ),

        "gap_report_sha256":
            gap_report_sha_before,

        "classification_dataframe_sha256":
            dataframe_sha256(
                detail_df
            ),

        "gap_dataframe_sha256":
            dataframe_sha256(
                gap_df
            ),

        "ohlcv_manifest_sha256":
            ohlcv_manifest_before,

        "expected_full_markets":
            expected_full_markets,

        "expected_full_jobs":
            expected_full_jobs,

        "dynamic_gap_markets":
            gap_coverage[
                "gap_markets"
            ],

        "dynamic_gap_jobs":
            gap_coverage[
                "gap_jobs"
            ],

        "dynamic_gap_events":
            gap_coverage[
                "gap_events"
            ],
    }

    input_fingerprint = (
        sha256_bytes(
            stable_json_bytes(
                fingerprint_payload
            )
        )
    )

    # --------------------------------------------------------
    # Load / initialize checkpoint
    # --------------------------------------------------------

    old_checkpoint = (
        load_checkpoint()
    )

    if (
        not force
        and checkpoint_matches_input(
            old_checkpoint,
            input_fingerprint,
        )
    ):
        checkpoint = old_checkpoint

        print(
            "[RESUME] Compatible checkpoint "
            "found."
        )

    else:

        checkpoint = empty_checkpoint(
            input_fingerprint,
            classifier_path,
            gap_report_path,
        )

        if force:

            print(
                "[RESUME] Force mode: "
                "checkpoint validation reset."
            )

        elif old_checkpoint is None:

            print(
                "[RESUME] No compatible "
                "checkpoint."
            )

        else:

            print(
                "[RESUME] Existing checkpoint "
                "does not match current input."
            )

        save_checkpoint(
            checkpoint
        )

    completed_jobs = (
        checkpoint[
            "completed_jobs"
        ]
    )

    # --------------------------------------------------------
    # Process gap jobs
    # --------------------------------------------------------

    grouped = {
        job_key: job_df.copy()
        for job_key, job_df
        in detail_df.groupby(
            "job_key",
            sort=True,
        )
    }

    resumed_jobs = 0
    processed_jobs = 0

    print_line()
    print(
        "REVIEWING CLASSIFICATION JOBS"
    )
    print_line()

    for index, job_key in enumerate(
        sorted(grouped),
        start=1,
    ):

        job_df = grouped[
            job_key
        ]

        current = build_job_summary(
            job_df
        )

        stored = completed_jobs.get(
            job_key
        )

        if (
            not force
            and checkpoint_job_is_valid(
                stored,
                current,
            )
        ):

            resumed_jobs += 1

            print(
                f"[{index}/{len(grouped)}] "
                f"[RESUME] {job_key}"
            )

            continue

        print(
            f"[{index}/{len(grouped)}] "
            f"[REVIEW] {job_key} | "
            f"rows={current.row_count} | "
            f"recoverable="
            f"{current.recoverable_rows} | "
            f"structural="
            f"{current.structural_rows} | "
            f"review="
            f"{current.review_rows}"
        )

        completed_jobs[
            job_key
        ] = review_job_to_checkpoint(
            current
        )

        processed_jobs += 1

        if (
            checkpoint_every > 0
            and processed_jobs
            % checkpoint_every == 0
        ):
            save_checkpoint(
                checkpoint
            )

    save_checkpoint(
        checkpoint
    )

    # --------------------------------------------------------
    # Verify checkpoint completeness
    # --------------------------------------------------------

    verified_completed = 0

    for job_key in sorted(
        grouped
    ):

        current = build_job_summary(
            grouped[job_key]
        )

        stored = completed_jobs.get(
            job_key
        )

        if not checkpoint_job_is_valid(
            stored,
            current,
        ):

            raise RuntimeError(
                "Checkpoint integrity failed: "
                + job_key
            )

        verified_completed += 1

    if verified_completed != len(
        grouped
    ):

        raise RuntimeError(
            "Completed checkpoint count "
            "mismatch. "
            f"expected={len(grouped)}, "
            f"found={verified_completed}"
        )

    # --------------------------------------------------------
    # Build outputs
    # --------------------------------------------------------

    summary_df = (
        build_summary_dataframe(
            detail_df
        )
    )

    targets_df = (
        build_recovery_targets(
            detail_df
        )
    )

    structural_df = (
        detail_df[
            detail_df["classification"]
            == CLASS_STRUCTURAL
        ]
        .copy()
        .reset_index(drop=True)
    )

    review_df = (
        detail_df[
            detail_df["classification"]
            == CLASS_REVIEW
        ]
        .copy()
        .reset_index(drop=True)
    )

    verify_output_integrity(
        detail_df,
        summary_df,
        targets_df,
        structural_df,
        review_df,
    )

    # --------------------------------------------------------
    # Write runtime outputs
    # --------------------------------------------------------

    atomic_write_dataframe(
        DETAIL_PATH,
        detail_df,
    )

    atomic_write_dataframe(
        SUMMARY_PATH,
        summary_df,
    )

    atomic_write_dataframe(
        RECOVERABLE_PATH,
        targets_df,
    )

    atomic_write_dataframe(
        STRUCTURAL_PATH,
        structural_df,
    )

    atomic_write_dataframe(
        REVIEW_PATH,
        review_df,
    )

    recovery_plan = (
        build_recovery_plan_json(
            targets_df,
            classifier_path,
            gap_report_path,
            input_fingerprint,
            full_coverage,
            gap_coverage,
        )
    )

    atomic_write_json(
        RECOVERY_PLAN_JSON_PATH,
        recovery_plan,
    )

    # --------------------------------------------------------
    # Re-read outputs
    # --------------------------------------------------------

    written_detail = (
        read_csv_flexible(
            DETAIL_PATH
        )
    )

    written_summary = (
        read_csv_flexible(
            SUMMARY_PATH
        )
    )

    written_targets = (
        read_csv_flexible(
            RECOVERABLE_PATH
        )
    )

    written_structural = (
        read_csv_flexible(
            STRUCTURAL_PATH
        )
    )

    written_review = (
        read_csv_flexible(
            REVIEW_PATH
        )
    )

    if len(written_detail) != len(
        detail_df
    ):
        raise RuntimeError(
            "Written detail row count "
            "mismatch."
        )

    if len(written_summary) != len(
        summary_df
    ):
        raise RuntimeError(
            "Written summary row count "
            "mismatch."
        )

    if len(written_targets) != len(
        targets_df
    ):
        raise RuntimeError(
            "Written recovery target count "
            "mismatch."
        )

    if len(written_structural) != len(
        structural_df
    ):
        raise RuntimeError(
            "Written structural row count "
            "mismatch."
        )

    if len(written_review) != len(
        review_df
    ):
        raise RuntimeError(
            "Written review row count "
            "mismatch."
        )

    # --------------------------------------------------------
    # Verify sources AFTER
    # --------------------------------------------------------

    classifier_sha_after = (
        sha256_file(
            classifier_path
        )
    )

    gap_report_sha_after = (
        sha256_file(
            gap_report_path
        )
    )

    ohlcv_manifest_after = (
        source_manifest_sha256(
            ohlcv_files
        )
    )

    if (
        classifier_sha_before
        != classifier_sha_after
    ):

        raise RuntimeError(
            "Classifier source changed "
            "during review."
        )

    if (
        gap_report_sha_before
        != gap_report_sha_after
    ):

        raise RuntimeError(
            "Gap report changed "
            "during review."
        )

    if (
        ohlcv_manifest_before
        != ohlcv_manifest_after
    ):

        raise RuntimeError(
            "OHLCV source files changed "
            "during review."
        )

    # --------------------------------------------------------
    # Status
    # --------------------------------------------------------

    write_status_csv(
        result="PASSED",
        classifier_path=classifier_path,
        gap_report_path=gap_report_path,
        detail_df=detail_df,
        summary_df=summary_df,
        targets_df=targets_df,
        structural_df=structural_df,
        review_df=review_df,
        resumed_jobs=resumed_jobs,
        processed_jobs=processed_jobs,
        input_fingerprint=input_fingerprint,
        full_coverage=full_coverage,
        gap_coverage=gap_coverage,
    )

    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    recoverable_missing = (
        int(
            targets_df[
                "missing_count"
            ].sum()
        )
        if not targets_df.empty
        else 0
    )

    elapsed = (
        time.monotonic()
        - started
    )

    print_line()

    print(
        "FULL KRW HISTORY GAP "
        "CLASSIFICATION REVIEW SUMMARY"
    )

    print_line()

    print(
        f"Project          : "
        f"{PROJECT_NAME}"
    )

    print(
        f"Version          : "
        f"{VERSION}"
    )

    print(
        "Execution mode   : "
        "READ ONLY REVIEW"
    )

    print()
    print("Full OHLCV coverage:")

    print(
        f"  Markets        : "
        f"{full_coverage['market_count']}"
    )

    print(
        f"  Jobs/files     : "
        f"{full_coverage['job_count']}"
    )

    for timeframe in TIMEFRAMES:

        print(
            f"  {timeframe:<4}           : "
            f"{full_coverage['timeframe_counts'][timeframe]}"
        )

    print()
    print("Gap coverage:")

    print(
        f"  Markets        : "
        f"{gap_coverage['gap_markets']}"
    )

    print(
        f"  Jobs           : "
        f"{gap_coverage['gap_jobs']}"
    )

    print(
        f"  Gap events     : "
        f"{gap_coverage['gap_events']}"
    )

    print()
    print("Classification:")

    print(
        "  RECOVERABLE    : "
        f"{len(targets_df)}"
    )

    print(
        "  STRUCTURAL     : "
        f"{len(structural_df)}"
    )

    print(
        "  REVIEW         : "
        f"{len(review_df)}"
    )

    print(
        "  Recover miss   : "
        f"{recoverable_missing}"
    )

    print()
    print("Resume:")

    print(
        f"  Resumed jobs   : "
        f"{resumed_jobs}"
    )

    print(
        f"  Processed jobs : "
        f"{processed_jobs}"
    )

    print(
        "  Completed jobs : "
        f"{verified_completed}"
    )

    print(
        "  Checkpoint     : "
        "VERIFIED"
    )

    print()
    print("Input:")

    print(
        "  Classifier     : "
        "READ ONLY"
    )

    print(
        "  Gap report     : "
        "READ ONLY"
    )

    print(
        "  OHLCV          : "
        "READ ONLY"
    )

    print()
    print("Output:")

    print(
        "  Detail         : "
        + str(
            DETAIL_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Summary        : "
        + str(
            SUMMARY_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Recovery CSV   : "
        + str(
            RECOVERABLE_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Recovery JSON  : "
        + str(
            RECOVERY_PLAN_JSON_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Structural     : "
        + str(
            STRUCTURAL_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Manual review  : "
        + str(
            REVIEW_PATH.relative_to(
                ROOT
            )
        )
    )

    print(
        "  Status         : "
        + str(
            STATUS_PATH.relative_to(
                ROOT
            )
        )
    )

    print()
    print("Integrity:")

    print(
        "  Full OHLCV     : "
        "VERIFIED"
    )

    print(
        "  Gap coverage   : "
        "VERIFIED"
    )

    print(
        "  Classifier     : "
        "UNCHANGED"
    )

    print(
        "  Gap report     : "
        "UNCHANGED"
    )

    print(
        "  OHLCV          : "
        "UNCHANGED"
    )

    print()
    print("Safety:")

    print(
        "  OHLCV write    : "
        "DISABLED"
    )

    print(
        "  OHLCV delete   : "
        "DISABLED"
    )

    print(
        "  Gap repair     : "
        "DISABLED"
    )

    print(
        "  Feature build  : "
        "DISABLED"
    )

    print(
        "  256 Detector   : "
        "DISABLED"
    )

    print(
        "  Future labels  : "
        "DISABLED"
    )

    print(
        "  Prediction     : "
        "DISABLED"
    )

    print(
        "  Trading        : "
        "DISABLED"
    )

    print(
        "  Git reset      : "
        "DISABLED"
    )

    print(
        "  Git clean      : "
        "DISABLED"
    )

    print(
        "  Git commit     : "
        "DISABLED"
    )

    print(
        "  Git push       : "
        "DISABLED"
    )

    print()

    print(
        f"Elapsed          : "
        f"{elapsed:.2f}s"
    )

    print_line()

    print(
        "[RESULT] FULL KRW HISTORY GAP "
        "CLASSIFICATION REVIEW PASSED"
    )

    print(
        "[PASS] Full OHLCV coverage: "
        f"{full_coverage['market_count']} "
        "markets / "
        f"{full_coverage['job_count']} "
        "jobs."
    )

    print(
        "[PASS] Dynamic gap coverage: "
        f"{gap_coverage['gap_markets']} "
        "markets / "
        f"{gap_coverage['gap_jobs']} "
        "jobs / "
        f"{gap_coverage['gap_events']} "
        "events."
    )

    print(
        "[PASS] Classifier matches "
        "source gap report."
    )

    print(
        "[PASS] Persistent Resume "
        "verified."
    )

    print(
        "[PASS] Recovery target plan "
        "generated."
    )

    print(
        "[PASS] Classification source "
        "remained unchanged."
    )

    print(
        "[PASS] Gap report source "
        "remained unchanged."
    )

    print(
        "[PASS] OHLCV source files "
        "remained unchanged."
    )

    if len(review_df) > 0:

        print(
            "[NOTICE] Manual REVIEW items "
            "exist: "
            f"{len(review_df)}"
        )

        print(
            "[NEXT] Inspect REVIEW items "
            "before actual historical "
            "recovery."
        )

    elif len(targets_df) > 0:

        print(
            "[NEXT] Recovery targets are "
            "ready for actual historical "
            "recovery."
        )

    else:

        print(
            "[NEXT] No RECOVERABLE targets "
            "exist. Historical repair is "
            "not required."
        )

    print_line()

    return 0


# ============================================================
# 22. ARGUMENTS
# ============================================================

def parse_args() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description=(
            "Review History Gap "
            "Classification Clean V002"
        )
    )

    parser.add_argument(
        "--expected-full-markets",
        type=int,
        default=(
            DEFAULT_EXPECTED_FULL_MARKETS
        ),
        help=(
            "Expected unique markets in the "
            "FULL OHLCV source dataset. "
            "This is NOT the classifier "
            "market count. Use 0 to disable."
        ),
    )

    parser.add_argument(
        "--expected-full-jobs",
        type=int,
        default=(
            DEFAULT_EXPECTED_FULL_JOBS
        ),
        help=(
            "Expected market/timeframe jobs "
            "in the FULL OHLCV source "
            "dataset. This is NOT the "
            "classifier job count. "
            "Use 0 to disable."
        ),
    )

    parser.add_argument(
        "--checkpoint-every",
        type=int,
        default=10,
        help=(
            "Persist checkpoint every N "
            "newly processed gap jobs."
        ),
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Revalidate every gap job even "
            "when a compatible checkpoint "
            "exists."
        ),
    )

    return parser.parse_args()


# ============================================================
# 23. ENTRY POINT
# ============================================================

def main() -> int:

    args = parse_args()

    try:

        return run_review(
            expected_full_markets=max(
                0,
                args.expected_full_markets,
            ),
            expected_full_jobs=max(
                0,
                args.expected_full_jobs,
            ),
            checkpoint_every=max(
                1,
                args.checkpoint_every,
            ),
            force=bool(
                args.force
            ),
        )

    except KeyboardInterrupt:

        print()
        print_line()

        print(
            "[INTERRUPTED] Review stopped "
            "by user."
        )

        print(
            "[RESUME] Successfully completed "
            "checkpoint entries remain "
            "available."
        )

        print(
            "[SAFETY] No source cleanup "
            "was executed."
        )

        print_line()

        return 130

    except Exception as exc:

        print()
        print_line()

        print(
            "HISTORY GAP CLASSIFICATION "
            "REVIEW FATAL ERROR"
        )

        print_line()

        print(
            f"{type(exc).__name__}: "
            f"{exc}"
        )

        print()

        print(
            "[SAFETY] No automatic source "
            "deletion was executed."
        )

        print(
            "[SAFETY] No Git reset/clean "
            "was executed."
        )

        print(
            "[RESUME] Successfully completed "
            "checkpoint entries remain "
            "available."
        )

        print_line()

        return 1


if __name__ == "__main__":
    sys.exit(main())
