"""
Upbit Surge Monitor
Collector Data Validator

Version:
    Clean V001

Purpose:
    Validate OHLCV files generated by collector.py.

Important:
    - This script NEVER modifies OHLCV source files.
    - This script only reads and validates collected data.
    - Designed for Windows PC execution with:
          py validate_collector.py

Expected structure:

    data/
    ├── ohlcv/
    │   ├── h1/
    │   ├── h4/
    │   └── d1/
    └── collector_status.csv
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VERSION = "Clean V001"

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
OHLCV_DIR = DATA_DIR / "ohlcv"

TIMEFRAME_DIRS = {
    "h1": OHLCV_DIR / "h1",
    "h4": OHLCV_DIR / "h4",
    "d1": OHLCV_DIR / "d1",
}

EXPECTED_MARKET_COUNT = 289

EXPECTED_TIMEFRAME_COUNTS = {
    "h1": EXPECTED_MARKET_COUNT,
    "h4": EXPECTED_MARKET_COUNT,
    "d1": EXPECTED_MARKET_COUNT,
}

# Different collector versions may use slightly different timestamp names.
TIMESTAMP_CANDIDATES = (
    "timestamp",
    "datetime",
    "candle_date_time_utc",
    "candle_date_time_kst",
)

# Standard OHLCV names expected from the clean collector.
REQUIRED_OHLC_COLUMNS = (
    "open",
    "high",
    "low",
    "close",
    "volume",
)

# Optional columns that may exist but are not required.
OPTIONAL_COLUMNS = (
    "market",
    "trade_price",
    "trade_value",
    "candle_acc_trade_price",
    "candle_acc_trade_volume",
)


# ============================================================
# RESULT MODELS
# ============================================================

@dataclass
class FileValidationResult:
    timeframe: str
    market: str
    path: Path

    passed: bool = True
    row_count: int = 0

    first_timestamp: str = ""
    last_timestamp: str = ""

    timestamp_column: str = ""

    duplicate_timestamps: int = 0
    invalid_timestamps: int = 0
    unsorted_timestamps: int = 0

    missing_required_columns: list[str] = field(default_factory=list)

    nan_open: int = 0
    nan_high: int = 0
    nan_low: int = 0
    nan_close: int = 0
    nan_volume: int = 0

    negative_open: int = 0
    negative_high: int = 0
    negative_low: int = 0
    negative_close: int = 0
    negative_volume: int = 0

    invalid_high_low: int = 0
    invalid_high_open: int = 0
    invalid_high_close: int = 0
    invalid_low_open: int = 0
    invalid_low_close: int = 0

    infinite_values: int = 0

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class TimeframeValidationResult:
    timeframe: str
    directory: Path

    directory_exists: bool = False
    file_count: int = 0
    expected_file_count: int = 0

    total_rows: int = 0
    passed_files: int = 0
    failed_files: int = 0

    files: list[FileValidationResult] = field(default_factory=list)

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ============================================================
# DISPLAY HELPERS
# ============================================================

def print_separator(char: str = "=", width: int = 78) -> None:
    print(char * width)


def print_header(title: str) -> None:
    print()
    print_separator("=")
    print(title)
    print_separator("=")


def safe_text(value: Any) -> str:
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    return str(value)


# ============================================================
# COLUMN HELPERS
# ============================================================

def normalize_column_name(column: str) -> str:
    return str(column).strip().lower()


def build_column_lookup(df: pd.DataFrame) -> dict[str, str]:
    lookup: dict[str, str] = {}

    for column in df.columns:
        normalized = normalize_column_name(column)

        if normalized not in lookup:
            lookup[normalized] = column

    return lookup


def find_timestamp_column(df: pd.DataFrame) -> str | None:
    lookup = build_column_lookup(df)

    for candidate in TIMESTAMP_CANDIDATES:
        if candidate in lookup:
            return lookup[candidate]

    return None


def find_required_column(
    df: pd.DataFrame,
    required_name: str,
) -> str | None:
    lookup = build_column_lookup(df)
    return lookup.get(required_name)


# ============================================================
# NUMERIC HELPERS
# ============================================================

def to_numeric_series(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def count_nan(series: pd.Series) -> int:
    numeric = to_numeric_series(series)
    return int(numeric.isna().sum())


def count_negative(series: pd.Series) -> int:
    numeric = to_numeric_series(series)
    return int((numeric < 0).fillna(False).sum())


def count_infinite_in_columns(
    df: pd.DataFrame,
    columns: list[str],
) -> int:
    total = 0

    for column in columns:
        numeric = to_numeric_series(df[column])

        values = numeric.to_numpy(dtype=float, na_value=np.nan)

        total += int(np.isinf(values).sum())

    return total


# ============================================================
# TIMESTAMP VALIDATION
# ============================================================

def validate_timestamp(
    df: pd.DataFrame,
    result: FileValidationResult,
) -> pd.Series | None:
    timestamp_column = find_timestamp_column(df)

    if timestamp_column is None:
        result.passed = False
        result.errors.append(
            "Timestamp column not found. "
            f"Expected one of: {', '.join(TIMESTAMP_CANDIDATES)}"
        )
        return None

    result.timestamp_column = timestamp_column

    timestamps = pd.to_datetime(
        df[timestamp_column],
        errors="coerce",
        utc=True,
    )

    result.invalid_timestamps = int(timestamps.isna().sum())

    if result.invalid_timestamps > 0:
        result.passed = False
        result.errors.append(
            f"Invalid timestamps: {result.invalid_timestamps:,}"
        )

    valid_timestamps = timestamps.dropna()

    if valid_timestamps.empty:
        result.passed = False
        result.errors.append("No valid timestamps found.")
        return timestamps

    result.first_timestamp = safe_text(valid_timestamps.min())
    result.last_timestamp = safe_text(valid_timestamps.max())

    result.duplicate_timestamps = int(
        valid_timestamps.duplicated(keep=False).sum()
    )

    if result.duplicate_timestamps > 0:
        result.passed = False
        result.errors.append(
            "Duplicate timestamp rows: "
            f"{result.duplicate_timestamps:,}"
        )

    # Check whether valid timestamps are stored in ascending order.
    valid_array = valid_timestamps.reset_index(drop=True)

    if len(valid_array) >= 2:
        diff = valid_array.diff()

        result.unsorted_timestamps = int(
            (diff.iloc[1:] < pd.Timedelta(0)).sum()
        )

        if result.unsorted_timestamps > 0:
            result.passed = False
            result.errors.append(
                "Timestamp order errors: "
                f"{result.unsorted_timestamps:,}"
            )

    return timestamps


# ============================================================
# OHLCV VALIDATION
# ============================================================

def validate_required_columns(
    df: pd.DataFrame,
    result: FileValidationResult,
) -> dict[str, str]:
    resolved: dict[str, str] = {}

    for required in REQUIRED_OHLC_COLUMNS:
        actual = find_required_column(df, required)

        if actual is None:
            result.missing_required_columns.append(required)
        else:
            resolved[required] = actual

    if result.missing_required_columns:
        result.passed = False
        result.errors.append(
            "Missing required columns: "
            + ", ".join(result.missing_required_columns)
        )

    return resolved


def validate_numeric_columns(
    df: pd.DataFrame,
    columns: dict[str, str],
    result: FileValidationResult,
) -> dict[str, pd.Series]:
    numeric: dict[str, pd.Series] = {}

    for logical_name, actual_name in columns.items():
        numeric[logical_name] = to_numeric_series(df[actual_name])

    if "open" in numeric:
        result.nan_open = int(numeric["open"].isna().sum())
        result.negative_open = int((numeric["open"] < 0).fillna(False).sum())

    if "high" in numeric:
        result.nan_high = int(numeric["high"].isna().sum())
        result.negative_high = int((numeric["high"] < 0).fillna(False).sum())

    if "low" in numeric:
        result.nan_low = int(numeric["low"].isna().sum())
        result.negative_low = int((numeric["low"] < 0).fillna(False).sum())

    if "close" in numeric:
        result.nan_close = int(numeric["close"].isna().sum())
        result.negative_close = int(
            (numeric["close"] < 0).fillna(False).sum()
        )

    if "volume" in numeric:
        result.nan_volume = int(numeric["volume"].isna().sum())
        result.negative_volume = int(
            (numeric["volume"] < 0).fillna(False).sum()
        )

    nan_total = (
        result.nan_open
        + result.nan_high
        + result.nan_low
        + result.nan_close
        + result.nan_volume
    )

    negative_total = (
        result.negative_open
        + result.negative_high
        + result.negative_low
        + result.negative_close
        + result.negative_volume
    )

    if nan_total > 0:
        result.passed = False
        result.errors.append(
            f"NaN/non-numeric OHLCV values: {nan_total:,}"
        )

    if negative_total > 0:
        result.passed = False
        result.errors.append(
            f"Negative OHLCV values: {negative_total:,}"
        )

    actual_columns = list(columns.values())

    if actual_columns:
        result.infinite_values = count_infinite_in_columns(
            df,
            actual_columns,
        )

        if result.infinite_values > 0:
            result.passed = False
            result.errors.append(
                f"Infinite OHLCV values: {result.infinite_values:,}"
            )

    return numeric


def validate_ohlc_logic(
    numeric: dict[str, pd.Series],
    result: FileValidationResult,
) -> None:
    required = {"open", "high", "low", "close"}

    if not required.issubset(numeric):
        return

    open_series = numeric["open"]
    high_series = numeric["high"]
    low_series = numeric["low"]
    close_series = numeric["close"]

    result.invalid_high_low = int(
        (high_series < low_series).fillna(False).sum()
    )

    result.invalid_high_open = int(
        (high_series < open_series).fillna(False).sum()
    )

    result.invalid_high_close = int(
        (high_series < close_series).fillna(False).sum()
    )

    result.invalid_low_open = int(
        (low_series > open_series).fillna(False).sum()
    )

    result.invalid_low_close = int(
        (low_series > close_series).fillna(False).sum()
    )

    invalid_total = (
        result.invalid_high_low
        + result.invalid_high_open
        + result.invalid_high_close
        + result.invalid_low_open
        + result.invalid_low_close
    )

    if invalid_total > 0:
        result.passed = False
        result.errors.append(
            f"Invalid OHLC relationships: {invalid_total:,}"
        )


# ============================================================
# FILE VALIDATION
# ============================================================

def validate_file(
    timeframe: str,
    path: Path,
) -> FileValidationResult:
    result = FileValidationResult(
        timeframe=timeframe,
        market=path.stem,
        path=path,
    )

    try:
        if not path.exists():
            result.passed = False
            result.errors.append("File does not exist.")
            return result

        if path.stat().st_size == 0:
            result.passed = False
            result.errors.append("File is empty.")
            return result

        try:
            df = pd.read_csv(
                path,
                low_memory=False,
            )
        except Exception as exc:
            result.passed = False
            result.errors.append(
                f"CSV read failed: {type(exc).__name__}: {exc}"
            )
            return result

        result.row_count = len(df)

        if result.row_count == 0:
            result.passed = False
            result.errors.append("CSV contains zero rows.")
            return result

        if len(df.columns) == 0:
            result.passed = False
            result.errors.append("CSV contains zero columns.")
            return result

        validate_timestamp(
            df=df,
            result=result,
        )

        required_columns = validate_required_columns(
            df=df,
            result=result,
        )

        numeric = validate_numeric_columns(
            df=df,
            columns=required_columns,
            result=result,
        )

        validate_ohlc_logic(
            numeric=numeric,
            result=result,
        )

    except Exception as exc:
        result.passed = False
        result.errors.append(
            f"Unexpected validation error: "
            f"{type(exc).__name__}: {exc}"
        )

    return result


# ============================================================
# TIMEFRAME VALIDATION
# ============================================================

def validate_timeframe(
    timeframe: str,
    directory: Path,
) -> TimeframeValidationResult:
    expected_count = EXPECTED_TIMEFRAME_COUNTS[timeframe]

    result = TimeframeValidationResult(
        timeframe=timeframe,
        directory=directory,
        expected_file_count=expected_count,
    )

    print()
    print_separator("-")
    print(f"VALIDATING TIMEFRAME: {timeframe.upper()}")
    print_separator("-")
    print(f"Directory : {directory}")

    if not directory.exists():
        result.errors.append(
            f"Directory not found: {directory}"
        )

        print("[FAIL] Directory not found.")
        return result

    if not directory.is_dir():
        result.errors.append(
            f"Path is not a directory: {directory}"
        )

        print("[FAIL] Path is not a directory.")
        return result

    result.directory_exists = True

    files = sorted(
        directory.glob("*.csv"),
        key=lambda item: item.name.upper(),
    )

    result.file_count = len(files)

    print(f"CSV files : {result.file_count:,}")
    print(f"Expected  : {expected_count:,}")

    if result.file_count != expected_count:
        result.errors.append(
            "Unexpected CSV file count: "
            f"{result.file_count:,} "
            f"(expected {expected_count:,})"
        )

    if not files:
        print("[FAIL] No CSV files found.")
        return result

    total_files = len(files)

    for index, path in enumerate(files, start=1):
        file_result = validate_file(
            timeframe=timeframe,
            path=path,
        )

        result.files.append(file_result)
        result.total_rows += file_result.row_count

        if file_result.passed:
            result.passed_files += 1
            status = "OK"
        else:
            result.failed_files += 1
            status = "FAIL"

        print(
            f"[{index:03d}/{total_files:03d}] "
            f"{path.stem:<18} "
            f"{status:<4} "
            f"rows={file_result.row_count:,}"
        )

        if not file_result.passed:
            for error in file_result.errors:
                print(f"    [ERROR] {error}")

            for warning in file_result.warnings:
                print(f"    [WARN ] {warning}")

    print()
    print(
        f"[{timeframe.upper()}] "
        f"files={result.file_count:,} | "
        f"passed={result.passed_files:,} | "
        f"failed={result.failed_files:,} | "
        f"rows={result.total_rows:,}"
    )

    return result


# ============================================================
# CROSS-TIMEFRAME VALIDATION
# ============================================================

def get_market_names(
    timeframe_result: TimeframeValidationResult,
) -> set[str]:
    return {
        item.market.upper()
        for item in timeframe_result.files
    }


def compare_market_sets(
    results: dict[str, TimeframeValidationResult],
) -> list[str]:
    errors: list[str] = []

    if not all(
        timeframe in results
        for timeframe in ("h1", "h4", "d1")
    ):
        errors.append(
            "Cannot compare market sets because "
            "one or more timeframe results are missing."
        )
        return errors

    h1_markets = get_market_names(results["h1"])
    h4_markets = get_market_names(results["h4"])
    d1_markets = get_market_names(results["d1"])

    all_markets = h1_markets | h4_markets | d1_markets

    for market in sorted(all_markets):
        missing_from: list[str] = []

        if market not in h1_markets:
            missing_from.append("h1")

        if market not in h4_markets:
            missing_from.append("h4")

        if market not in d1_markets:
            missing_from.append("d1")

        if missing_from:
            errors.append(
                f"{market} missing from: "
                + ", ".join(missing_from)
            )

    return errors


# ============================================================
# REPORT HELPERS
# ============================================================

def collect_failed_files(
    results: dict[str, TimeframeValidationResult],
) -> list[FileValidationResult]:
    failed: list[FileValidationResult] = []

    for timeframe_result in results.values():
        for file_result in timeframe_result.files:
            if not file_result.passed:
                failed.append(file_result)

    return failed


def calculate_total_files(
    results: dict[str, TimeframeValidationResult],
) -> int:
    return sum(
        result.file_count
        for result in results.values()
    )


def calculate_total_rows(
    results: dict[str, TimeframeValidationResult],
) -> int:
    return sum(
        result.total_rows
        for result in results.values()
    )


def calculate_passed_files(
    results: dict[str, TimeframeValidationResult],
) -> int:
    return sum(
        result.passed_files
        for result in results.values()
    )


def calculate_failed_files(
    results: dict[str, TimeframeValidationResult],
) -> int:
    return sum(
        result.failed_files
        for result in results.values()
    )


def print_timeframe_summary(
    results: dict[str, TimeframeValidationResult],
) -> None:
    print()
    print_separator("-")
    print("TIMEFRAME SUMMARY")
    print_separator("-")

    print(
        f"{'TF':<6}"
        f"{'FILES':>10}"
        f"{'EXPECTED':>12}"
        f"{'PASSED':>10}"
        f"{'FAILED':>10}"
        f"{'ROWS':>16}"
    )

    print_separator("-", 64)

    for timeframe in ("h1", "h4", "d1"):
        result = results[timeframe]

        print(
            f"{timeframe.upper():<6}"
            f"{result.file_count:>10,}"
            f"{result.expected_file_count:>12,}"
            f"{result.passed_files:>10,}"
            f"{result.failed_files:>10,}"
            f"{result.total_rows:>16,}"
        )


def print_failed_file_summary(
    failed_files: list[FileValidationResult],
) -> None:
    if not failed_files:
        return

    print()
    print_separator("-")
    print("FAILED FILES")
    print_separator("-")

    for result in failed_files:
        print(
            f"[{result.timeframe.upper()}] "
            f"{result.market}"
        )

        print(f"  Path : {result.path}")

        for error in result.errors:
            print(f"  ERROR: {error}")

        for warning in result.warnings:
            print(f"  WARN : {warning}")


# ============================================================
# MAIN VALIDATION
# ============================================================

def main() -> int:
    print_header("UPBIT SURGE MONITOR - COLLECTOR DATA VALIDATOR")

    print(f"Project root       : {BASE_DIR}")
    print(f"Data directory     : {DATA_DIR}")
    print(f"OHLCV directory    : {OHLCV_DIR}")
    print(f"Expected markets   : {EXPECTED_MARKET_COUNT:,}")
    print("Timeframes         : h1 / h4 / d1")
    print()
    print("Mode               : READ ONLY")
    print("Source modification: DISABLED")

    overall_errors: list[str] = []

    if not DATA_DIR.exists():
        print()
        print(f"[FAIL] Data directory not found: {DATA_DIR}")
        return 1

    if not OHLCV_DIR.exists():
        print()
        print(f"[FAIL] OHLCV directory not found: {OHLCV_DIR}")
        return 1

    results: dict[str, TimeframeValidationResult] = {}

    for timeframe in ("h1", "h4", "d1"):
        results[timeframe] = validate_timeframe(
            timeframe=timeframe,
            directory=TIMEFRAME_DIRS[timeframe],
        )

    # --------------------------------------------------------
    # Validate directory/file counts
    # --------------------------------------------------------

    for timeframe, result in results.items():
        if not result.directory_exists:
            overall_errors.append(
                f"{timeframe}: directory missing"
            )

        if result.file_count != result.expected_file_count:
            overall_errors.append(
                f"{timeframe}: "
                f"{result.file_count:,} files found, "
                f"{result.expected_file_count:,} expected"
            )

        if result.failed_files > 0:
            overall_errors.append(
                f"{timeframe}: "
                f"{result.failed_files:,} invalid files"
            )

    # --------------------------------------------------------
    # Compare markets between h1/h4/d1
    # --------------------------------------------------------

    print()
    print_separator("-")
    print("CROSS-TIMEFRAME MARKET CHECK")
    print_separator("-")

    market_errors = compare_market_sets(results)

    if market_errors:
        print(
            f"[FAIL] Market-set differences: "
            f"{len(market_errors):,}"
        )

        for error in market_errors:
            print(f"  {error}")

        overall_errors.extend(market_errors)

    else:
        print(
            "[PASS] h1 / h4 / d1 contain "
            "the same market set."
        )

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print_timeframe_summary(results)

    failed_files = collect_failed_files(results)

    print_failed_file_summary(failed_files)

    total_files = calculate_total_files(results)
    total_rows = calculate_total_rows(results)
    passed_files = calculate_passed_files(results)
    failed_file_count = calculate_failed_files(results)

    print()
    print_separator("=")
    print("VALIDATION SUMMARY")
    print_separator("=")

    print(f"Project              : {PROJECT_NAME}")
    print(f"Version              : {VERSION}")
    print(f"Expected markets     : {EXPECTED_MARKET_COUNT:,}")
    print(f"Expected files       : {EXPECTED_MARKET_COUNT * 3:,}")
    print(f"Actual files         : {total_files:,}")
    print(f"Passed files         : {passed_files:,}")
    print(f"Failed files         : {failed_file_count:,}")
    print(f"Total OHLCV rows     : {total_rows:,}")
    print(f"Cross-market errors  : {len(market_errors):,}")
    print(f"Overall errors       : {len(overall_errors):,}")

    print_separator("=")

    if overall_errors:
        print("[RESULT] COLLECTOR VALIDATION FAILED")
        print()
        print("Detected problems:")

        for index, error in enumerate(
            overall_errors,
            start=1,
        ):
            print(f"  {index:03d}. {error}")

        print_separator("=")
        return 1

    print("[RESULT] COLLECTOR VALIDATION PASSED")
    print(
        "[PASS] All expected OHLCV files passed "
        "the validation checks."
    )
    print_separator("=")

    return 0


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    try:
        exit_code = main()

    except KeyboardInterrupt:
        print()
        print("[STOP] Validation interrupted by user.")
        exit_code = 130

    except Exception as exc:
        print()
        print_separator("=")
        print("VALIDATOR FATAL ERROR")
        print_separator("=")
        print(
            f"{type(exc).__name__}: {exc}"
        )
        print_separator("=")
        exit_code = 1

    sys.exit(exit_code)
