"""
Upbit Surge Monitor
256 Detector Output Validator

Version:
    Clean V002

File:
    validate_256.py

Purpose:
    Validate output generated by detect_256.py.

Main responsibilities:
    - Validate KRW-BTC h1 / h4 / d1 OHLCV, Feature, and Signal CSV files.
    - Verify OHLCV / Feature / Signal timestamp integrity.
    - Correctly parse Unix timestamps stored in milliseconds.
    - Verify Feature / Signal row alignment.
    - Verify OHLC sanity.
    - Verify MA / score / research-state columns when present.
    - Use signal_setup / signal_ready / signal_trigger as the official
      detector state columns.
    - Inspect signal_stage only as supplementary information.
    - Detect suspicious future-information / target columns.
    - Verify source files remain unchanged during validation.
    - NEVER modify OHLCV, Feature, or Signal source files.

Important:
    This validator is READ ONLY.

Expected structure:

    data/
        ohlcv/
            h1/
                KRW-BTC.csv
            h4/
                KRW-BTC.csv
            d1/
                KRW-BTC.csv

        features/
            h1/
                KRW-BTC.csv
            h4/
                KRW-BTC.csv
            d1/
                KRW-BTC.csv

        signals/
            256/
                h1/
                    KRW-BTC.csv
                h4/
                    KRW-BTC.csv
                d1/
                    KRW-BTC.csv

Windows execution:

    py validate_256.py
"""

from __future__ import annotations

import hashlib
import math
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VALIDATOR_NAME = "256 Validator Clean V002"
VERSION = "Clean V002"

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
OHLCV_DIR = DATA_DIR / "ohlcv"
FEATURE_DIR = DATA_DIR / "features"
SIGNAL_DIR = DATA_DIR / "signals" / "256"

TIMEFRAMES = ("h1", "h4", "d1")
MARKETS = ("KRW-BTC",)

TIMESTAMP_CANDIDATES = (
    "timestamp",
    "candle_date_time_utc",
    "datetime",
    "candle_date_time_kst",
)

REQUIRED_OHLC_COLUMNS = (
    "open",
    "high",
    "low",
    "close",
    "volume",
)

OFFICIAL_STATE_COLUMNS = (
    "signal_setup",
    "signal_ready",
    "signal_trigger",
)

SCORE_COLUMNS = (
    "setup_score",
    "ready_score",
    "trigger_score",
)

MA_PREFIXES = (
    "ma",
    "sma",
    "ema",
)

FORBIDDEN_FUTURE_PATTERNS = (
    "future_",
    "future-",
    "future ",
    "next_",
    "next-",
    "next ",
    "forward_",
    "forward-",
    "forward ",
    "target",
    "label",
    "outcome",
)

ALLOWED_NEXT_COLUMNS = {
    # Keep empty unless a legitimate historical-only column
    # intentionally contains "next" in its name.
}

TRUE_VALUES = {
    "1",
    "1.0",
    "true",
    "t",
    "yes",
    "y",
}

FALSE_VALUES = {
    "0",
    "0.0",
    "false",
    "f",
    "no",
    "n",
    "",
    "nan",
    "none",
    "null",
}


# ============================================================
# RESULT MODEL
# ============================================================

@dataclass
class ValidationResult:
    market: str
    timeframe: str

    ohlcv_path: Path
    feature_path: Path
    signal_path: Path

    passed: bool = True

    ohlcv_rows: int = 0
    feature_rows: int = 0
    signal_rows: int = 0

    setup_count: int = 0
    ready_count: int = 0
    trigger_count: int = 0

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    elapsed_seconds: float = 0.0

    def fail(self, message: str) -> None:
        self.passed = False
        self.errors.append(message)
        print(f"[FAIL] {message}")

    def warn(self, message: str) -> None:
        self.warnings.append(message)
        print(f"[WARN] {message}")

    def passed_message(self, message: str) -> None:
        print(f"[PASS] {message}")


# ============================================================
# BASIC HELPERS
# ============================================================

def separator(char: str = "-", length: int = 72) -> None:
    print(char * length)


def utc_now_text() -> str:
    return datetime.now(timezone.utc).isoformat()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file:
        while True:
            block = file.read(1024 * 1024)

            if not block:
                break

            digest.update(block)

    return digest.hexdigest()


def file_size_text(path: Path) -> str:
    try:
        return f"{path.stat().st_size:,} bytes"
    except Exception:
        return "unknown size"


def normalize_column_name(value: Any) -> str:
    return str(value).strip()


def find_timestamp_column(df: pd.DataFrame) -> str | None:
    columns = {str(column).strip(): column for column in df.columns}

    for candidate in TIMESTAMP_CANDIDATES:
        if candidate in columns:
            return columns[candidate]

    return None


def safe_read_csv(
    path: Path,
    label: str,
    result: ValidationResult,
) -> pd.DataFrame | None:
    if not path.exists():
        result.fail(f"{label} file does not exist: {path}")
        return None

    if not path.is_file():
        result.fail(f"{label} path is not a file: {path}")
        return None

    result.passed_message(
        f"{label} file exists ({file_size_text(path)})"
    )

    try:
        df = pd.read_csv(
            path,
            low_memory=False,
        )
    except Exception as exc:
        result.fail(
            f"{label} CSV read failed: "
            f"{type(exc).__name__}: {exc}"
        )
        return None

    result.passed_message(
        f"{label} dataframe rows={len(df):,}, "
        f"columns={len(df.columns):,}"
    )

    return df


# ============================================================
# TIMESTAMP PARSER - CLEAN V002
# ============================================================

def _numeric_timestamp_to_datetime(
    numeric: pd.Series,
) -> pd.Series:
    """
    Convert numeric timestamps using magnitude-aware Unix units.

    Typical values:

        seconds:
            1506311839

        milliseconds:
            1506311839886

        microseconds:
            1506311839886000

        nanoseconds:
            1506311839886000000

    Clean V002 specifically fixes the project OHLCV format:

        1506311839886.0

    which is Unix milliseconds.
    """

    result = pd.Series(
        pd.NaT,
        index=numeric.index,
        dtype="datetime64[ns, UTC]",
    )

    valid = numeric.notna()

    if not valid.any():
        return result

    absolute = numeric.abs()

    # Unix seconds.
    mask_seconds = (
        valid
        & (absolute < 1.0e11)
    )

    # Unix milliseconds.
    mask_milliseconds = (
        valid
        & (absolute >= 1.0e11)
        & (absolute < 1.0e14)
    )

    # Unix microseconds.
    mask_microseconds = (
        valid
        & (absolute >= 1.0e14)
        & (absolute < 1.0e17)
    )

    # Unix nanoseconds.
    mask_nanoseconds = (
        valid
        & (absolute >= 1.0e17)
    )

    if mask_seconds.any():
        result.loc[mask_seconds] = pd.to_datetime(
            numeric.loc[mask_seconds],
            unit="s",
            utc=True,
            errors="coerce",
        )

    if mask_milliseconds.any():
        result.loc[mask_milliseconds] = pd.to_datetime(
            numeric.loc[mask_milliseconds],
            unit="ms",
            utc=True,
            errors="coerce",
        )

    if mask_microseconds.any():
        result.loc[mask_microseconds] = pd.to_datetime(
            numeric.loc[mask_microseconds],
            unit="us",
            utc=True,
            errors="coerce",
        )

    if mask_nanoseconds.any():
        result.loc[mask_nanoseconds] = pd.to_datetime(
            numeric.loc[mask_nanoseconds],
            unit="ns",
            utc=True,
            errors="coerce",
        )

    return result


def parse_timestamp_series(
    series: pd.Series,
) -> pd.Series:
    """
    Robust timestamp parser.

    Handles:
        - Unix seconds
        - Unix milliseconds
        - Unix microseconds
        - Unix nanoseconds
        - Numeric values stored as strings
        - Numeric values stored with ".0"
        - ISO / datetime strings

    Numeric-looking values are parsed numerically first.
    Remaining values are parsed as datetime strings.
    """

    output = pd.Series(
        pd.NaT,
        index=series.index,
        dtype="datetime64[ns, UTC]",
    )

    if len(series) == 0:
        return output

    raw = series.copy()

    numeric = pd.to_numeric(
        raw,
        errors="coerce",
    )

    numeric_mask = numeric.notna()

    if numeric_mask.any():
        numeric_parsed = _numeric_timestamp_to_datetime(
            numeric
        )

        output.loc[numeric_mask] = numeric_parsed.loc[
            numeric_mask
        ]

    remaining_mask = output.isna() & raw.notna()

    if remaining_mask.any():
        string_values = (
            raw.loc[remaining_mask]
            .astype(str)
            .str.strip()
        )

        string_values = string_values.replace(
            {
                "": np.nan,
                "nan": np.nan,
                "NaN": np.nan,
                "None": np.nan,
                "null": np.nan,
                "NULL": np.nan,
            }
        )

        parsed_strings = pd.to_datetime(
            string_values,
            utc=True,
            errors="coerce",
        )

        output.loc[remaining_mask] = parsed_strings

    return output


# ============================================================
# COLUMN VALIDATION
# ============================================================

def validate_unique_columns(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> None:
    duplicated = (
        pd.Index(df.columns)
        .duplicated(keep=False)
    )

    if duplicated.any():
        duplicates = (
            pd.Index(df.columns)[duplicated]
            .astype(str)
            .tolist()
        )

        result.fail(
            f"{label} duplicate column names: "
            f"{duplicates}"
        )
        return

    result.passed_message(
        f"{label} column names are unique."
    )


def validate_required_ohlc_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    missing = [
        column
        for column in REQUIRED_OHLC_COLUMNS
        if column not in df.columns
    ]

    if missing:
        result.fail(
            "OHLCV missing required columns: "
            + ", ".join(missing)
        )
        return

    result.passed_message(
        "OHLCV required OHLCV columns are present."
    )


# ============================================================
# TIMESTAMP VALIDATION
# ============================================================

def validate_timestamp_integrity(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> tuple[str | None, pd.Series | None]:
    timestamp_column = find_timestamp_column(df)

    if timestamp_column is None:
        result.fail(
            f"{label} has no supported timestamp column. "
            f"Expected one of: {TIMESTAMP_CANDIDATES}"
        )
        return None, None

    parsed = parse_timestamp_series(
        df[timestamp_column]
    )

    parse_failures = int(parsed.isna().sum())

    if parse_failures:
        result.fail(
            f"{label} timestamp parse failures="
            f"{parse_failures:,}"
        )
    else:
        result.passed_message(
            f"{label} timestamps parsed successfully."
        )

    valid = parsed.dropna()

    duplicate_count = int(
        valid.duplicated(keep=False).sum()
    )

    if duplicate_count:
        result.fail(
            f"{label} duplicate timestamps="
            f"{duplicate_count:,}"
        )
    else:
        result.passed_message(
            f"{label} timestamps are unique."
        )

    if len(valid) > 1:
        chronological = bool(
            valid.is_monotonic_increasing
        )

        if chronological:
            result.passed_message(
                f"{label} timestamps are chronological."
            )
        else:
            result.fail(
                f"{label} timestamps are not chronological."
            )
    else:
        result.passed_message(
            f"{label} timestamp chronology check passed."
        )

    if len(valid):
        first_timestamp = valid.iloc[0]
        last_timestamp = valid.iloc[-1]

        print(
            f"[INFO] {label} timestamp range: "
            f"{first_timestamp} -> {last_timestamp}"
        )

    return timestamp_column, parsed


# ============================================================
# ROW / TIMESTAMP ALIGNMENT
# ============================================================

def validate_row_counts(
    ohlcv: pd.DataFrame,
    feature: pd.DataFrame,
    signal: pd.DataFrame,
    result: ValidationResult,
) -> None:
    result.ohlcv_rows = len(ohlcv)
    result.feature_rows = len(feature)
    result.signal_rows = len(signal)

    if (
        result.ohlcv_rows
        == result.feature_rows
        == result.signal_rows
    ):
        result.passed_message(
            "OHLCV / Feature / Signal row counts are 1:1 "
            f"({result.signal_rows:,} rows)."
        )
    else:
        result.fail(
            "OHLCV / Feature / Signal row-count mismatch: "
            f"OHLCV={result.ohlcv_rows:,}, "
            f"Feature={result.feature_rows:,}, "
            f"Signal={result.signal_rows:,}"
        )


def validate_timestamp_alignment(
    ohlcv_ts: pd.Series | None,
    feature_ts: pd.Series | None,
    signal_ts: pd.Series | None,
    result: ValidationResult,
) -> None:
    if (
        ohlcv_ts is None
        or feature_ts is None
        or signal_ts is None
    ):
        result.fail(
            "Timestamp alignment could not be checked."
        )
        return

    if not (
        len(ohlcv_ts)
        == len(feature_ts)
        == len(signal_ts)
    ):
        result.fail(
            "Timestamp alignment skipped because row counts differ."
        )
        return

    if (
        ohlcv_ts.isna().any()
        or feature_ts.isna().any()
        or signal_ts.isna().any()
    ):
        result.fail(
            "Timestamp alignment cannot pass while parsed "
            "timestamps contain NaT."
        )
        return

    feature_equal = bool(
        ohlcv_ts.reset_index(drop=True).equals(
            feature_ts.reset_index(drop=True)
        )
    )

    signal_equal = bool(
        ohlcv_ts.reset_index(drop=True).equals(
            signal_ts.reset_index(drop=True)
        )
    )

    if feature_equal:
        result.passed_message(
            "Feature timestamps match OHLCV 1:1."
        )
    else:
        result.fail(
            "Feature timestamps do not match OHLCV 1:1."
        )

    if signal_equal:
        result.passed_message(
            "Signal timestamps match OHLCV 1:1."
        )
    else:
        result.fail(
            "Signal timestamps do not match OHLCV 1:1."
        )


# ============================================================
# OHLCV VALIDATION
# ============================================================

def numeric_series(
    df: pd.DataFrame,
    column: str,
) -> pd.Series:
    return pd.to_numeric(
        df[column],
        errors="coerce",
    )


def validate_ohlcv_values(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    missing = [
        column
        for column in REQUIRED_OHLC_COLUMNS
        if column not in df.columns
    ]

    if missing:
        return

    numeric = {
        column: numeric_series(df, column)
        for column in REQUIRED_OHLC_COLUMNS
    }

    for column, series in numeric.items():
        invalid_numeric = int(series.isna().sum())

        if invalid_numeric:
            result.fail(
                f"OHLCV {column} invalid/NaN values="
                f"{invalid_numeric:,}"
            )
        else:
            result.passed_message(
                f"OHLCV {column} numeric values valid."
            )

        finite = np.isfinite(
            series.to_numpy(dtype=float, na_value=np.nan)
        )

        non_finite = int((~finite).sum())

        if non_finite:
            result.fail(
                f"OHLCV {column} non-finite values="
                f"{non_finite:,}"
            )

    open_price = numeric["open"]
    high_price = numeric["high"]
    low_price = numeric["low"]
    close_price = numeric["close"]
    volume = numeric["volume"]

    invalid_positive = (
        (open_price <= 0)
        | (high_price <= 0)
        | (low_price <= 0)
        | (close_price <= 0)
    )

    invalid_positive_count = int(
        invalid_positive.fillna(True).sum()
    )

    if invalid_positive_count:
        result.fail(
            "OHLCV non-positive price rows="
            f"{invalid_positive_count:,}"
        )
    else:
        result.passed_message(
            "OHLCV prices are positive."
        )

    negative_volume = int(
        (volume < 0).fillna(False).sum()
    )

    if negative_volume:
        result.fail(
            f"OHLCV negative volume rows="
            f"{negative_volume:,}"
        )
    else:
        result.passed_message(
            "OHLCV volume is non-negative."
        )

    high_invalid = (
        (high_price < open_price)
        | (high_price < close_price)
        | (high_price < low_price)
    )

    high_invalid_count = int(
        high_invalid.fillna(False).sum()
    )

    if high_invalid_count:
        result.fail(
            "OHLCV high relationship violations="
            f"{high_invalid_count:,}"
        )
    else:
        result.passed_message(
            "OHLCV high relationships are valid."
        )

    low_invalid = (
        (low_price > open_price)
        | (low_price > close_price)
        | (low_price > high_price)
    )

    low_invalid_count = int(
        low_invalid.fillna(False).sum()
    )

    if low_invalid_count:
        result.fail(
            "OHLCV low relationship violations="
            f"{low_invalid_count:,}"
        )
    else:
        result.passed_message(
            "OHLCV low relationships are valid."
        )


# ============================================================
# NUMERIC SIGNAL VALIDATION
# ============================================================

def validate_numeric_infinite_values(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> None:
    numeric_df = df.select_dtypes(
        include=[np.number]
    )

    if numeric_df.empty:
        result.passed_message(
            f"No numeric {label} columns require "
            "infinite-value inspection."
        )
        return

    values = numeric_df.to_numpy(
        dtype=float,
        copy=False,
    )

    infinite_count = int(
        np.isinf(values).sum()
    )

    if infinite_count:
        result.fail(
            f"{label} contains infinite numeric values="
            f"{infinite_count:,}"
        )
    else:
        result.passed_message(
            f"No infinite values found in numeric "
            f"{label} columns."
        )


# ============================================================
# MA VALIDATION
# ============================================================

def is_ma_column(column: str) -> bool:
    lower = column.lower()

    for prefix in MA_PREFIXES:
        if lower.startswith(prefix + "_"):
            return True

        if lower == prefix:
            return True

    return False


def validate_ma_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    ma_columns = [
        str(column)
        for column in df.columns
        if is_ma_column(str(column))
    ]

    if not ma_columns:
        result.warn(
            "No MA-prefixed columns found. "
            "MA validation skipped."
        )
        return

    print(
        "[INFO] MA columns found: "
        + ", ".join(ma_columns)
    )

    failures = 0

    for column in ma_columns:
        series = pd.to_numeric(
            df[column],
            errors="coerce",
        )

        finite_values = series.dropna()

        if finite_values.empty:
            continue

        array = finite_values.to_numpy(
            dtype=float
        )

        infinite = int(
            np.isinf(array).sum()
        )

        if infinite:
            result.fail(
                f"MA column '{column}' infinite values="
                f"{infinite:,}"
            )
            failures += 1

        non_positive = int(
            (finite_values <= 0).sum()
        )

        # Some MA-like derived columns can legitimately be
        # ratios / directions. Therefore only warn.
        if non_positive:
            result.warn(
                f"MA-like column '{column}' has "
                f"{non_positive:,} non-positive values."
            )

    if failures == 0:
        result.passed_message(
            "MA columns passed finite-value validation."
        )


# ============================================================
# SCORE VALIDATION
# ============================================================

def validate_score_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    found = [
        column
        for column in SCORE_COLUMNS
        if column in df.columns
    ]

    if not found:
        result.warn(
            "No expected score columns found."
        )
        return

    for column in found:
        series = pd.to_numeric(
            df[column],
            errors="coerce",
        )

        invalid = int(
            series.isna().sum()
        )

        if invalid:
            result.fail(
                f"Score '{column}' invalid/NaN values="
                f"{invalid:,}"
            )
            continue

        infinite = int(
            np.isinf(
                series.to_numpy(dtype=float)
            ).sum()
        )

        if infinite:
            result.fail(
                f"Score '{column}' infinite values="
                f"{infinite:,}"
            )
            continue

        unique_values = (
            series.value_counts(dropna=False)
            .sort_index()
        )

        values_text = [
            str(value)
            for value in unique_values.index.tolist()
        ]

        print(
            f"[INFO] Score '{column}': "
            f"min={series.min()}, "
            f"max={series.max()}, "
            f"values={values_text[:20]}"
        )

    result.passed_message(
        "Expected score columns inspected."
    )


# ============================================================
# OFFICIAL SIGNAL STATE VALIDATION
# ============================================================

def normalize_boolean_signal(
    series: pd.Series,
) -> tuple[pd.Series, list[str]]:
    """
    Return:
        boolean_series
        invalid_original_values

    Detector official state columns are expected to be
    binary-like values.
    """

    output = pd.Series(
        False,
        index=series.index,
        dtype=bool,
    )

    invalid_values: list[str] = []

    for index, value in series.items():
        if pd.isna(value):
            invalid_values.append("NaN")
            continue

        if isinstance(value, (bool, np.bool_)):
            output.at[index] = bool(value)
            continue

        if isinstance(
            value,
            (
                int,
                float,
                np.integer,
                np.floating,
            ),
        ):
            try:
                numeric_value = float(value)

                if math.isclose(
                    numeric_value,
                    1.0,
                    rel_tol=0.0,
                    abs_tol=1e-12,
                ):
                    output.at[index] = True
                    continue

                if math.isclose(
                    numeric_value,
                    0.0,
                    rel_tol=0.0,
                    abs_tol=1e-12,
                ):
                    output.at[index] = False
                    continue

                invalid_values.append(str(value))
                continue

            except Exception:
                invalid_values.append(str(value))
                continue

        text = str(value).strip().lower()

        if text in TRUE_VALUES:
            output.at[index] = True
            continue

        if text in FALSE_VALUES:
            output.at[index] = False
            continue

        invalid_values.append(str(value))

    return output, invalid_values


def validate_official_signal_states(
    df: pd.DataFrame,
    result: ValidationResult,
) -> dict[str, pd.Series]:
    missing = [
        column
        for column in OFFICIAL_STATE_COLUMNS
        if column not in df.columns
    ]

    if missing:
        result.fail(
            "Missing official detector state columns: "
            + ", ".join(missing)
        )
        return {}

    normalized: dict[str, pd.Series] = {}

    for column in OFFICIAL_STATE_COLUMNS:
        bool_series, invalid_values = (
            normalize_boolean_signal(
                df[column]
            )
        )

        normalized[column] = bool_series

        if invalid_values:
            unique_invalid = list(
                dict.fromkeys(invalid_values)
            )

            result.fail(
                f"Condition '{column}' has invalid "
                f"binary values: "
                f"{unique_invalid[:20]}"
            )
            continue

        true_count = int(
            bool_series.sum()
        )

        false_count = int(
            len(bool_series) - true_count
        )

        raw_values = (
            df[column]
            .astype(str)
            .drop_duplicates()
            .tolist()
        )

        print(
            f"[INFO] Condition '{column}': "
            f"true-like={true_count:,}, "
            f"false-like={false_count:,}, "
            f"values={raw_values[:20]}"
        )

    if len(normalized) == 3:
        result.setup_count = int(
            normalized["signal_setup"].sum()
        )

        result.ready_count = int(
            normalized["signal_ready"].sum()
        )

        result.trigger_count = int(
            normalized["signal_trigger"].sum()
        )

        result.passed_message(
            "Official SETUP / READY / TRIGGER "
            "columns validated."
        )

    return normalized


# ============================================================
# SIGNAL STAGE SUPPLEMENTARY INSPECTION
# ============================================================

def inspect_signal_stage(
    df: pd.DataFrame,
    official_states: dict[str, pd.Series],
    result: ValidationResult,
) -> None:
    """
    signal_stage is NOT used to calculate official counts.

    Official counts come only from:
        signal_setup
        signal_ready
        signal_trigger

    signal_stage is inspected for diagnostic purposes only.
    """

    if "signal_stage" not in df.columns:
        result.warn(
            "signal_stage column not present. "
            "Supplementary stage inspection skipped."
        )
        return

    stage = (
        df["signal_stage"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    counts = stage.value_counts(
        dropna=False
    )

    print("[INFO] signal_stage distribution:")

    for value, count in counts.head(30).items():
        display_value = (
            value if value else "<EMPTY>"
        )

        print(
            f"       {display_value}: {count:,}"
        )

    # Do NOT fail simply because stage labels do not equal
    # independent official-state counts.
    #
    # The detector can represent hierarchy / priority in
    # signal_stage while signal_setup, signal_ready and
    # signal_trigger remain independent binary research states.

    if official_states:
        result.passed_message(
            "signal_stage inspected separately from "
            "official state counts."
        )


# ============================================================
# FUTURE LEAKAGE INSPECTION
# ============================================================

def find_suspicious_future_columns(
    columns: Iterable[Any],
) -> list[str]:
    suspicious: list[str] = []

    for raw_column in columns:
        column = str(raw_column).strip()
        lower = column.lower()

        if column in ALLOWED_NEXT_COLUMNS:
            continue

        for pattern in FORBIDDEN_FUTURE_PATTERNS:
            if pattern in lower:
                suspicious.append(column)
                break

    return suspicious


def validate_future_leakage(
    feature: pd.DataFrame,
    signal: pd.DataFrame,
    result: ValidationResult,
) -> None:
    feature_suspicious = (
        find_suspicious_future_columns(
            feature.columns
        )
    )

    signal_suspicious = (
        find_suspicious_future_columns(
            signal.columns
        )
    )

    if feature_suspicious:
        result.fail(
            "Suspicious future/target Feature columns: "
            + ", ".join(feature_suspicious)
        )
    else:
        result.passed_message(
            "No suspicious future/target Feature "
            "columns detected."
        )

    if signal_suspicious:
        result.fail(
            "Suspicious future/target Signal columns: "
            + ", ".join(signal_suspicious)
        )
    else:
        result.passed_message(
            "No suspicious future/target Signal "
            "columns detected."
        )


# ============================================================
# SIGNAL -> OHLCV TIMESTAMP MEMBERSHIP
# ============================================================

def validate_signal_timestamp_membership(
    ohlcv_ts: pd.Series | None,
    signal_ts: pd.Series | None,
    result: ValidationResult,
) -> None:
    if (
        ohlcv_ts is None
        or signal_ts is None
    ):
        return

    valid_ohlcv = ohlcv_ts.dropna()
    valid_signal = signal_ts.dropna()

    ohlcv_set = set(
        valid_ohlcv.astype("int64").tolist()
    )

    signal_values = (
        valid_signal.astype("int64").tolist()
    )

    missing_count = sum(
        1
        for value in signal_values
        if value not in ohlcv_set
    )

    if missing_count:
        result.fail(
            "Signal timestamps missing from OHLCV="
            f"{missing_count:,}"
        )
    else:
        result.passed_message(
            "Every valid Signal timestamp exists in OHLCV."
        )


# ============================================================
# SOURCE HASH VALIDATION
# ============================================================

def validate_hash_unchanged(
    path: Path,
    before_hash: str | None,
    label: str,
    result: ValidationResult,
) -> None:
    if before_hash is None:
        result.fail(
            f"{label} SHA256 before-validation hash "
            "was unavailable."
        )
        return

    if not path.exists():
        result.fail(
            f"{label} disappeared during validation."
        )
        return

    try:
        after_hash = file_sha256(path)
    except Exception as exc:
        result.fail(
            f"{label} SHA256 after-validation failed: "
            f"{type(exc).__name__}: {exc}"
        )
        return

    if after_hash == before_hash:
        result.passed_message(
            f"{label} SHA256 unchanged."
        )
    else:
        result.fail(
            f"{label} SHA256 changed during validation."
        )


# ============================================================
# PROJECT STRUCTURE
# ============================================================

def validate_project_structure() -> bool:
    print()
    separator("=")
    print("PROJECT STRUCTURE CHECK")
    separator("=")

    required_dirs = [
        DATA_DIR,
        OHLCV_DIR,
        FEATURE_DIR,
        SIGNAL_DIR,
    ]

    for timeframe in TIMEFRAMES:
        required_dirs.extend(
            [
                OHLCV_DIR / timeframe,
                FEATURE_DIR / timeframe,
                SIGNAL_DIR / timeframe,
            ]
        )

    passed = True

    for directory in required_dirs:
        if directory.exists() and directory.is_dir():
            print(f"[PASS] {directory}")
        else:
            print(f"[FAIL] Missing directory: {directory}")
            passed = False

    return passed


# ============================================================
# SINGLE JOB VALIDATION
# ============================================================

def validate_one(
    market: str,
    timeframe: str,
) -> ValidationResult:
    started = time.perf_counter()

    ohlcv_path = (
        OHLCV_DIR
        / timeframe
        / f"{market}.csv"
    )

    feature_path = (
        FEATURE_DIR
        / timeframe
        / f"{market}.csv"
    )

    signal_path = (
        SIGNAL_DIR
        / timeframe
        / f"{market}.csv"
    )

    result = ValidationResult(
        market=market,
        timeframe=timeframe,
        ohlcv_path=ohlcv_path,
        feature_path=feature_path,
        signal_path=signal_path,
    )

    separator("-")
    print(f"[{timeframe.upper()}] {market}")
    print(f"OHLCV  : {ohlcv_path}")
    print(f"Feature: {feature_path}")
    print(f"Signal : {signal_path}")
    print()

    # --------------------------------------------------------
    # SHA256 BEFORE
    # --------------------------------------------------------

    hashes_before: dict[str, str | None] = {
        "OHLCV": None,
        "Feature": None,
        "Signal": None,
    }

    for label, path in (
        ("OHLCV", ohlcv_path),
        ("Feature", feature_path),
        ("Signal", signal_path),
    ):
        if path.exists() and path.is_file():
            try:
                hashes_before[label] = (
                    file_sha256(path)
                )
            except Exception as exc:
                result.fail(
                    f"{label} SHA256 before-validation "
                    f"failed: {type(exc).__name__}: {exc}"
                )

    # --------------------------------------------------------
    # READ FILES
    # --------------------------------------------------------

    ohlcv = safe_read_csv(
        ohlcv_path,
        "OHLCV",
        result,
    )

    feature = safe_read_csv(
        feature_path,
        "Feature",
        result,
    )

    signal = safe_read_csv(
        signal_path,
        "Signal",
        result,
    )

    if (
        ohlcv is None
        or feature is None
        or signal is None
    ):
        result.elapsed_seconds = (
            time.perf_counter() - started
        )

        for label, path in (
            ("OHLCV", ohlcv_path),
            ("Feature", feature_path),
            ("Signal", signal_path),
        ):
            if path.exists():
                validate_hash_unchanged(
                    path,
                    hashes_before[label],
                    label,
                    result,
                )

        return result

    # --------------------------------------------------------
    # COLUMN NAME CHECK
    # --------------------------------------------------------

    validate_unique_columns(
        ohlcv,
        "OHLCV",
        result,
    )

    validate_unique_columns(
        feature,
        "Feature",
        result,
    )

    validate_unique_columns(
        signal,
        "Signal",
        result,
    )

    validate_required_ohlc_columns(
        ohlcv,
        result,
    )

    # --------------------------------------------------------
    # TIMESTAMP CHECK
    # --------------------------------------------------------

    _, ohlcv_ts = validate_timestamp_integrity(
        ohlcv,
        "OHLCV",
        result,
    )

    _, feature_ts = validate_timestamp_integrity(
        feature,
        "Feature",
        result,
    )

    _, signal_ts = validate_timestamp_integrity(
        signal,
        "Signal",
        result,
    )

    # --------------------------------------------------------
    # ROW / TIMESTAMP 1:1
    # --------------------------------------------------------

    validate_row_counts(
        ohlcv,
        feature,
        signal,
        result,
    )

    validate_timestamp_alignment(
        ohlcv_ts,
        feature_ts,
        signal_ts,
        result,
    )

    # --------------------------------------------------------
    # OHLCV SANITY
    # --------------------------------------------------------

    validate_ohlcv_values(
        ohlcv,
        result,
    )

    # --------------------------------------------------------
    # FEATURE / SIGNAL NUMERIC CHECK
    # --------------------------------------------------------

    validate_numeric_infinite_values(
        feature,
        "Feature",
        result,
    )

    validate_numeric_infinite_values(
        signal,
        "Signal",
        result,
    )

    # --------------------------------------------------------
    # MA CHECK
    # --------------------------------------------------------

    validate_ma_columns(
        signal,
        result,
    )

    # --------------------------------------------------------
    # SCORE CHECK
    # --------------------------------------------------------

    validate_score_columns(
        signal,
        result,
    )

    # --------------------------------------------------------
    # OFFICIAL RESEARCH STATES
    # --------------------------------------------------------

    official_states = (
        validate_official_signal_states(
            signal,
            result,
        )
    )

    # --------------------------------------------------------
    # SIGNAL STAGE
    # --------------------------------------------------------

    inspect_signal_stage(
        signal,
        official_states,
        result,
    )

    # --------------------------------------------------------
    # FUTURE LEAKAGE
    # --------------------------------------------------------

    validate_future_leakage(
        feature,
        signal,
        result,
    )

    # --------------------------------------------------------
    # SIGNAL TIMESTAMP MEMBERSHIP
    # --------------------------------------------------------

    validate_signal_timestamp_membership(
        ohlcv_ts,
        signal_ts,
        result,
    )

    # --------------------------------------------------------
    # SOURCE HASH AFTER
    # --------------------------------------------------------

    validate_hash_unchanged(
        ohlcv_path,
        hashes_before["OHLCV"],
        "OHLCV",
        result,
    )

    validate_hash_unchanged(
        feature_path,
        hashes_before["Feature"],
        "Feature",
        result,
    )

    validate_hash_unchanged(
        signal_path,
        hashes_before["Signal"],
        "Signal",
        result,
    )

    # --------------------------------------------------------
    # JOB SUMMARY
    # --------------------------------------------------------

    result.elapsed_seconds = (
        time.perf_counter() - started
    )

    print()
    print(
        f"Rows    : "
        f"OHLCV={result.ohlcv_rows:,} | "
        f"Feature={result.feature_rows:,} | "
        f"Signal={result.signal_rows:,}"
    )

    print(
        f"SETUP   : {result.setup_count:,}"
    )

    print(
        f"READY   : {result.ready_count:,}"
    )

    print(
        f"TRIGGER : {result.trigger_count:,}"
    )

    print(
        f"Elapsed : "
        f"{result.elapsed_seconds:.2f}s"
    )

    if result.passed:
        print("[RESULT] PASS")
    else:
        print("[RESULT] FAIL")

    return result


# ============================================================
# SUMMARY
# ============================================================

def print_summary(
    results: list[ValidationResult],
    total_elapsed: float,
) -> bool:
    separator("=")
    print("256 VALIDATOR SUMMARY")
    separator("=")

    passed_jobs = sum(
        1
        for result in results
        if result.passed
    )

    failed_jobs = (
        len(results) - passed_jobs
    )

    total_ohlcv_rows = sum(
        result.ohlcv_rows
        for result in results
    )

    total_feature_rows = sum(
        result.feature_rows
        for result in results
    )

    total_signal_rows = sum(
        result.signal_rows
        for result in results
    )

    total_setup = sum(
        result.setup_count
        for result in results
    )

    total_ready = sum(
        result.ready_count
        for result in results
    )

    total_trigger = sum(
        result.trigger_count
        for result in results
    )

    print(f"Project       : {PROJECT_NAME}")
    print(f"Validator     : {VALIDATOR_NAME}")
    print(f"Base dir      : {BASE_DIR}")
    print(f"Markets       : {len(MARKETS):,}")
    print(f"Timeframes    : {len(TIMEFRAMES):,}")
    print(f"Total jobs    : {len(results):,}")
    print(f"Passed jobs   : {passed_jobs:,}")
    print(f"Failed jobs   : {failed_jobs:,}")
    print(
        f"OHLCV rows    : "
        f"{total_ohlcv_rows:,}"
    )
    print(
        f"Feature rows  : "
        f"{total_feature_rows:,}"
    )
    print(
        f"Signal rows   : "
        f"{total_signal_rows:,}"
    )

    print()
    print("256 Research States:")
    print(
        f"  SETUP       : "
        f"{total_setup:,}"
    )
    print(
        f"  READY       : "
        f"{total_ready:,}"
    )
    print(
        f"  TRIGGER     : "
        f"{total_trigger:,}"
    )

    print()
    print("Validation:")
    print(
        "  File existence       : CHECKED"
    )
    print(
        "  CSV readability      : CHECKED"
    )
    print(
        "  Timestamp integrity  : CHECKED"
    )
    print(
        "  Unix ms timestamp    : SUPPORTED"
    )
    print(
        "  Feature/Signal 1:1   : CHECKED"
    )
    print(
        "  OHLC sanity          : CHECKED"
    )
    print(
        "  MA values            : CHECKED IF PRESENT"
    )
    print(
        "  Scores               : CHECKED IF PRESENT"
    )
    print(
        "  Research states      : OFFICIAL BINARY COLUMNS"
    )
    print(
        "  signal_stage         : SUPPLEMENTARY ONLY"
    )
    print(
        "  Future leakage       : CHECKED"
    )
    print(
        "  Source SHA256        : CHECKED"
    )

    print()
    print("Safety:")
    print(
        "  Source modification  : DISABLED"
    )
    print(
        "  Future label         : NOT CREATED"
    )
    print(
        "  Prediction           : DISABLED"
    )
    print(
        "  Trading              : DISABLED"
    )

    print()
    print(
        f"Elapsed total : "
        f"{total_elapsed:.2f}s"
    )

    print()

    for result in results:
        status = (
            "PASSED"
            if result.passed
            else "FAILED"
        )

        print(
            f"[{status}] "
            f"{result.market} "
            f"{result.timeframe} "
            f"signal_rows={result.signal_rows:,} "
            f"setup={result.setup_count:,} "
            f"ready={result.ready_count:,} "
            f"trigger={result.trigger_count:,}"
        )

        if not result.passed:
            for error in result.errors:
                print(
                    f"         ERROR: {error}"
                )

    separator("=")

    all_passed = (
        len(results) > 0
        and failed_jobs == 0
    )

    if all_passed:
        print(
            "[RESULT] 256 VALIDATOR PASSED"
        )
        print(
            "[PASS] Detector output structure "
            "and integrity validated."
        )
        print(
            "[PASS] Unix millisecond timestamps "
            "were interpreted correctly."
        )
        print(
            "[PASS] Official SETUP / READY / TRIGGER "
            "states validated."
        )
        print(
            "[PASS] OHLCV / Feature / Signal files "
            "remained unchanged."
        )
        print(
            "[NEXT] Validator foundation is ready "
            "for the next research step."
        )
    else:
        print(
            "[RESULT] 256 VALIDATOR FAILED"
        )
        print(
            "[STOP] Do NOT proceed to "
            "future-result labels yet."
        )
        print(
            "[NEXT] Fix the failed validation "
            "item(s) and run this validator again."
        )

    return all_passed


# ============================================================
# MAIN
# ============================================================

def main() -> int:
    total_started = time.perf_counter()

    print()
    separator("=")
    print(
        f"{PROJECT_NAME} - "
        f"{VALIDATOR_NAME}"
    )
    print(
        "STEP 4 - 256 DETECTOR OUTPUT VALIDATION"
    )
    separator("=")

    print(f"Started UTC : {utc_now_text()}")
    print(f"Base dir    : {BASE_DIR}")

    print()
    print("Mode:")
    print("  READ ONLY validation")
    print("  KRW-BTC validation mode")
    print("  h1 / h4 / d1")
    print("  Feature / Signal 1:1 verification")
    print("  Unix timestamp unit auto-detection")
    print("  Unix milliseconds supported")
    print("  SETUP / READY / TRIGGER inspection")
    print("  Official signal_* state counting")
    print("  signal_stage supplementary inspection")
    print("  MA / score / condition inspection")
    print("  Future-information leakage check")
    print("  Source SHA256 integrity check")
    print("  No future labels")
    print("  No prediction")
    print("  No trading")

    structure_ok = validate_project_structure()

    if not structure_ok:
        print()
        separator("=")
        print("[RESULT] PROJECT STRUCTURE FAILED")
        print(
            "[STOP] Required data directories "
            "are missing."
        )
        return 1

    results: list[ValidationResult] = []

    for market in MARKETS:
        for timeframe in TIMEFRAMES:
            try:
                result = validate_one(
                    market=market,
                    timeframe=timeframe,
                )

            except KeyboardInterrupt:
                print()
                print(
                    "[STOP] Validation interrupted "
                    "by user."
                )
                return 130

            except Exception as exc:
                ohlcv_path = (
                    OHLCV_DIR
                    / timeframe
                    / f"{market}.csv"
                )

                feature_path = (
                    FEATURE_DIR
                    / timeframe
                    / f"{market}.csv"
                )

                signal_path = (
                    SIGNAL_DIR
                    / timeframe
                    / f"{market}.csv"
                )

                result = ValidationResult(
                    market=market,
                    timeframe=timeframe,
                    ohlcv_path=ohlcv_path,
                    feature_path=feature_path,
                    signal_path=signal_path,
                    passed=False,
                )

                message = (
                    "Unexpected validator exception: "
                    f"{type(exc).__name__}: {exc}"
                )

                result.errors.append(message)

                print(
                    f"[FAIL] {message}"
                )

            results.append(result)

    total_elapsed = (
        time.perf_counter()
        - total_started
    )

    all_passed = print_summary(
        results,
        total_elapsed,
    )

    if all_passed:
        return 0

    return 1


if __name__ == "__main__":
    try:
        exit_code = main()

    except KeyboardInterrupt:
        print()
        print("[STOP] Interrupted by user.")
        exit_code = 130

    except Exception as exc:
        print()
        separator("=")
        print("[FATAL] validate_256.py crashed.")
        print(
            f"{type(exc).__name__}: {exc}"
        )
        separator("=")
        exit_code = 1

    sys.exit(exit_code)
