# ============================================================
# Upbit Surge Monitor
# validate_256.py
# Clean V001
# ============================================================
#
# PURPOSE
# ------------------------------------------------------------
# Validate outputs generated by:
#
#   detect_256.py - 256 Detector Clean V001
#
# This validator is READ ONLY.
#
# It must NOT:
#
#   - modify OHLCV files
#   - modify Feature files
#   - modify Signal files
#   - create labels
#   - use future price data for signal generation
#   - perform prediction
#   - perform trading
#
#
# CURRENT VALIDATION TARGET
# ------------------------------------------------------------
#
# Market:
#   KRW-BTC
#
# Timeframes:
#   h1
#   h4
#   d1
#
#
# EXPECTED PROJECT STRUCTURE
# ------------------------------------------------------------
#
# upbit-surge-monitor/
#
#   validate_256.py
#
#   data/
#     ohlcv/
#       h1/KRW-BTC.csv
#       h4/KRW-BTC.csv
#       d1/KRW-BTC.csv
#
#     features/
#       h1/KRW-BTC.csv
#       h4/KRW-BTC.csv
#       d1/KRW-BTC.csv
#
#     signals/
#       256/
#         h1/KRW-BTC.csv
#         h4/KRW-BTC.csv
#         d1/KRW-BTC.csv
#
#
# VALIDATION PRINCIPLES
# ------------------------------------------------------------
#
# 1. Source files are READ ONLY.
# 2. Signal row count must match Feature row count.
# 3. Signal timestamps must match Feature timestamps.
# 4. Duplicate timestamps are not allowed.
# 5. Timestamp ordering must be chronological.
# 6. OHLCV / Feature / Signal price values are sanity checked.
# 7. SETUP / READY / TRIGGER states are inspected.
# 8. Score columns are inspected when present.
# 9. MA columns are inspected when present.
# 10. Boolean research-condition columns are inspected.
# 11. Suspicious future-information columns are rejected.
# 12. No future-result label is generated here.
#
#
# IMPORTANT
# ------------------------------------------------------------
#
# Clean V001 intentionally discovers optional detector columns
# from the actual Signal CSV instead of inventing column names.
#
# Required structural validation is strict.
#
# Research-column validation is adaptive:
#
#   - if a known MA exists -> validate it
#   - if a score exists -> validate it
#   - if condition/state columns exist -> inspect them
#
# This avoids changing the detector merely to satisfy a validator.
#
# ============================================================


from __future__ import annotations

import hashlib
import math
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


# ============================================================
# 1. PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VALIDATOR_VERSION = "256 Validator Clean V001"

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"

OHLCV_ROOT = DATA_DIR / "ohlcv"
FEATURE_ROOT = DATA_DIR / "features"
SIGNAL_ROOT = DATA_DIR / "signals" / "256"

MARKETS = [
    "KRW-BTC",
]

TIMEFRAMES = [
    "h1",
    "h4",
    "d1",
]


# ============================================================
# 2. VALIDATION CONFIGURATION
# ============================================================

# Timestamp names that may exist in project CSV files.
TIMESTAMP_CANDIDATES = [
    "timestamp",
    "candle_date_time_utc",
    "datetime",
    "date",
    "time",
]

# Core OHLCV price fields.
PRICE_COLUMNS = [
    "open",
    "high",
    "low",
    "close",
]

# Common volume / trade-value fields.
VOLUME_COLUMNS = [
    "volume",
    "candle_acc_trade_volume",
]

TRADE_VALUE_COLUMNS = [
    "value",
    "trade_value",
    "candle_acc_trade_price",
]

# 256 research moving averages.
#
# MA5 / MA20 / MA60:
#   Original short-term 256 research structure.
#
# MA112 / MA224:
#   Longer-term variant discussed during 256 research.
#
MA_PERIODS = [
    5,
    20,
    60,
    112,
    224,
]

# Candidate names are discovered case-insensitively.
MA_NAME_PATTERNS = {
    5: [
        "ma5",
        "ma_5",
        "sma5",
        "sma_5",
        "close_ma5",
        "close_ma_5",
    ],
    20: [
        "ma20",
        "ma_20",
        "sma20",
        "sma_20",
        "close_ma20",
        "close_ma_20",
    ],
    60: [
        "ma60",
        "ma_60",
        "sma60",
        "sma_60",
        "close_ma60",
        "close_ma_60",
    ],
    112: [
        "ma112",
        "ma_112",
        "sma112",
        "sma_112",
        "close_ma112",
        "close_ma_112",
    ],
    224: [
        "ma224",
        "ma_224",
        "sma224",
        "sma_224",
        "close_ma224",
        "close_ma_224",
    ],
}

# State keywords.
STATE_KEYWORDS = {
    "SETUP": [
        "setup",
    ],
    "READY": [
        "ready",
    ],
    "TRIGGER": [
        "trigger",
    ],
}

# Future information is forbidden in detector output.
#
# These are intentionally conservative keywords.
#
# A detector Signal CSV should describe information available
# at the current candle only.
#
FORBIDDEN_FUTURE_KEYWORDS = [
    "future",
    "forward",
    "lookahead",
    "look_ahead",
    "next_return",
    "next_pct",
    "future_return",
    "future_pct",
    "future_high",
    "future_low",
    "future_close",
    "max_future",
    "min_future",
    "target_return",
    "target_pct",
    "reached_30",
    "hit_30",
    "hit30",
    "label_30",
    "label30",
    "future_label",
]

# Exact names that are especially suspicious.
FORBIDDEN_EXACT_COLUMNS = {
    "label",
    "target",
    "future_label",
    "future_return",
    "future_max_return",
    "future_min_return",
    "hit_30",
    "reached_30",
    "label_30",
}

# Words used to discover score columns.
SCORE_KEYWORDS = [
    "score",
]

# Words commonly used for boolean / detector conditions.
BOOLEAN_HINTS = [
    "is_",
    "has_",
    "flag",
    "cross",
    "above",
    "below",
    "rising",
    "falling",
    "turn",
    "compression",
    "compressed",
    "momentum",
    "expansion",
    "strong",
    "setup",
    "ready",
    "trigger",
]

# Floating point comparison tolerance.
FLOAT_RTOL = 1e-9
FLOAT_ATOL = 1e-12

# Maximum number of example problem rows printed.
MAX_EXAMPLES = 10


# ============================================================
# 3. RESULT DATA CLASSES
# ============================================================

@dataclass
class ValidationMessage:
    level: str
    message: str


@dataclass
class JobResult:
    market: str
    timeframe: str

    passed: bool = True

    feature_rows: int = 0
    signal_rows: int = 0
    ohlcv_rows: int = 0

    setup_count: int | None = None
    ready_count: int | None = None
    trigger_count: int | None = None

    messages: list[ValidationMessage] = field(default_factory=list)

    elapsed_seconds: float = 0.0

    def pass_message(self, message: str) -> None:
        self.messages.append(
            ValidationMessage(
                level="PASS",
                message=message,
            )
        )

    def info_message(self, message: str) -> None:
        self.messages.append(
            ValidationMessage(
                level="INFO",
                message=message,
            )
        )

    def warn_message(self, message: str) -> None:
        self.messages.append(
            ValidationMessage(
                level="WARN",
                message=message,
            )
        )

    def fail_message(self, message: str) -> None:
        self.passed = False
        self.messages.append(
            ValidationMessage(
                level="FAIL",
                message=message,
            )
        )


# ============================================================
# 4. GENERAL HELPERS
# ============================================================

def utc_now_text() -> str:
    return datetime.now(timezone.utc).isoformat()


def separator(char: str = "-", width: int = 72) -> str:
    return char * width


def normalize_column_name(name: Any) -> str:
    return str(name).strip().lower()


def normalized_column_map(df: pd.DataFrame) -> dict[str, str]:
    result: dict[str, str] = {}

    for column in df.columns:
        normalized = normalize_column_name(column)

        if normalized not in result:
            result[normalized] = str(column)

    return result


def safe_file_size(path: Path) -> int:
    try:
        return path.stat().st_size
    except OSError:
        return -1


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file_handle:
        while True:
            block = file_handle.read(1024 * 1024)

            if not block:
                break

            digest.update(block)

    return digest.hexdigest()


def read_csv_read_only(path: Path) -> pd.DataFrame:
    return pd.read_csv(
        path,
        low_memory=False,
    )


def find_timestamp_column(df: pd.DataFrame) -> str | None:
    column_map = normalized_column_map(df)

    for candidate in TIMESTAMP_CANDIDATES:
        normalized_candidate = normalize_column_name(candidate)

        if normalized_candidate in column_map:
            return column_map[normalized_candidate]

    # Fallback:
    # Detect columns containing both candle/date/time concepts.
    for column in df.columns:
        normalized = normalize_column_name(column)

        if "timestamp" in normalized:
            return str(column)

        if "datetime" in normalized:
            return str(column)

        if (
            "candle" in normalized
            and "time" in normalized
        ):
            return str(column)

    return None


def parse_timestamp_series(
    series: pd.Series,
) -> pd.Series:
    """
    Convert timestamps for validation only.

    utc=True gives us a common comparison basis and does not
    modify source files.
    """

    return pd.to_datetime(
        series,
        errors="coerce",
        utc=True,
    )


def numeric_series(
    series: pd.Series,
) -> pd.Series:
    return pd.to_numeric(
        series,
        errors="coerce",
    )


def finite_mask(series: pd.Series) -> pd.Series:
    numeric = numeric_series(series)

    values = numeric.to_numpy(dtype=float, na_value=np.nan)

    return pd.Series(
        np.isfinite(values),
        index=series.index,
    )


def true_mask_from_series(
    series: pd.Series,
) -> pd.Series:
    """
    Convert common state/boolean representations into True/False.

    Accepted true-like values:
      True
      1
      1.0
      yes
      y
      true
      t
      setup
      ready
      trigger
    """

    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)

    numeric = pd.to_numeric(
        series,
        errors="coerce",
    )

    numeric_available = numeric.notna()

    result = pd.Series(
        False,
        index=series.index,
        dtype=bool,
    )

    if numeric_available.any():
        result.loc[numeric_available] = (
            numeric.loc[numeric_available] > 0
        )

    text_mask = ~numeric_available

    if text_mask.any():
        text = (
            series.loc[text_mask]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        true_values = {
            "true",
            "t",
            "yes",
            "y",
            "on",
            "setup",
            "ready",
            "trigger",
            "1",
            "1.0",
        }

        result.loc[text_mask] = text.isin(true_values)

    return result


def format_percentage(
    numerator: int,
    denominator: int,
) -> str:
    if denominator <= 0:
        return "N/A"

    value = numerator / denominator * 100.0

    return f"{value:.4f}%"


def print_problem_examples(
    df: pd.DataFrame,
    mask: pd.Series,
    columns: Iterable[str],
    title: str,
) -> None:
    if not mask.any():
        return

    selected_columns = [
        column
        for column in columns
        if column in df.columns
    ]

    if not selected_columns:
        return

    examples = (
        df.loc[mask, selected_columns]
        .head(MAX_EXAMPLES)
    )

    print()
    print(f"  {title}")
    print(
        examples.to_string(
            index=False,
        )
    )


# ============================================================
# 5. COLUMN DISCOVERY
# ============================================================

def find_column_by_candidates(
    df: pd.DataFrame,
    candidates: Iterable[str],
) -> str | None:
    column_map = normalized_column_map(df)

    for candidate in candidates:
        normalized = normalize_column_name(candidate)

        if normalized in column_map:
            return column_map[normalized]

    return None


def discover_ma_columns(
    df: pd.DataFrame,
) -> dict[int, str]:
    result: dict[int, str] = {}

    for period in MA_PERIODS:
        candidates = MA_NAME_PATTERNS.get(
            period,
            [],
        )

        column = find_column_by_candidates(
            df,
            candidates,
        )

        if column is not None:
            result[period] = column
            continue

        # Flexible fallback.
        #
        # Examples:
        #   ma_close_5
        #   feature_ma_20
        #   price_sma_60
        #
        for existing_column in df.columns:
            normalized = normalize_column_name(
                existing_column
            )

            period_text = str(period)

            has_ma_word = (
                "ma" in normalized
                or "sma" in normalized
                or "moving_average" in normalized
            )

            has_period = (
                normalized.endswith(
                    f"_{period_text}"
                )
                or normalized.endswith(
                    period_text
                )
                or f"_{period_text}_" in normalized
            )

            if has_ma_word and has_period:
                result[period] = str(existing_column)
                break

    return result


def discover_score_columns(
    df: pd.DataFrame,
) -> list[str]:
    result: list[str] = []

    for column in df.columns:
        normalized = normalize_column_name(column)

        if any(
            keyword in normalized
            for keyword in SCORE_KEYWORDS
        ):
            result.append(str(column))

    return result


def discover_boolean_like_columns(
    df: pd.DataFrame,
) -> list[str]:
    result: list[str] = []

    for column in df.columns:
        normalized = normalize_column_name(column)

        hinted = any(
            hint in normalized
            for hint in BOOLEAN_HINTS
        )

        if not hinted:
            continue

        series = df[column]

        # Actual boolean.
        if pd.api.types.is_bool_dtype(series):
            result.append(str(column))
            continue

        non_null = series.dropna()

        if non_null.empty:
            continue

        # Small number of unique values often means a state flag.
        unique_values = non_null.astype(str).str.lower().unique()

        if len(unique_values) <= 10:
            result.append(str(column))

    return sorted(
        set(result)
    )


def discover_state_column(
    df: pd.DataFrame,
    state_name: str,
) -> str | None:
    state_name_lower = state_name.lower()

    # First preference:
    # exact or conventional flag names.
    candidates = [
        state_name_lower,
        f"is_{state_name_lower}",
        f"{state_name_lower}_flag",
        f"{state_name_lower}_signal",
        f"signal_{state_name_lower}",
        f"{state_name_lower}_state",
    ]

    found = find_column_by_candidates(
        df,
        candidates,
    )

    if found is not None:
        return found

    # Second preference:
    # any column containing the state word, but avoid score
    # because score > 0 is not necessarily state=True.
    for column in df.columns:
        normalized = normalize_column_name(column)

        if state_name_lower not in normalized:
            continue

        if "score" in normalized:
            continue

        if (
            "threshold" in normalized
            or "count" in normalized
        ):
            continue

        return str(column)

    return None


def discover_combined_state_column(
    df: pd.DataFrame,
) -> str | None:
    candidates = [
        "state",
        "signal_state",
        "research_state",
        "detector_state",
        "stage",
        "signal_stage",
    ]

    return find_column_by_candidates(
        df,
        candidates,
    )


# ============================================================
# 6. PATH VALIDATION
# ============================================================

def validate_required_paths(
    result: JobResult,
    ohlcv_path: Path,
    feature_path: Path,
    signal_path: Path,
) -> bool:
    required_paths = [
        ("OHLCV", ohlcv_path),
        ("Feature", feature_path),
        ("Signal", signal_path),
    ]

    all_exist = True

    for label, path in required_paths:
        if not path.exists():
            result.fail_message(
                f"Missing {label} file: {path}"
            )
            all_exist = False
            continue

        if not path.is_file():
            result.fail_message(
                f"{label} path is not a file: {path}"
            )
            all_exist = False
            continue

        size = safe_file_size(path)

        if size <= 0:
            result.fail_message(
                f"{label} file is empty: {path}"
            )
            all_exist = False
            continue

        result.pass_message(
            f"{label} file exists "
            f"({size:,} bytes)"
        )

    return all_exist


# ============================================================
# 7. BASIC DATAFRAME VALIDATION
# ============================================================

def validate_non_empty_dataframe(
    result: JobResult,
    label: str,
    df: pd.DataFrame,
) -> None:
    if df.empty:
        result.fail_message(
            f"{label} dataframe is empty."
        )
        return

    result.pass_message(
        f"{label} dataframe rows={len(df):,}, "
        f"columns={len(df.columns):,}"
    )


def validate_unique_column_names(
    result: JobResult,
    label: str,
    df: pd.DataFrame,
) -> None:
    duplicated = (
        pd.Index(df.columns)
        .duplicated()
    )

    if duplicated.any():
        duplicate_names = list(
            pd.Index(df.columns)[duplicated]
        )

        result.fail_message(
            f"{label} contains duplicate column names: "
            f"{duplicate_names}"
        )
        return

    result.pass_message(
        f"{label} column names are unique."
    )


def validate_timestamp_integrity(
    result: JobResult,
    label: str,
    df: pd.DataFrame,
) -> tuple[str | None, pd.Series | None]:
    timestamp_column = find_timestamp_column(df)

    if timestamp_column is None:
        result.fail_message(
            f"{label} timestamp column not found."
        )
        return None, None

    parsed = parse_timestamp_series(
        df[timestamp_column]
    )

    invalid_count = int(
        parsed.isna().sum()
    )

    if invalid_count > 0:
        result.fail_message(
            f"{label} timestamp parse failures="
            f"{invalid_count:,}"
        )
    else:
        result.pass_message(
            f"{label} timestamp parsing passed "
            f"using '{timestamp_column}'."
        )

    duplicate_count = int(
        parsed.duplicated().sum()
    )

    if duplicate_count > 0:
        result.fail_message(
            f"{label} duplicate timestamps="
            f"{duplicate_count:,}"
        )
    else:
        result.pass_message(
            f"{label} timestamps are unique."
        )

    valid_parsed = parsed.dropna()

    if not valid_parsed.empty:
        if valid_parsed.is_monotonic_increasing:
            result.pass_message(
                f"{label} timestamps are chronological."
            )
        else:
            result.fail_message(
                f"{label} timestamps are NOT "
                f"chronological."
            )

        result.info_message(
            f"{label} timestamp range: "
            f"{valid_parsed.iloc[0]} -> "
            f"{valid_parsed.iloc[-1]}"
        )

    return timestamp_column, parsed


# ============================================================
# 8. ROW / TIMESTAMP ALIGNMENT
# ============================================================

def validate_feature_signal_alignment(
    result: JobResult,
    feature_df: pd.DataFrame,
    signal_df: pd.DataFrame,
    feature_timestamp_column: str | None,
    signal_timestamp_column: str | None,
    feature_timestamps: pd.Series | None,
    signal_timestamps: pd.Series | None,
) -> None:
    feature_rows = len(feature_df)
    signal_rows = len(signal_df)

    result.feature_rows = feature_rows
    result.signal_rows = signal_rows

    if feature_rows != signal_rows:
        result.fail_message(
            "Feature/Signal row count mismatch: "
            f"feature={feature_rows:,}, "
            f"signal={signal_rows:,}"
        )
    else:
        result.pass_message(
            "Feature/Signal row counts match: "
            f"{feature_rows:,}"
        )

    if (
        feature_timestamp_column is None
        or signal_timestamp_column is None
        or feature_timestamps is None
        or signal_timestamps is None
    ):
        result.fail_message(
            "Feature/Signal timestamp alignment "
            "cannot be verified."
        )
        return

    if len(feature_timestamps) != len(signal_timestamps):
        result.fail_message(
            "Feature/Signal timestamp lengths differ."
        )
        return

    comparable = (
        feature_timestamps.notna()
        & signal_timestamps.notna()
    )

    mismatch_mask = pd.Series(
        False,
        index=feature_df.index,
        dtype=bool,
    )

    mismatch_mask.loc[comparable] = (
        feature_timestamps.loc[comparable].to_numpy()
        != signal_timestamps.loc[comparable].to_numpy()
    )

    mismatch_count = int(
        mismatch_mask.sum()
    )

    invalid_pair_count = int(
        (~comparable).sum()
    )

    if invalid_pair_count > 0:
        result.fail_message(
            "Feature/Signal contains invalid timestamp "
            f"pairs={invalid_pair_count:,}"
        )

    if mismatch_count > 0:
        result.fail_message(
            "Feature/Signal timestamp mismatches="
            f"{mismatch_count:,}"
        )

        print_problem_examples(
            signal_df,
            mismatch_mask,
            [
                signal_timestamp_column,
            ],
            "Signal timestamp mismatch examples:",
        )
    else:
        result.pass_message(
            "Feature/Signal timestamps match 1:1."
        )


# ============================================================
# 9. OHLCV VALIDATION
# ============================================================

def validate_ohlcv_prices(
    result: JobResult,
    df: pd.DataFrame,
) -> None:
    column_map = normalized_column_map(df)

    found_price_columns: dict[str, str] = {}

    for expected in PRICE_COLUMNS:
        if expected in column_map:
            found_price_columns[expected] = column_map[expected]

    if not found_price_columns:
        result.warn_message(
            "No standard OHLC price columns found "
            "in OHLCV file."
        )
        return

    for logical_name, column in found_price_columns.items():
        numeric = numeric_series(
            df[column]
        )

        invalid_numeric = int(
            numeric.isna().sum()
        )

        if invalid_numeric > 0:
            result.fail_message(
                f"OHLCV {logical_name} contains "
                f"{invalid_numeric:,} non-numeric/NaN values."
            )

        non_positive = int(
            (numeric.dropna() <= 0).sum()
        )

        if non_positive > 0:
            result.fail_message(
                f"OHLCV {logical_name} contains "
                f"{non_positive:,} non-positive values."
            )
        else:
            result.pass_message(
                f"OHLCV {logical_name} positive-value "
                "check passed."
            )

    required_for_relation = {
        "open",
        "high",
        "low",
        "close",
    }

    if not required_for_relation.issubset(
        found_price_columns.keys()
    ):
        result.warn_message(
            "OHLC relationship validation skipped "
            "because open/high/low/close are not all present."
        )
        return

    open_series = numeric_series(
        df[found_price_columns["open"]]
    )
    high_series = numeric_series(
        df[found_price_columns["high"]]
    )
    low_series = numeric_series(
        df[found_price_columns["low"]]
    )
    close_series = numeric_series(
        df[found_price_columns["close"]]
    )

    relation_valid = (
        high_series.ge(open_series)
        & high_series.ge(close_series)
        & low_series.le(open_series)
        & low_series.le(close_series)
        & high_series.ge(low_series)
    )

    relation_valid = relation_valid.fillna(False)

    invalid_relation_count = int(
        (~relation_valid).sum()
    )

    if invalid_relation_count > 0:
        result.fail_message(
            "OHLCV candle relationship failures="
            f"{invalid_relation_count:,}"
        )

        print_problem_examples(
            df,
            ~relation_valid,
            [
                found_price_columns["open"],
                found_price_columns["high"],
                found_price_columns["low"],
                found_price_columns["close"],
            ],
            "Invalid OHLC examples:",
        )
    else:
        result.pass_message(
            "OHLCV candle relationships passed."
        )


def validate_volume_columns(
    result: JobResult,
    df: pd.DataFrame,
) -> None:
    column_map = normalized_column_map(df)

    discovered: list[str] = []

    for candidate in (
        VOLUME_COLUMNS
        + TRADE_VALUE_COLUMNS
    ):
        normalized = normalize_column_name(candidate)

        if normalized in column_map:
            discovered.append(
                column_map[normalized]
            )

    discovered = list(
        dict.fromkeys(discovered)
    )

    if not discovered:
        result.warn_message(
            "No standard volume/trade-value columns "
            "were discovered."
        )
        return

    for column in discovered:
        numeric = numeric_series(
            df[column]
        )

        negative_count = int(
            (numeric.dropna() < 0).sum()
        )

        if negative_count > 0:
            result.fail_message(
                f"{column} contains negative values="
                f"{negative_count:,}"
            )
        else:
            result.pass_message(
                f"{column} non-negative check passed."
            )


# ============================================================
# 10. FEATURE / SIGNAL COMMON COLUMN CONSISTENCY
# ============================================================

def compare_common_numeric_column(
    result: JobResult,
    feature_df: pd.DataFrame,
    signal_df: pd.DataFrame,
    column_name: str,
) -> None:
    if column_name not in feature_df.columns:
        return

    if column_name not in signal_df.columns:
        return

    if len(feature_df) != len(signal_df):
        return

    feature_numeric = numeric_series(
        feature_df[column_name]
    )

    signal_numeric = numeric_series(
        signal_df[column_name]
    )

    both_nan = (
        feature_numeric.isna()
        & signal_numeric.isna()
    )

    one_nan = (
        feature_numeric.isna()
        ^ signal_numeric.isna()
    )

    comparable = (
        feature_numeric.notna()
        & signal_numeric.notna()
    )

    close_mask = pd.Series(
        True,
        index=feature_df.index,
        dtype=bool,
    )

    if comparable.any():
        feature_values = (
            feature_numeric.loc[comparable]
            .to_numpy(dtype=float)
        )

        signal_values = (
            signal_numeric.loc[comparable]
            .to_numpy(dtype=float)
        )

        close_values = np.isclose(
            feature_values,
            signal_values,
            rtol=FLOAT_RTOL,
            atol=FLOAT_ATOL,
            equal_nan=True,
        )

        close_mask.loc[comparable] = close_values

    mismatch = (
        one_nan
        | (
            ~both_nan
            & ~close_mask
        )
    )

    mismatch_count = int(
        mismatch.sum()
    )

    if mismatch_count > 0:
        result.fail_message(
            f"Feature/Signal common column '{column_name}' "
            f"differs in {mismatch_count:,} rows."
        )
    else:
        result.pass_message(
            f"Feature/Signal common column "
            f"'{column_name}' matches."
        )


def validate_common_feature_signal_values(
    result: JobResult,
    feature_df: pd.DataFrame,
    signal_df: pd.DataFrame,
) -> None:
    if len(feature_df) != len(signal_df):
        result.warn_message(
            "Common Feature/Signal value comparison "
            "skipped because row counts differ."
        )
        return

    feature_map = normalized_column_map(
        feature_df
    )
    signal_map = normalized_column_map(
        signal_df
    )

    logical_candidates = [
        "open",
        "high",
        "low",
        "close",
        "volume",
        "candle_acc_trade_volume",
        "candle_acc_trade_price",
    ]

    compared_columns = 0

    for logical_name in logical_candidates:
        if (
            logical_name not in feature_map
            or logical_name not in signal_map
        ):
            continue

        feature_column = feature_map[
            logical_name
        ]
        signal_column = signal_map[
            logical_name
        ]

        if feature_column != signal_column:
            # Compare directly without requiring identical
            # original capitalization.
            feature_numeric = numeric_series(
                feature_df[feature_column]
            )
            signal_numeric = numeric_series(
                signal_df[signal_column]
            )

            comparable = (
                feature_numeric.notna()
                & signal_numeric.notna()
            )

            mismatch_count = 0

            if comparable.any():
                same = np.isclose(
                    feature_numeric.loc[comparable]
                    .to_numpy(dtype=float),
                    signal_numeric.loc[comparable]
                    .to_numpy(dtype=float),
                    rtol=FLOAT_RTOL,
                    atol=FLOAT_ATOL,
                    equal_nan=True,
                )

                mismatch_count += int(
                    (~same).sum()
                )

            mismatch_count += int(
                (
                    feature_numeric.isna()
                    ^ signal_numeric.isna()
                ).sum()
            )

            if mismatch_count > 0:
                result.fail_message(
                    f"Feature/Signal '{logical_name}' "
                    f"differs in {mismatch_count:,} rows."
                )
            else:
                result.pass_message(
                    f"Feature/Signal '{logical_name}' matches."
                )

            compared_columns += 1
            continue

        compare_common_numeric_column(
            result,
            feature_df,
            signal_df,
            feature_column,
        )

        compared_columns += 1

    # Compare discovered MA columns where both sides have
    # equivalent logical periods.
    feature_ma = discover_ma_columns(
        feature_df
    )
    signal_ma = discover_ma_columns(
        signal_df
    )

    common_periods = sorted(
        set(feature_ma.keys())
        & set(signal_ma.keys())
    )

    for period in common_periods:
        feature_column = feature_ma[period]
        signal_column = signal_ma[period]

        feature_numeric = numeric_series(
            feature_df[feature_column]
        )
        signal_numeric = numeric_series(
            signal_df[signal_column]
        )

        comparable = (
            feature_numeric.notna()
            & signal_numeric.notna()
        )

        mismatch_count = 0

        if comparable.any():
            same = np.isclose(
                feature_numeric.loc[comparable]
                .to_numpy(dtype=float),
                signal_numeric.loc[comparable]
                .to_numpy(dtype=float),
                rtol=FLOAT_RTOL,
                atol=FLOAT_ATOL,
                equal_nan=True,
            )

            mismatch_count += int(
                (~same).sum()
            )

        mismatch_count += int(
            (
                feature_numeric.isna()
                ^ signal_numeric.isna()
            ).sum()
        )

        if mismatch_count > 0:
            result.fail_message(
                f"Feature/Signal MA{period} differs "
                f"in {mismatch_count:,} rows."
            )
        else:
            result.pass_message(
                f"Feature/Signal MA{period} matches."
            )

        compared_columns += 1

    if compared_columns == 0:
        result.warn_message(
            "No common core numeric columns were "
            "available for Feature/Signal value comparison."
        )


# ============================================================
# 11. FUTURE INFORMATION LEAKAGE CHECK
# ============================================================

def validate_no_future_information_columns(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    suspicious: list[str] = []

    for column in signal_df.columns:
        normalized = normalize_column_name(
            column
        )

        if normalized in FORBIDDEN_EXACT_COLUMNS:
            suspicious.append(
                str(column)
            )
            continue

        if any(
            keyword in normalized
            for keyword in FORBIDDEN_FUTURE_KEYWORDS
        ):
            suspicious.append(
                str(column)
            )

    suspicious = sorted(
        set(suspicious)
    )

    if suspicious:
        result.fail_message(
            "Potential future-information columns "
            f"detected: {suspicious}"
        )
        return

    result.pass_message(
        "No known future-information / future-label "
        "columns detected."
    )


# ============================================================
# 12. MA VALIDATION
# ============================================================

def validate_ma_columns(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    ma_columns = discover_ma_columns(
        signal_df
    )

    if not ma_columns:
        result.warn_message(
            "No MA5/20/60/112/224 columns discovered "
            "in Signal CSV."
        )
        return

    discovered_text = ", ".join(
        f"MA{period}={column}"
        for period, column in sorted(
            ma_columns.items()
        )
    )

    result.info_message(
        f"Discovered MA columns: {discovered_text}"
    )

    for period, column in sorted(
        ma_columns.items()
    ):
        numeric = numeric_series(
            signal_df[column]
        )

        finite = finite_mask(
            signal_df[column]
        )

        finite_count = int(
            finite.sum()
        )

        nan_count = int(
            numeric.isna().sum()
        )

        inf_count = int(
            (
                ~finite
                & numeric.notna()
            ).sum()
        )

        # Initial moving-average warm-up NaNs are normal.
        #
        # We therefore do not fail merely because the first
        # period-1 rows are NaN.
        #
        non_nan = numeric.dropna()

        if non_nan.empty:
            result.fail_message(
                f"MA{period} column '{column}' "
                "contains no numeric values."
            )
            continue

        non_positive = int(
            (non_nan <= 0).sum()
        )

        if non_positive > 0:
            result.fail_message(
                f"MA{period} contains non-positive values="
                f"{non_positive:,}"
            )
        else:
            result.pass_message(
                f"MA{period} positive-value check passed."
            )

        if inf_count > 0:
            result.fail_message(
                f"MA{period} contains infinite values="
                f"{inf_count:,}"
            )
        else:
            result.pass_message(
                f"MA{period} has no infinite values."
            )

        result.info_message(
            f"MA{period}: valid={finite_count:,}, "
            f"NaN/warmup={nan_count:,}"
        )


# ============================================================
# 13. SCORE VALIDATION
# ============================================================

def validate_score_columns(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    score_columns = discover_score_columns(
        signal_df
    )

    if not score_columns:
        result.warn_message(
            "No score columns discovered."
        )
        return

    result.info_message(
        "Score columns: "
        + ", ".join(score_columns)
    )

    for column in score_columns:
        numeric = numeric_series(
            signal_df[column]
        )

        non_null = numeric.dropna()

        if non_null.empty:
            result.warn_message(
                f"Score column '{column}' has "
                "no numeric values."
            )
            continue

        values = non_null.to_numpy(
            dtype=float
        )

        infinite_count = int(
            (~np.isfinite(values)).sum()
        )

        if infinite_count > 0:
            result.fail_message(
                f"Score '{column}' contains "
                f"infinite values={infinite_count:,}"
            )
            continue

        minimum = float(
            non_null.min()
        )
        maximum = float(
            non_null.max()
        )
        mean_value = float(
            non_null.mean()
        )

        result.pass_message(
            f"Score '{column}' numeric check passed."
        )

        result.info_message(
            f"Score '{column}': "
            f"min={minimum:.6f}, "
            f"max={maximum:.6f}, "
            f"mean={mean_value:.6f}, "
            f"non-null={len(non_null):,}"
        )


# ============================================================
# 14. STATE VALIDATION
# ============================================================

def count_state_from_combined_column(
    series: pd.Series,
    state_name: str,
) -> int:
    normalized = (
        series
        .astype(str)
        .str.strip()
        .str.upper()
    )

    return int(
        normalized.eq(
            state_name.upper()
        ).sum()
    )


def validate_research_states(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    combined_state_column = discover_combined_state_column(
        signal_df
    )

    state_counts: dict[str, int | None] = {
        "SETUP": None,
        "READY": None,
        "TRIGGER": None,
    }

    if combined_state_column is not None:
        result.info_message(
            "Combined research-state column: "
            f"'{combined_state_column}'"
        )

        for state_name in state_counts:
            state_counts[state_name] = (
                count_state_from_combined_column(
                    signal_df[
                        combined_state_column
                    ],
                    state_name,
                )
            )

    for state_name in state_counts:
        if state_counts[state_name] is not None:
            continue

        state_column = discover_state_column(
            signal_df,
            state_name,
        )

        if state_column is None:
            continue

        mask = true_mask_from_series(
            signal_df[state_column]
        )

        state_counts[state_name] = int(
            mask.sum()
        )

        result.info_message(
            f"{state_name} state column: "
            f"'{state_column}'"
        )

    setup_count = state_counts[
        "SETUP"
    ]
    ready_count = state_counts[
        "READY"
    ]
    trigger_count = state_counts[
        "TRIGGER"
    ]

    result.setup_count = setup_count
    result.ready_count = ready_count
    result.trigger_count = trigger_count

    discovered_count = sum(
        value is not None
        for value in state_counts.values()
    )

    if discovered_count == 0:
        result.fail_message(
            "SETUP / READY / TRIGGER state columns "
            "could not be discovered."
        )
        return

    if discovered_count < 3:
        missing_states = [
            state_name
            for state_name, value
            in state_counts.items()
            if value is None
        ]

        result.warn_message(
            "Some research states could not be "
            f"discovered: {missing_states}"
        )

    total_rows = len(
        signal_df
    )

    for state_name, count in state_counts.items():
        if count is None:
            continue

        result.pass_message(
            f"{state_name} count={count:,} "
            f"({format_percentage(count, total_rows)})"
        )

    # IMPORTANT:
    #
    # Clean V001 does NOT enforce:
    #
    #   SETUP >= READY >= TRIGGER
    #
    # because the current detector may define these states
    # independently rather than as mutually exclusive
    # sequential stages.
    #
    # This is intentionally reported instead of assumed.
    #
    if all(
        state_counts[state] is not None
        for state in (
            "SETUP",
            "READY",
            "TRIGGER",
        )
    ):
        result.info_message(
            "State counts are informational only. "
            "Clean V001 does not assume "
            "SETUP -> READY -> TRIGGER exclusivity."
        )


# ============================================================
# 15. BOOLEAN / CONDITION COLUMN VALIDATION
# ============================================================

def validate_boolean_condition_columns(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    columns = discover_boolean_like_columns(
        signal_df
    )

    if not columns:
        result.warn_message(
            "No boolean-like detector condition columns "
            "were discovered."
        )
        return

    result.info_message(
        f"Boolean-like condition columns discovered="
        f"{len(columns):,}"
    )

    for column in columns:
        series = signal_df[column]

        non_null = series.dropna()

        if non_null.empty:
            result.warn_message(
                f"Condition '{column}' contains "
                "only null values."
            )
            continue

        mask = true_mask_from_series(
            series
        )

        true_count = int(
            mask.sum()
        )

        false_count = int(
            len(series) - true_count
        )

        unique_preview = (
            non_null
            .astype(str)
            .drop_duplicates()
            .head(10)
            .tolist()
        )

        result.info_message(
            f"Condition '{column}': "
            f"true-like={true_count:,}, "
            f"false-like={false_count:,}, "
            f"values={unique_preview}"
        )


# ============================================================
# 16. SIGNAL NUMERIC SAFETY
# ============================================================

def validate_signal_numeric_safety(
    result: JobResult,
    signal_df: pd.DataFrame,
) -> None:
    numeric_columns = signal_df.select_dtypes(
        include=[
            np.number,
        ]
    ).columns.tolist()

    if not numeric_columns:
        result.warn_message(
            "Signal CSV contains no pandas-native "
            "numeric columns."
        )
        return

    infinite_columns: list[
        tuple[str, int]
    ] = []

    for column in numeric_columns:
        series = pd.to_numeric(
            signal_df[column],
            errors="coerce",
        )

        values = series.to_numpy(
            dtype=float,
            na_value=np.nan,
        )

        inf_count = int(
            np.isinf(values).sum()
        )

        if inf_count > 0:
            infinite_columns.append(
                (
                    str(column),
                    inf_count,
                )
            )

    if infinite_columns:
        result.fail_message(
            "Infinite numeric values detected: "
            f"{infinite_columns}"
        )
    else:
        result.pass_message(
            "No infinite values found in numeric "
            "Signal columns."
        )


# ============================================================
# 17. HASH SAFETY
# ============================================================

def validate_files_unchanged(
    result: JobResult,
    before_hashes: dict[str, str],
    paths: dict[str, Path],
) -> None:
    for label, path in paths.items():
        if not path.exists():
            result.fail_message(
                f"{label} disappeared during validation."
            )
            continue

        after_hash = sha256_file(
            path
        )

        before_hash = before_hashes[
            label
        ]

        if after_hash != before_hash:
            result.fail_message(
                f"{label} SHA256 CHANGED during "
                "read-only validation."
            )
        else:
            result.pass_message(
                f"{label} SHA256 unchanged."
            )


# ============================================================
# 18. SINGLE JOB VALIDATION
# ============================================================

def validate_job(
    market: str,
    timeframe: str,
) -> JobResult:
    started = time.perf_counter()

    result = JobResult(
        market=market,
        timeframe=timeframe,
    )

    ohlcv_path = (
        OHLCV_ROOT
        / timeframe
        / f"{market}.csv"
    )

    feature_path = (
        FEATURE_ROOT
        / timeframe
        / f"{market}.csv"
    )

    signal_path = (
        SIGNAL_ROOT
        / timeframe
        / f"{market}.csv"
    )

    print(separator())
    print(
        f"[{timeframe.upper()}] {market}"
    )
    print(f"OHLCV  : {ohlcv_path}")
    print(f"Feature: {feature_path}")
    print(f"Signal : {signal_path}")

    paths_ok = validate_required_paths(
        result,
        ohlcv_path,
        feature_path,
        signal_path,
    )

    if not paths_ok:
        result.elapsed_seconds = (
            time.perf_counter()
            - started
        )

        print_job_result(
            result
        )

        return result

    source_paths = {
        "OHLCV": ohlcv_path,
        "Feature": feature_path,
        "Signal": signal_path,
    }

    before_hashes = {
        label: sha256_file(path)
        for label, path
        in source_paths.items()
    }

    try:
        ohlcv_df = read_csv_read_only(
            ohlcv_path
        )

        feature_df = read_csv_read_only(
            feature_path
        )

        signal_df = read_csv_read_only(
            signal_path
        )

    except Exception as exc:
        result.fail_message(
            "CSV read failure: "
            f"{type(exc).__name__}: {exc}"
        )

        validate_files_unchanged(
            result,
            before_hashes,
            source_paths,
        )

        result.elapsed_seconds = (
            time.perf_counter()
            - started
        )

        print_job_result(
            result
        )

        return result

    result.ohlcv_rows = len(
        ohlcv_df
    )
    result.feature_rows = len(
        feature_df
    )
    result.signal_rows = len(
        signal_df
    )

    # --------------------------------------------------------
    # Basic dataframe validation
    # --------------------------------------------------------

    validate_non_empty_dataframe(
        result,
        "OHLCV",
        ohlcv_df,
    )

    validate_non_empty_dataframe(
        result,
        "Feature",
        feature_df,
    )

    validate_non_empty_dataframe(
        result,
        "Signal",
        signal_df,
    )

    validate_unique_column_names(
        result,
        "OHLCV",
        ohlcv_df,
    )

    validate_unique_column_names(
        result,
        "Feature",
        feature_df,
    )

    validate_unique_column_names(
        result,
        "Signal",
        signal_df,
    )

    # --------------------------------------------------------
    # Timestamp validation
    # --------------------------------------------------------

    (
        ohlcv_timestamp_column,
        ohlcv_timestamps,
    ) = validate_timestamp_integrity(
        result,
        "OHLCV",
        ohlcv_df,
    )

    (
        feature_timestamp_column,
        feature_timestamps,
    ) = validate_timestamp_integrity(
        result,
        "Feature",
        feature_df,
    )

    (
        signal_timestamp_column,
        signal_timestamps,
    ) = validate_timestamp_integrity(
        result,
        "Signal",
        signal_df,
    )

    # OHLCV timestamp values are intentionally not required
    # to have exactly the same number of rows as Feature if
    # future Feature Builder behavior removes warm-up rows.
    #
    # Current Feature/Signal output MUST align 1:1.
    #

    validate_feature_signal_alignment(
        result,
        feature_df,
        signal_df,
        feature_timestamp_column,
        signal_timestamp_column,
        feature_timestamps,
        signal_timestamps,
    )

    # --------------------------------------------------------
    # OHLCV sanity
    # --------------------------------------------------------

    validate_ohlcv_prices(
        result,
        ohlcv_df,
    )

    validate_volume_columns(
        result,
        ohlcv_df,
    )

    # --------------------------------------------------------
    # Feature -> Signal preservation
    # --------------------------------------------------------

    validate_common_feature_signal_values(
        result,
        feature_df,
        signal_df,
    )

    # --------------------------------------------------------
    # Future-information leakage
    # --------------------------------------------------------

    validate_no_future_information_columns(
        result,
        signal_df,
    )

    # --------------------------------------------------------
    # 256 research columns
    # --------------------------------------------------------

    validate_ma_columns(
        result,
        signal_df,
    )

    validate_score_columns(
        result,
        signal_df,
    )

    validate_research_states(
        result,
        signal_df,
    )

    validate_boolean_condition_columns(
        result,
        signal_df,
    )

    validate_signal_numeric_safety(
        result,
        signal_df,
    )

    # --------------------------------------------------------
    # Timestamp relation to OHLCV
    # --------------------------------------------------------

    if (
        ohlcv_timestamp_column is not None
        and signal_timestamp_column is not None
        and ohlcv_timestamps is not None
        and signal_timestamps is not None
    ):
        valid_ohlcv_timestamps = set(
            ohlcv_timestamps
            .dropna()
            .tolist()
        )

        valid_signal = (
            signal_timestamps
            .dropna()
        )

        missing_from_ohlcv = (
            ~valid_signal.isin(
                valid_ohlcv_timestamps
            )
        )

        missing_count = int(
            missing_from_ohlcv.sum()
        )

        if missing_count > 0:
            result.fail_message(
                "Signal contains timestamps not found "
                f"in OHLCV: {missing_count:,}"
            )
        else:
            result.pass_message(
                "Every valid Signal timestamp exists "
                "in OHLCV."
            )

    # --------------------------------------------------------
    # Source file immutability
    # --------------------------------------------------------

    validate_files_unchanged(
        result,
        before_hashes,
        source_paths,
    )

    result.elapsed_seconds = (
        time.perf_counter()
        - started
    )

    print_job_result(
        result
    )

    return result


# ============================================================
# 19. JOB OUTPUT
# ============================================================

def print_job_result(
    result: JobResult,
) -> None:
    print()

    for message in result.messages:
        print(
            f"[{message.level}] "
            f"{message.message}"
        )

    print()
    print(
        f"Rows    : "
        f"OHLCV={result.ohlcv_rows:,} | "
        f"Feature={result.feature_rows:,} | "
        f"Signal={result.signal_rows:,}"
    )

    if result.setup_count is not None:
        print(
            f"SETUP   : "
            f"{result.setup_count:,}"
        )

    if result.ready_count is not None:
        print(
            f"READY   : "
            f"{result.ready_count:,}"
        )

    if result.trigger_count is not None:
        print(
            f"TRIGGER : "
            f"{result.trigger_count:,}"
        )

    print(
        f"Elapsed : "
        f"{result.elapsed_seconds:.2f}s"
    )

    if result.passed:
        print(
            "[RESULT] PASS"
        )
    else:
        print(
            "[RESULT] FAIL"
        )


# ============================================================
# 20. PROJECT-LEVEL VALIDATION
# ============================================================

def validate_project_structure() -> bool:
    print(separator("="))
    print(
        "PROJECT STRUCTURE CHECK"
    )
    print(separator("="))

    required_directories = [
        DATA_DIR,
        OHLCV_ROOT,
        FEATURE_ROOT,
        SIGNAL_ROOT,
    ]

    ok = True

    for directory in required_directories:
        if directory.exists() and directory.is_dir():
            print(
                f"[PASS] {directory}"
            )
        else:
            print(
                f"[FAIL] Missing directory: "
                f"{directory}"
            )
            ok = False

    for timeframe in TIMEFRAMES:
        directories = [
            OHLCV_ROOT / timeframe,
            FEATURE_ROOT / timeframe,
            SIGNAL_ROOT / timeframe,
        ]

        for directory in directories:
            if (
                directory.exists()
                and directory.is_dir()
            ):
                print(
                    f"[PASS] {directory}"
                )
            else:
                print(
                    f"[FAIL] Missing directory: "
                    f"{directory}"
                )
                ok = False

    return ok


# ============================================================
# 21. SUMMARY
# ============================================================

def print_summary(
    results: list[JobResult],
    total_elapsed: float,
) -> None:
    print()
    print(separator("="))
    print(
        "256 VALIDATOR SUMMARY"
    )
    print(separator("="))

    total_jobs = len(
        results
    )

    passed_jobs = sum(
        1
        for result in results
        if result.passed
    )

    failed_jobs = (
        total_jobs
        - passed_jobs
    )

    total_ohlcv_rows = sum(
        result.ohlcv_rows
        for result in results
    )

    total_feature_rows = sum(
        result.feature_rows
        for result in results
    )

    total_signal_rows = sum(
        result.signal_rows
        for result in results
    )

    setup_total = sum(
        result.setup_count
        for result in results
        if result.setup_count is not None
    )

    ready_total = sum(
        result.ready_count
        for result in results
        if result.ready_count is not None
    )

    trigger_total = sum(
        result.trigger_count
        for result in results
        if result.trigger_count is not None
    )

    setup_available = any(
        result.setup_count is not None
        for result in results
    )

    ready_available = any(
        result.ready_count is not None
        for result in results
    )

    trigger_available = any(
        result.trigger_count is not None
        for result in results
    )

    print(
        f"Project       : {PROJECT_NAME}"
    )
    print(
        f"Validator     : {VALIDATOR_VERSION}"
    )
    print(
        f"Base dir      : {BASE_DIR}"
    )
    print(
        f"Markets       : {len(MARKETS)}"
    )
    print(
        f"Timeframes    : {len(TIMEFRAMES)}"
    )
    print(
        f"Total jobs    : {total_jobs}"
    )
    print(
        f"Passed jobs   : {passed_jobs}"
    )
    print(
        f"Failed jobs   : {failed_jobs}"
    )
    print(
        f"OHLCV rows    : {total_ohlcv_rows:,}"
    )
    print(
        f"Feature rows  : {total_feature_rows:,}"
    )
    print(
        f"Signal rows   : {total_signal_rows:,}"
    )

    print()
    print(
        "256 Research States:"
    )

    if setup_available:
        print(
            f"  SETUP       : {setup_total:,}"
        )
    else:
        print(
            "  SETUP       : NOT DISCOVERED"
        )

    if ready_available:
        print(
            f"  READY       : {ready_total:,}"
        )
    else:
        print(
            "  READY       : NOT DISCOVERED"
        )

    if trigger_available:
        print(
            f"  TRIGGER     : {trigger_total:,}"
        )
    else:
        print(
            "  TRIGGER     : NOT DISCOVERED"
        )

    print()
    print(
        "Validation:"
    )
    print(
        "  File existence       : CHECKED"
    )
    print(
        "  CSV readability      : CHECKED"
    )
    print(
        "  Timestamp integrity  : CHECKED"
    )
    print(
        "  Feature/Signal 1:1   : CHECKED"
    )
    print(
        "  OHLC sanity          : CHECKED"
    )
    print(
        "  MA values            : CHECKED IF PRESENT"
    )
    print(
        "  Scores               : CHECKED IF PRESENT"
    )
    print(
        "  Research states      : CHECKED"
    )
    print(
        "  Future leakage       : CHECKED"
    )
    print(
        "  Source SHA256        : CHECKED"
    )

    print()
    print(
        "Safety:"
    )
    print(
        "  Source modification  : DISABLED"
    )
    print(
        "  Future label         : NOT CREATED"
    )
    print(
        "  Prediction           : DISABLED"
    )
    print(
        "  Trading              : DISABLED"
    )

    print()
    print(
        f"Elapsed total : "
        f"{total_elapsed:.2f}s"
    )

    print()

    for result in results:
        status = (
            "PASSED"
            if result.passed
            else "FAILED"
        )

        state_parts: list[str] = []

        if result.setup_count is not None:
            state_parts.append(
                f"setup={result.setup_count:,}"
            )

        if result.ready_count is not None:
            state_parts.append(
                f"ready={result.ready_count:,}"
            )

        if result.trigger_count is not None:
            state_parts.append(
                f"trigger={result.trigger_count:,}"
            )

        state_text = (
            " "
            + " ".join(state_parts)
            if state_parts
            else ""
        )

        print(
            f"[{status}] "
            f"{result.market} "
            f"{result.timeframe} "
            f"signal_rows={result.signal_rows:,}"
            f"{state_text}"
        )

    print(separator("="))

    if failed_jobs == 0:
        print(
            "[RESULT] 256 VALIDATOR PASSED"
        )
        print(
            "[PASS] Detector outputs passed "
            "Clean V001 structural validation."
        )
        print(
            "[PASS] Source OHLCV / Feature / Signal "
            "files remained unchanged."
        )
        print(
            "[PASS] No known future-result columns "
            "were detected."
        )
        print(
            "[NEXT] Review validation output before "
            "implementing future-result labels."
        )
    else:
        print(
            "[RESULT] 256 VALIDATOR FAILED"
        )
        print(
            "[STOP] Do NOT proceed to future-result "
            "labels yet."
        )
        print(
            "[NEXT] Fix the failed validation item(s) "
            "and run this validator again."
        )


# ============================================================
# 22. MAIN
# ============================================================

def main() -> int:
    total_started = time.perf_counter()

    print()
    print(separator("="))
    print(
        f"{PROJECT_NAME} - "
        f"{VALIDATOR_VERSION}"
    )
    print(
        "STEP 4 - 256 DETECTOR OUTPUT VALIDATION"
    )
    print(separator("="))

    print(
        f"Started UTC : {utc_now_text()}"
    )
    print(
        f"Base dir    : {BASE_DIR}"
    )

    print()
    print(
        "Mode:"
    )
    print(
        "  READ ONLY validation"
    )
    print(
        "  KRW-BTC validation mode"
    )
    print(
        "  h1 / h4 / d1"
    )
    print(
        "  Feature / Signal 1:1 verification"
    )
    print(
        "  SETUP / READY / TRIGGER inspection"
    )
    print(
        "  MA / score / condition inspection"
    )
    print(
        "  Future-information leakage check"
    )
    print(
        "  Source SHA256 integrity check"
    )
    print(
        "  No future labels"
    )
    print(
        "  No prediction"
    )
    print(
        "  No trading"
    )

    print()

    structure_ok = validate_project_structure()

    if not structure_ok:
        print()
        print(separator("="))
        print(
            "[RESULT] PROJECT STRUCTURE FAILED"
        )
        print(
            "[STOP] Required local data directories "
            "are missing."
        )
        print(separator("="))

        return 1

    results: list[JobResult] = []

    for market in MARKETS:
        for timeframe in TIMEFRAMES:
            result = validate_job(
                market=market,
                timeframe=timeframe,
            )

            results.append(
                result
            )

    total_elapsed = (
        time.perf_counter()
        - total_started
    )

    print_summary(
        results,
        total_elapsed,
    )

    failed_jobs = [
        result
        for result in results
        if not result.passed
    ]

    if failed_jobs:
        return 1

    return 0


# ============================================================
# 23. ENTRY POINT
# ============================================================

if __name__ == "__main__":
    try:
        exit_code = main()

    except KeyboardInterrupt:
        print()
        print(
            "[STOP] Validation interrupted by user."
        )
        exit_code = 130

    except Exception as exc:
        print()
        print(separator("="))
        print(
            "[FATAL] Unexpected validator error"
        )
        print(separator("="))
        print(
            f"{type(exc).__name__}: {exc}"
        )
        print()
        print(
            "No source file should have been modified."
        )

        exit_code = 1

    sys.exit(
        exit_code
    )


# ============================================================
# END
# ============================================================
