"""
Upbit Surge Monitor
Collector Data Validator

Version:
    Clean V002

File:
    validate_collector.py

Purpose:
    Validate OHLCV files generated by collector.py.

Main responsibilities:
    - Load the current Upbit KRW market list dynamically.
    - Validate h1 / h4 / d1 OHLCV CSV files.
    - Verify that every current KRW market exists in every timeframe.
    - Preserve historical CSV files for markets that are no longer active.
    - Detect invalid timestamps, duplicates, sorting problems,
      invalid OHLCV values, and invalid OHLC relationships.
    - Compare market sets across h1 / h4 / d1.
    - Never modify source OHLCV files.

Important:
    - This script NEVER modifies OHLCV source files.
    - Historical CSV files are never deleted.
    - Extra CSV files that are no longer in the current Upbit KRW
      market list are treated as historical data, not as errors.
    - Designed for Windows PC execution with:

          py validate_collector.py --mode pre
          py validate_collector.py --mode post

    PRE  : allow a market that is completely absent from h1/h4/d1
           (treated as a newly listed market waiting for backfill).
           Partial timeframe absence still fails.
    POST : require every current KRW market in h1/h4/d1.

Expected structure:

    data/
        ohlcv/
            h1/
            h4/
            d1/
        collector_status.csv
"""

from __future__ import annotations

import argparse
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import requests


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VERSION = "Clean V002"

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
OHLCV_DIR = DATA_DIR / "ohlcv"

TIMEFRAME_DIRS = {
    "h1": OHLCV_DIR / "h1",
    "h4": OHLCV_DIR / "h4",
    "d1": OHLCV_DIR / "d1",
}

UPBIT_API_BASE = "https://api.upbit.com/v1"

REQUEST_TIMEOUT = 15
MAX_RETRIES = 5

SESSION = requests.Session()

SESSION.headers.update(
    {
        "Accept": "application/json",
        "User-Agent": "upbit-surge-monitor-validator-clean-v002",
    }
)


# ============================================================
# COLUMN CONFIGURATION
# ============================================================

TIMESTAMP_CANDIDATES = (
    "candle_date_time_utc",
    "timestamp",
    "datetime",
    "candle_date_time_kst",
)

REQUIRED_OHLC_COLUMNS = (
    "open",
    "high",
    "low",
    "close",
    "volume",
)

OPTIONAL_COLUMNS = (
    "market",
    "trade_value",
    "trade_price",
    "candle_acc_trade_price",
    "candle_acc_trade_volume",
)


# ============================================================
# RESULT MODELS
# ============================================================

@dataclass
class FileValidationResult:
    timeframe: str
    market: str
    path: Path

    passed: bool = True
    row_count: int = 0

    first_timestamp: str = ""
    last_timestamp: str = ""

    timestamp_column: str = ""

    duplicate_timestamps: int = 0
    invalid_timestamps: int = 0
    unsorted_timestamps: int = 0

    missing_required_columns: list[str] = field(default_factory=list)

    nan_open: int = 0
    nan_high: int = 0
    nan_low: int = 0
    nan_close: int = 0
    nan_volume: int = 0

    negative_open: int = 0
    negative_high: int = 0
    negative_low: int = 0
    negative_close: int = 0
    negative_volume: int = 0

    invalid_high_low: int = 0
    invalid_high_open: int = 0
    invalid_high_close: int = 0
    invalid_low_open: int = 0
    invalid_low_close: int = 0

    infinite_values: int = 0

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class TimeframeValidationResult:
    timeframe: str
    directory: Path

    directory_exists: bool = False

    file_count: int = 0
    current_market_file_count: int = 0
    historical_file_count: int = 0

    total_rows: int = 0

    passed_files: int = 0
    failed_files: int = 0

    missing_current_markets: list[str] = field(default_factory=list)
    historical_markets: list[str] = field(default_factory=list)

    files: list[FileValidationResult] = field(default_factory=list)

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ============================================================
# DISPLAY HELPERS
# ============================================================

def print_separator(
    char: str = "=",
    width: int = 78,
) -> None:
    print(char * width)


def print_header(title: str) -> None:
    print()
    print_separator("=")
    print(title)
    print_separator("=")


def safe_text(value: Any) -> str:
    if value is None:
        return ""

    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass

    return str(value)


# ============================================================
# HTTP
# ============================================================

def request_json(
    url: str,
    params: dict[str, Any] | None = None,
) -> Any:
    """
    Call Upbit REST API and return JSON.

    Temporary network errors, HTTP 429, and server errors
    are retried.
    """

    last_error: Exception | None = None

    for attempt in range(1, MAX_RETRIES + 1):

        try:
            response = SESSION.get(
                url,
                params=params,
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 429:
                wait_seconds = min(
                    float(attempt),
                    5.0,
                )

                print(
                    f"[WARN] HTTP 429 rate limit. "
                    f"retry={attempt}/{MAX_RETRIES}, "
                    f"wait={wait_seconds:.1f}s"
                )

                time.sleep(wait_seconds)
                continue

            if 500 <= response.status_code <= 599:
                wait_seconds = min(
                    float(attempt),
                    5.0,
                )

                print(
                    f"[WARN] Upbit server error "
                    f"{response.status_code}. "
                    f"retry={attempt}/{MAX_RETRIES}"
                )

                time.sleep(wait_seconds)
                continue

            response.raise_for_status()

            return response.json()

        except (
            requests.Timeout,
            requests.ConnectionError,
            requests.HTTPError,
            ValueError,
        ) as exc:

            last_error = exc

            if attempt >= MAX_RETRIES:
                break

            wait_seconds = min(
                float(attempt),
                5.0,
            )

            print(
                f"[WARN] Request failed: {exc} "
                f"retry={attempt}/{MAX_RETRIES}"
            )

            time.sleep(wait_seconds)

    if last_error is None:
        raise RuntimeError(
            "Unknown Upbit API request failure."
        )

    raise RuntimeError(
        f"Upbit API request failed after "
        f"{MAX_RETRIES} attempts: {last_error}"
    )


# ============================================================
# CURRENT UPBIT KRW MARKETS
# ============================================================

def get_current_krw_markets() -> list[str]:
    """
    Load the current KRW market list directly from Upbit.

    The validator intentionally does not use a fixed expected
    market count because listings and delistings can change.
    """

    url = f"{UPBIT_API_BASE}/market/all"

    data = request_json(
        url,
        params={
            "is_details": "false",
        },
    )

    if not isinstance(data, list):
        raise RuntimeError(
            "Unexpected Upbit market API response."
        )

    markets: list[str] = []

    for item in data:

        if not isinstance(item, dict):
            continue

        market = str(
            item.get("market", "")
        ).strip().upper()

        if market.startswith("KRW-"):
            markets.append(market)

    markets = sorted(set(markets))

    if not markets:
        raise RuntimeError(
            "No KRW markets were returned from Upbit."
        )

    return markets


# ============================================================
# COLUMN HELPERS
# ============================================================

def normalize_column_name(column: str) -> str:
    return str(column).strip().lower()


def build_column_lookup(
    df: pd.DataFrame,
) -> dict[str, str]:

    lookup: dict[str, str] = {}

    for column in df.columns:

        normalized = normalize_column_name(
            column
        )

        if normalized not in lookup:
            lookup[normalized] = column

    return lookup


def find_timestamp_column(
    df: pd.DataFrame,
) -> str | None:

    lookup = build_column_lookup(df)

    for candidate in TIMESTAMP_CANDIDATES:

        if candidate in lookup:
            return lookup[candidate]

    return None


def find_required_column(
    df: pd.DataFrame,
    required_name: str,
) -> str | None:

    lookup = build_column_lookup(df)

    return lookup.get(required_name)


# ============================================================
# NUMERIC HELPERS
# ============================================================

def to_numeric_series(
    series: pd.Series,
) -> pd.Series:

    return pd.to_numeric(
        series,
        errors="coerce",
    )


def count_infinite_in_columns(
    df: pd.DataFrame,
    columns: list[str],
) -> int:

    total = 0

    for column in columns:

        numeric = to_numeric_series(
            df[column]
        )

        values = numeric.to_numpy(
            dtype=float,
            na_value=np.nan,
        )

        total += int(
            np.isinf(values).sum()
        )

    return total


# ============================================================
# TIMESTAMP VALIDATION
# ============================================================

def validate_timestamp(
    df: pd.DataFrame,
    result: FileValidationResult,
) -> pd.Series | None:

    timestamp_column = find_timestamp_column(
        df
    )

    if timestamp_column is None:

        result.passed = False

        result.errors.append(
            "Timestamp column not found. "
            f"Expected one of: "
            f"{', '.join(TIMESTAMP_CANDIDATES)}"
        )

        return None

    result.timestamp_column = timestamp_column

    timestamps = pd.to_datetime(
        df[timestamp_column],
        errors="coerce",
        utc=True,
    )

    result.invalid_timestamps = int(
        timestamps.isna().sum()
    )

    if result.invalid_timestamps > 0:

        result.passed = False

        result.errors.append(
            "Invalid timestamps: "
            f"{result.invalid_timestamps:,}"
        )

    valid_timestamps = timestamps.dropna()

    if valid_timestamps.empty:

        result.passed = False

        result.errors.append(
            "No valid timestamps found."
        )

        return timestamps

    result.first_timestamp = safe_text(
        valid_timestamps.min()
    )

    result.last_timestamp = safe_text(
        valid_timestamps.max()
    )

    result.duplicate_timestamps = int(
        valid_timestamps.duplicated(
            keep=False
        ).sum()
    )

    if result.duplicate_timestamps > 0:

        result.passed = False

        result.errors.append(
            "Duplicate timestamp rows: "
            f"{result.duplicate_timestamps:,}"
        )

    valid_array = valid_timestamps.reset_index(
        drop=True
    )

    if len(valid_array) >= 2:

        diff = valid_array.diff()

        result.unsorted_timestamps = int(
            (
                diff.iloc[1:]
                < pd.Timedelta(0)
            ).sum()
        )

        if result.unsorted_timestamps > 0:

            result.passed = False

            result.errors.append(
                "Timestamp order errors: "
                f"{result.unsorted_timestamps:,}"
            )

    return timestamps


# ============================================================
# REQUIRED COLUMN VALIDATION
# ============================================================

def validate_required_columns(
    df: pd.DataFrame,
    result: FileValidationResult,
) -> dict[str, str]:

    resolved: dict[str, str] = {}

    for required in REQUIRED_OHLC_COLUMNS:

        actual = find_required_column(
            df,
            required,
        )

        if actual is None:

            result.missing_required_columns.append(
                required
            )

        else:

            resolved[required] = actual

    if result.missing_required_columns:

        result.passed = False

        result.errors.append(
            "Missing required columns: "
            + ", ".join(
                result.missing_required_columns
            )
        )

    return resolved


# ============================================================
# NUMERIC OHLCV VALIDATION
# ============================================================

def validate_numeric_columns(
    df: pd.DataFrame,
    columns: dict[str, str],
    result: FileValidationResult,
) -> dict[str, pd.Series]:

    numeric: dict[str, pd.Series] = {}

    for logical_name, actual_name in columns.items():

        numeric[logical_name] = (
            to_numeric_series(
                df[actual_name]
            )
        )

    if "open" in numeric:

        result.nan_open = int(
            numeric["open"].isna().sum()
        )

        result.negative_open = int(
            (
                numeric["open"] < 0
            ).fillna(False).sum()
        )

    if "high" in numeric:

        result.nan_high = int(
            numeric["high"].isna().sum()
        )

        result.negative_high = int(
            (
                numeric["high"] < 0
            ).fillna(False).sum()
        )

    if "low" in numeric:

        result.nan_low = int(
            numeric["low"].isna().sum()
        )

        result.negative_low = int(
            (
                numeric["low"] < 0
            ).fillna(False).sum()
        )

    if "close" in numeric:

        result.nan_close = int(
            numeric["close"].isna().sum()
        )

        result.negative_close = int(
            (
                numeric["close"] < 0
            ).fillna(False).sum()
        )

    if "volume" in numeric:

        result.nan_volume = int(
            numeric["volume"].isna().sum()
        )

        result.negative_volume = int(
            (
                numeric["volume"] < 0
            ).fillna(False).sum()
        )

    nan_total = (
        result.nan_open
        + result.nan_high
        + result.nan_low
        + result.nan_close
        + result.nan_volume
    )

    negative_total = (
        result.negative_open
        + result.negative_high
        + result.negative_low
        + result.negative_close
        + result.negative_volume
    )

    if nan_total > 0:

        result.passed = False

        result.errors.append(
            "NaN/non-numeric OHLCV values: "
            f"{nan_total:,}"
        )

    if negative_total > 0:

        result.passed = False

        result.errors.append(
            "Negative OHLCV values: "
            f"{negative_total:,}"
        )

    actual_columns = list(
        columns.values()
    )

    if actual_columns:

        result.infinite_values = (
            count_infinite_in_columns(
                df,
                actual_columns,
            )
        )

        if result.infinite_values > 0:

            result.passed = False

            result.errors.append(
                "Infinite OHLCV values: "
                f"{result.infinite_values:,}"
            )

    return numeric


# ============================================================
# OHLC RELATIONSHIP VALIDATION
# ============================================================

def validate_ohlc_logic(
    numeric: dict[str, pd.Series],
    result: FileValidationResult,
) -> None:

    required = {
        "open",
        "high",
        "low",
        "close",
    }

    if not required.issubset(numeric):
        return

    open_series = numeric["open"]
    high_series = numeric["high"]
    low_series = numeric["low"]
    close_series = numeric["close"]

    result.invalid_high_low = int(
        (
            high_series < low_series
        ).fillna(False).sum()
    )

    result.invalid_high_open = int(
        (
            high_series < open_series
        ).fillna(False).sum()
    )

    result.invalid_high_close = int(
        (
            high_series < close_series
        ).fillna(False).sum()
    )

    result.invalid_low_open = int(
        (
            low_series > open_series
        ).fillna(False).sum()
    )

    result.invalid_low_close = int(
        (
            low_series > close_series
        ).fillna(False).sum()
    )

    invalid_total = (
        result.invalid_high_low
        + result.invalid_high_open
        + result.invalid_high_close
        + result.invalid_low_open
        + result.invalid_low_close
    )

    if invalid_total > 0:

        result.passed = False

        result.errors.append(
            "Invalid OHLC relationships: "
            f"{invalid_total:,}"
        )


# ============================================================
# MARKET COLUMN VALIDATION
# ============================================================

def validate_market_column(
    df: pd.DataFrame,
    expected_market: str,
    result: FileValidationResult,
) -> None:
    """
    If the CSV contains a market column, verify that it agrees
    with the filename.

    Example:
        KRW-BTC.csv -> market column must contain KRW-BTC.
    """

    lookup = build_column_lookup(df)

    market_column = lookup.get("market")

    if market_column is None:

        result.warnings.append(
            "Market column not found."
        )

        return

    values = (
        df[market_column]
        .dropna()
        .astype(str)
        .str.strip()
        .str.upper()
    )

    if values.empty:

        result.passed = False

        result.errors.append(
            "Market column contains no valid values."
        )

        return

    invalid_market_rows = int(
        (
            values != expected_market.upper()
        ).sum()
    )

    if invalid_market_rows > 0:

        result.passed = False

        result.errors.append(
            "Market column does not match filename: "
            f"{invalid_market_rows:,} rows"
        )


# ============================================================
# FILE VALIDATION
# ============================================================

def validate_file(
    timeframe: str,
    path: Path,
) -> FileValidationResult:

    result = FileValidationResult(
        timeframe=timeframe,
        market=path.stem.upper(),
        path=path,
    )

    try:

        if not path.exists():

            result.passed = False

            result.errors.append(
                "File does not exist."
            )

            return result

        if path.stat().st_size == 0:

            result.passed = False

            result.errors.append(
                "File is empty."
            )

            return result

        try:

            df = pd.read_csv(
                path,
                low_memory=False,
            )

        except Exception as exc:

            result.passed = False

            result.errors.append(
                "CSV read failed: "
                f"{type(exc).__name__}: {exc}"
            )

            return result

        result.row_count = len(df)

        if result.row_count == 0:

            result.passed = False

            result.errors.append(
                "CSV contains zero rows."
            )

            return result

        if len(df.columns) == 0:

            result.passed = False

            result.errors.append(
                "CSV contains zero columns."
            )

            return result

        validate_timestamp(
            df=df,
            result=result,
        )

        required_columns = (
            validate_required_columns(
                df=df,
                result=result,
            )
        )

        numeric = validate_numeric_columns(
            df=df,
            columns=required_columns,
            result=result,
        )

        validate_ohlc_logic(
            numeric=numeric,
            result=result,
        )

        validate_market_column(
            df=df,
            expected_market=path.stem.upper(),
            result=result,
        )

    except Exception as exc:

        result.passed = False

        result.errors.append(
            "Unexpected validation error: "
            f"{type(exc).__name__}: {exc}"
        )

    return result


# ============================================================
# TIMEFRAME VALIDATION
# ============================================================

def validate_timeframe(
    timeframe: str,
    directory: Path,
    current_markets: set[str],
    enforce_current_coverage: bool,
) -> TimeframeValidationResult:

    result = TimeframeValidationResult(
        timeframe=timeframe,
        directory=directory,
    )

    print()
    print_separator("-")
    print(
        f"VALIDATING TIMEFRAME: "
        f"{timeframe.upper()}"
    )
    print_separator("-")

    print(
        f"Directory       : {directory}"
    )

    if not directory.exists():

        result.errors.append(
            f"Directory not found: {directory}"
        )

        print(
            "[FAIL] Directory not found."
        )

        return result

    if not directory.is_dir():

        result.errors.append(
            f"Path is not a directory: {directory}"
        )

        print(
            "[FAIL] Path is not a directory."
        )

        return result

    result.directory_exists = True

    files = sorted(
        directory.glob("*.csv"),
        key=lambda item: item.name.upper(),
    )

    result.file_count = len(files)

    stored_markets = {
        path.stem.upper()
        for path in files
    }

    result.missing_current_markets = sorted(
        current_markets - stored_markets
    )

    result.historical_markets = sorted(
        stored_markets - current_markets
    )

    result.current_market_file_count = len(
        stored_markets & current_markets
    )

    result.historical_file_count = len(
        result.historical_markets
    )

    print(
        f"CSV files       : {result.file_count:,}"
    )

    print(
        f"Current markets : "
        f"{len(current_markets):,}"
    )

    print(
        f"Current files   : "
        f"{result.current_market_file_count:,}"
    )

    print(
        f"Historical files: "
        f"{result.historical_file_count:,}"
    )

    if result.missing_current_markets:

        if enforce_current_coverage:
            result.errors.append(
                "Missing current KRW market CSV files: "
                f"{len(result.missing_current_markets):,}"
            )
            print(
                "[FAIL] Missing current KRW market files: "
                f"{len(result.missing_current_markets):,}"
            )
        else:
            result.warnings.append(
                "Current KRW market CSV files not yet present: "
                f"{len(result.missing_current_markets):,}"
            )
            print(
                "[INFO] PRE mode - current KRW market files "
                "not yet present: "
                f"{len(result.missing_current_markets):,}"
            )

        for market in result.missing_current_markets:
            print(f"    [MISSING] {market}")

    else:

        print(
            "[PASS] Every current KRW market "
            "has a CSV file."
        )

    if result.historical_markets:

        result.warnings.append(
            "Historical/non-current market CSV files: "
            f"{len(result.historical_markets):,}"
        )

        print(
            "[INFO] Historical/non-current CSV files "
            "are preserved:"
        )

        for market in result.historical_markets:

            print(
                f"    [HISTORICAL] {market}"
            )

    if not files:

        result.errors.append(
            "No CSV files found."
        )

        print(
            "[FAIL] No CSV files found."
        )

        return result

    total_files = len(files)

    print()
    print(
        "Validating individual CSV files..."
    )
    print()

    for index, path in enumerate(
        files,
        start=1,
    ):

        file_result = validate_file(
            timeframe=timeframe,
            path=path,
        )

        result.files.append(
            file_result
        )

        result.total_rows += (
            file_result.row_count
        )

        if file_result.passed:

            result.passed_files += 1
            status = "OK"

        else:

            result.failed_files += 1
            status = "FAIL"

        market_type = (
            "CURRENT"
            if file_result.market in current_markets
            else "HIST"
        )

        print(
            f"[{index:03d}/{total_files:03d}] "
            f"{path.stem:<18} "
            f"{status:<4} "
            f"{market_type:<7} "
            f"rows={file_result.row_count:,}"
        )

        if not file_result.passed:

            for error in file_result.errors:

                print(
                    f"    [ERROR] {error}"
                )

        for warning in file_result.warnings:

            print(
                f"    [WARN ] {warning}"
            )

    print()
    print(
        f"[{timeframe.upper()}] "
        f"files={result.file_count:,} | "
        f"current={result.current_market_file_count:,} | "
        f"historical={result.historical_file_count:,} | "
        f"passed={result.passed_files:,} | "
        f"failed={result.failed_files:,} | "
        f"rows={result.total_rows:,}"
    )

    return result


# ============================================================
# MARKET SET HELPERS
# ============================================================

def get_market_names(
    timeframe_result: TimeframeValidationResult,
) -> set[str]:

    return {
        item.market.upper()
        for item in timeframe_result.files
    }


def compare_market_sets(
    results: dict[str, TimeframeValidationResult],
) -> list[str]:

    errors: list[str] = []

    required_timeframes = (
        "h1",
        "h4",
        "d1",
    )

    if not all(
        timeframe in results
        for timeframe in required_timeframes
    ):

        errors.append(
            "Cannot compare market sets because "
            "one or more timeframe results are missing."
        )

        return errors

    h1_markets = get_market_names(
        results["h1"]
    )

    h4_markets = get_market_names(
        results["h4"]
    )

    d1_markets = get_market_names(
        results["d1"]
    )

    all_markets = (
        h1_markets
        | h4_markets
        | d1_markets
    )

    for market in sorted(all_markets):

        missing_from: list[str] = []

        if market not in h1_markets:
            missing_from.append("h1")

        if market not in h4_markets:
            missing_from.append("h4")

        if market not in d1_markets:
            missing_from.append("d1")

        if missing_from:

            errors.append(
                f"{market} missing from: "
                + ", ".join(missing_from)
            )

    return errors


# ============================================================
# CURRENT MARKET COVERAGE
# ============================================================

def validate_current_market_coverage(
    results: dict[str, TimeframeValidationResult],
    current_markets: set[str],
    mode: str,
) -> tuple[list[str], list[str]]:
    """
    Validate current-market coverage.

    PRE mode:
        - A current market missing from ALL h1/h4/d1 is treated as a
          newly listed market and is allowed to proceed to backfill.
        - A market present in only some timeframes is an error because
          that indicates partial/inconsistent stored data.

    POST mode:
        - Every current market must exist in all h1/h4/d1.

    Returns:
        (errors, allowed_new_markets)
    """

    errors: list[str] = []
    allowed_new_markets: list[str] = []

    required_timeframes = ("h1", "h4", "d1")

    stored_by_timeframe: dict[str, set[str]] = {}

    for timeframe in required_timeframes:
        result = results.get(timeframe)
        if result is None:
            errors.append(f"{timeframe}: validation result missing")
            stored_by_timeframe[timeframe] = set()
            continue
        stored_by_timeframe[timeframe] = get_market_names(result)

    for market in sorted(current_markets):
        present_in = [
            timeframe
            for timeframe in required_timeframes
            if market in stored_by_timeframe[timeframe]
        ]
        missing_from = [
            timeframe
            for timeframe in required_timeframes
            if market not in stored_by_timeframe[timeframe]
        ]

        if not missing_from:
            continue

        if mode == "pre" and not present_in:
            allowed_new_markets.append(market)
            continue

        errors.append(
            f"{market}: missing from {', '.join(missing_from)}"
        )

    return errors, allowed_new_markets


# ============================================================
# REPORT HELPERS
# ============================================================

def collect_failed_files(
    results: dict[str, TimeframeValidationResult],
) -> list[FileValidationResult]:

    failed: list[FileValidationResult] = []

    for timeframe_result in results.values():

        for file_result in timeframe_result.files:

            if not file_result.passed:

                failed.append(
                    file_result
                )

    return failed


def calculate_total_files(
    results: dict[str, TimeframeValidationResult],
) -> int:

    return sum(
        result.file_count
        for result in results.values()
    )


def calculate_total_rows(
    results: dict[str, TimeframeValidationResult],
) -> int:

    return sum(
        result.total_rows
        for result in results.values()
    )


def calculate_passed_files(
    results: dict[str, TimeframeValidationResult],
) -> int:

    return sum(
        result.passed_files
        for result in results.values()
    )


def calculate_failed_files(
    results: dict[str, TimeframeValidationResult],
) -> int:

    return sum(
        result.failed_files
        for result in results.values()
    )


def calculate_historical_files(
    results: dict[str, TimeframeValidationResult],
) -> int:

    return sum(
        result.historical_file_count
        for result in results.values()
    )


def print_timeframe_summary(
    results: dict[str, TimeframeValidationResult],
    current_market_count: int,
) -> None:

    print()
    print_separator("-")
    print("TIMEFRAME SUMMARY")
    print_separator("-")

    print(
        f"{'TF':<6}"
        f"{'FILES':>10}"
        f"{'CURRENT':>10}"
        f"{'EXPECTED':>10}"
        f"{'HIST':>8}"
        f"{'PASSED':>10}"
        f"{'FAILED':>10}"
        f"{'ROWS':>16}"
    )

    print_separator("-", 80)

    for timeframe in (
        "h1",
        "h4",
        "d1",
    ):

        result = results[timeframe]

        print(
            f"{timeframe.upper():<6}"
            f"{result.file_count:>10,}"
            f"{result.current_market_file_count:>10,}"
            f"{current_market_count:>10,}"
            f"{result.historical_file_count:>8,}"
            f"{result.passed_files:>10,}"
            f"{result.failed_files:>10,}"
            f"{result.total_rows:>16,}"
        )


def print_failed_file_summary(
    failed_files: list[FileValidationResult],
) -> None:

    if not failed_files:
        return

    print()
    print_separator("-")
    print("FAILED FILES")
    print_separator("-")

    for result in failed_files:

        print(
            f"[{result.timeframe.upper()}] "
            f"{result.market}"
        )

        print(
            f"  Path : {result.path}"
        )

        for error in result.errors:

            print(
                f"  ERROR: {error}"
            )

        for warning in result.warnings:

            print(
                f"  WARN : {warning}"
            )


def print_historical_market_summary(
    results: dict[str, TimeframeValidationResult],
) -> None:

    historical_union: set[str] = set()

    for result in results.values():

        historical_union.update(
            result.historical_markets
        )

    if not historical_union:
        return

    print()
    print_separator("-")
    print("HISTORICAL / NON-CURRENT MARKETS")
    print_separator("-")

    print(
        "These CSV files are preserved intentionally."
    )

    print(
        "They are not part of the current Upbit KRW "
        "market list and are NOT treated as validation errors."
    )

    print()

    for market in sorted(
        historical_union
    ):

        present_in: list[str] = []

        for timeframe in (
            "h1",
            "h4",
            "d1",
        ):

            result = results[
                timeframe
            ]

            markets = get_market_names(
                result
            )

            if market in markets:

                present_in.append(
                    timeframe
                )

        print(
            f"  {market:<18} "
            f"stored in: "
            f"{', '.join(present_in)}"
        )


# ============================================================
# COMMAND-LINE MODE
# ============================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate collector OHLCV data before or after backfill."
    )
    parser.add_argument(
        "--mode",
        choices=("pre", "post"),
        default="post",
        help=(
            "pre: allow markets missing from all h1/h4/d1 so backfill can create them; "
            "post: require complete current-market coverage"
        ),
    )
    return parser.parse_args()


# ============================================================
# MAIN VALIDATION
# ============================================================

def main() -> int:

    args = parse_args()
    validation_mode = args.mode.lower()

    print_header(
        "UPBIT SURGE MONITOR - "
        "COLLECTOR DATA VALIDATOR"
    )

    print(
        f"Project root       : {BASE_DIR}"
    )

    print(
        f"Data directory     : {DATA_DIR}"
    )

    print(
        f"OHLCV directory    : {OHLCV_DIR}"
    )

    print(
        "Timeframes         : h1 / h4 / d1"
    )

    print()
    print(
        f"Validation mode    : {validation_mode.upper()}"
    )

    print(
        "Mode               : READ ONLY"
    )

    print(
        "Source modification: DISABLED"
    )

    print(
        "Historical deletion: DISABLED"
    )

    # --------------------------------------------------------
    # LOAD CURRENT UPBIT KRW MARKET LIST
    # --------------------------------------------------------

    print()
    print_separator("-")
    print("CURRENT UPBIT KRW MARKET LIST")
    print_separator("-")

    try:

        current_market_list = (
            get_current_krw_markets()
        )

    except Exception as exc:

        print(
            "[FATAL] Failed to load current "
            "Upbit KRW market list."
        )

        print(
            f"{type(exc).__name__}: {exc}"
        )

        print_separator("=")

        return 1

    current_markets = set(
        current_market_list
    )

    print(
        "[PASS] Current Upbit KRW "
        "market list loaded."
    )

    print(
        f"Current KRW markets: "
        f"{len(current_markets):,}"
    )

    # --------------------------------------------------------
    # VERIFY BASE DIRECTORIES
    # --------------------------------------------------------

    if not DATA_DIR.exists():

        print()
        print(
            f"[FAIL] Data directory "
            f"not found: {DATA_DIR}"
        )

        return 1

    if not OHLCV_DIR.exists():

        print()
        print(
            f"[FAIL] OHLCV directory "
            f"not found: {OHLCV_DIR}"
        )

        return 1

    # --------------------------------------------------------
    # VALIDATE TIMEFRAMES
    # --------------------------------------------------------

    overall_errors: list[str] = []

    results: dict[
        str,
        TimeframeValidationResult,
    ] = {}

    for timeframe in (
        "h1",
        "h4",
        "d1",
    ):

        results[timeframe] = (
            validate_timeframe(
                timeframe=timeframe,
                directory=TIMEFRAME_DIRS[
                    timeframe
                ],
                current_markets=current_markets,
                enforce_current_coverage=(validation_mode == "post"),
            )
        )

    # --------------------------------------------------------
    # DIRECTORY / FILE VALIDATION RESULTS
    # --------------------------------------------------------

    for timeframe, result in results.items():

        if not result.directory_exists:

            overall_errors.append(
                f"{timeframe}: directory missing"
            )

        if (
            validation_mode == "post"
            and result.missing_current_markets
        ):
            overall_errors.append(
                f"{timeframe}: "
                f"{len(result.missing_current_markets):,} "
                "current KRW market files missing"
            )

        if result.failed_files > 0:

            overall_errors.append(
                f"{timeframe}: "
                f"{result.failed_files:,} "
                "invalid CSV files"
            )

    # --------------------------------------------------------
    # CURRENT MARKET COVERAGE
    # --------------------------------------------------------

    print()
    print_separator("-")
    print("CURRENT MARKET COVERAGE CHECK")
    print_separator("-")

    coverage_errors, allowed_new_markets = (
        validate_current_market_coverage(
            results=results,
            current_markets=current_markets,
            mode=validation_mode,
        )
    )

    if coverage_errors:

        print(
            "[FAIL] Current KRW market "
            "coverage problems: "
            f"{len(coverage_errors):,}"
        )

        for error in coverage_errors:

            print(
                f"  {error}"
            )

        overall_errors.extend(
            coverage_errors
        )

    else:

        if validation_mode == "pre" and allowed_new_markets:
            print(
                "[PASS] PRE mode accepted completely missing "
                "new current markets for backfill."
            )
            for market in allowed_new_markets:
                print(f"  [NEW MARKET] {market} -> h1/h4/d1 will be created by backfill")
        else:
            print(
                "[PASS] Every current Upbit KRW "
                "market exists in h1 / h4 / d1."
            )

    # --------------------------------------------------------
    # CROSS-TIMEFRAME MARKET SET
    # --------------------------------------------------------

    print()
    print_separator("-")
    print("CROSS-TIMEFRAME MARKET CHECK")
    print_separator("-")

    market_errors = compare_market_sets(
        results
    )

    if market_errors:

        print(
            "[FAIL] Market-set differences: "
            f"{len(market_errors):,}"
        )

        for error in market_errors:

            print(
                f"  {error}"
            )

        overall_errors.extend(
            market_errors
        )

    else:

        print(
            "[PASS] h1 / h4 / d1 contain "
            "the same stored market set."
        )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print_timeframe_summary(
        results=results,
        current_market_count=len(
            current_markets
        ),
    )

    failed_files = collect_failed_files(
        results
    )

    print_failed_file_summary(
        failed_files
    )

    print_historical_market_summary(
        results
    )

    total_files = calculate_total_files(
        results
    )

    total_rows = calculate_total_rows(
        results
    )

    passed_files = calculate_passed_files(
        results
    )

    failed_file_count = (
        calculate_failed_files(
            results
        )
    )

    historical_file_count = (
        calculate_historical_files(
            results
        )
    )

    print()
    print_separator("=")
    print("VALIDATION SUMMARY")
    print_separator("=")

    print(
        f"Project              : "
        f"{PROJECT_NAME}"
    )

    print(
        f"Version              : "
        f"{VERSION}"
    )

    print(
        f"Validation mode      : "
        f"{validation_mode.upper()}"
    )

    print(
        f"Current KRW markets  : "
        f"{len(current_markets):,}"
    )

    print(
        f"Expected active files: "
        f"{len(current_markets) * 3:,}"
    )

    print(
        f"Actual stored files  : "
        f"{total_files:,}"
    )

    print(
        f"Historical file refs : "
        f"{historical_file_count:,}"
    )

    print(
        f"Passed files         : "
        f"{passed_files:,}"
    )

    print(
        f"Failed files         : "
        f"{failed_file_count:,}"
    )

    print(
        f"Total OHLCV rows     : "
        f"{total_rows:,}"
    )

    print(
        f"Cross-market errors  : "
        f"{len(market_errors):,}"
    )

    print(
        f"Coverage errors      : "
        f"{len(coverage_errors):,}"
    )

    print(
        f"PRE allowed new mkts : "
        f"{len(allowed_new_markets):,}"
    )

    print(
        f"Overall errors       : "
        f"{len(overall_errors):,}"
    )

    print_separator("=")

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    if overall_errors:

        print(
            "[RESULT] COLLECTOR VALIDATION FAILED"
        )

        print()
        print(
            "Detected problems:"
        )

        for index, error in enumerate(
            overall_errors,
            start=1,
        ):

            print(
                f"  {index:03d}. {error}"
            )

        print_separator("=")

        return 1

    print(
        "[RESULT] COLLECTOR VALIDATION PASSED"
    )

    if validation_mode == "pre" and allowed_new_markets:
        print(
            "[PASS] Existing OHLCV data is valid enough to start backfill."
        )
        print(
            f"[INFO] {len(allowed_new_markets):,} completely missing current "
            "market(s) will be created by backfill."
        )
    else:
        print(
            "[PASS] All current Upbit KRW markets "
            "exist in h1 / h4 / d1."
        )

    print(
        "[PASS] All stored OHLCV CSV files "
        "passed validation."
    )

    if historical_file_count > 0:

        print(
            "[INFO] Historical/non-current "
            "market data was preserved."
        )

    print_separator("=")

    return 0


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    try:

        exit_code = main()

    except KeyboardInterrupt:

        print()
        print(
            "[STOP] Validation interrupted "
            "by user."
        )

        exit_code = 130

    except Exception as exc:

        print()
        print_separator("=")
        print(
            "VALIDATOR FATAL ERROR"
        )
        print_separator("=")

        print(
            f"{type(exc).__name__}: {exc}"
        )

        print_separator("=")

        exit_code = 1

    sys.exit(exit_code)
