"""
Upbit Surge Monitor
256 Detector Output Validator

Version:
    Clean V003

File:
    validate_256.py

Purpose:
    Validate ALL KRW-market output generated by detect_256.py.

Clean V003:
    - Full KRW market validation
    - Automatic market discovery
    - h1 / h4 / d1 validation
    - Resume / checkpoint support
    - Input SHA256-aware resume
    - Failed jobs are never marked completed
    - Source OHLCV / Feature / Signal files are READ ONLY
    - No future labels
    - No prediction
    - No trading

Official detector states:
    signal_setup
    signal_ready
    signal_trigger

Important:
    This validator is READ ONLY.

Windows:
    py validate_256.py
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import os
import sys
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Upbit Surge Monitor"
VALIDATOR_NAME = "256 Validator Clean V003"
VERSION = "Clean V003"

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
OHLCV_DIR = DATA_DIR / "ohlcv"
FEATURE_DIR = DATA_DIR / "features"
SIGNAL_DIR = DATA_DIR / "signals" / "256"

TIMEFRAMES = ("h1", "h4", "d1")

CHECKPOINT_DIR = DATA_DIR / "validation"
CHECKPOINT_PATH = CHECKPOINT_DIR / "validate_256_checkpoint.json"
STATUS_PATH = DATA_DIR / "validate_256_status.csv"

CHECKPOINT_VERSION = 1

TIMESTAMP_CANDIDATES = (
    "timestamp",
    "candle_date_time_utc",
    "datetime",
    "candle_date_time_kst",
)

REQUIRED_OHLC_COLUMNS = (
    "open",
    "high",
    "low",
    "close",
    "volume",
)

OFFICIAL_STATE_COLUMNS = (
    "signal_setup",
    "signal_ready",
    "signal_trigger",
)

SCORE_COLUMNS = (
    "setup_score",
    "ready_score",
    "trigger_score",
)

MA_PREFIXES = (
    "ma",
    "sma",
    "ema",
)

FORBIDDEN_FUTURE_PATTERNS = (
    "future_",
    "future-",
    "future ",
    "next_",
    "next-",
    "next ",
    "forward_",
    "forward-",
    "forward ",
    "target",
    "label",
    "outcome",
)

ALLOWED_NEXT_COLUMNS: set[str] = set()

TRUE_VALUES = {
    "1",
    "1.0",
    "true",
    "t",
    "yes",
    "y",
}

FALSE_VALUES = {
    "0",
    "0.0",
    "false",
    "f",
    "no",
    "n",
    "",
    "nan",
    "none",
    "null",
}


# ============================================================
# RESULT MODEL
# ============================================================

@dataclass
class ValidationResult:
    market: str
    timeframe: str

    ohlcv_path: Path
    feature_path: Path
    signal_path: Path

    passed: bool = True

    ohlcv_rows: int = 0
    feature_rows: int = 0
    signal_rows: int = 0

    setup_count: int = 0
    ready_count: int = 0
    trigger_count: int = 0

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    elapsed_seconds: float = 0.0

    skipped_resume: bool = False

    def fail(self, message: str) -> None:
        self.passed = False
        self.errors.append(message)
        print(f"[FAIL] {message}")

    def warn(self, message: str) -> None:
        self.warnings.append(message)
        print(f"[WARN] {message}")

    def passed_message(self, message: str) -> None:
        print(f"[PASS] {message}")


# ============================================================
# BASIC HELPERS
# ============================================================

def separator(char: str = "-", length: int = 72) -> None:
    print(char * length)


def utc_now_text() -> str:
    return datetime.now(timezone.utc).isoformat()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as file:
        while True:
            block = file.read(1024 * 1024)

            if not block:
                break

            digest.update(block)

    return digest.hexdigest()


def file_size_text(path: Path) -> str:
    try:
        return f"{path.stat().st_size:,} bytes"
    except Exception:
        return "unknown size"


def find_timestamp_column(df: pd.DataFrame) -> str | None:
    columns = {
        str(column).strip(): column
        for column in df.columns
    }

    for candidate in TIMESTAMP_CANDIDATES:
        if candidate in columns:
            return columns[candidate]

    return None


def atomic_write_json(
    path: Path,
    payload: dict[str, Any],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    temporary_path = path.with_suffix(
        path.suffix + ".tmp"
    )

    with temporary_path.open(
        "w",
        encoding="utf-8",
        newline="\n",
    ) as file:
        json.dump(
            payload,
            file,
            ensure_ascii=False,
            indent=2,
        )

        file.flush()
        os.fsync(file.fileno())

    os.replace(
        temporary_path,
        path,
    )


# ============================================================
# MARKET DISCOVERY
# ============================================================

def csv_markets(directory: Path) -> set[str]:
    if not directory.exists():
        return set()

    return {
        path.stem
        for path in directory.glob("KRW-*.csv")
        if path.is_file()
    }


def discover_markets() -> list[str]:
    """
    A market is considered valid for the full validator only
    when OHLCV / Feature / Signal files exist for ALL configured
    timeframes.

    We also report incomplete markets separately.
    """

    all_seen: set[str] = set()

    directory_sets: dict[str, set[str]] = {}

    for timeframe in TIMEFRAMES:
        for label, base_dir in (
            ("ohlcv", OHLCV_DIR),
            ("feature", FEATURE_DIR),
            ("signal", SIGNAL_DIR),
        ):
            key = f"{label}:{timeframe}"

            markets = csv_markets(
                base_dir / timeframe
            )

            directory_sets[key] = markets
            all_seen.update(markets)

    complete: list[str] = []

    for market in sorted(all_seen):
        exists_everywhere = True

        for timeframe in TIMEFRAMES:
            for label in (
                "ohlcv",
                "feature",
                "signal",
            ):
                key = f"{label}:{timeframe}"

                if market not in directory_sets[key]:
                    exists_everywhere = False
                    break

            if not exists_everywhere:
                break

        if exists_everywhere:
            complete.append(market)

    return complete


def discover_incomplete_markets(
    complete_markets: list[str],
) -> list[str]:
    complete_set = set(complete_markets)
    all_seen: set[str] = set()

    for timeframe in TIMEFRAMES:
        all_seen.update(
            csv_markets(
                OHLCV_DIR / timeframe
            )
        )
        all_seen.update(
            csv_markets(
                FEATURE_DIR / timeframe
            )
        )
        all_seen.update(
            csv_markets(
                SIGNAL_DIR / timeframe
            )
        )

    return sorted(
        all_seen - complete_set
    )


# ============================================================
# CHECKPOINT / RESUME
# ============================================================

def empty_checkpoint() -> dict[str, Any]:
    return {
        "checkpoint_version": CHECKPOINT_VERSION,
        "project": PROJECT_NAME,
        "validator": VALIDATOR_NAME,
        "validator_version": VERSION,
        "updated_utc": utc_now_text(),
        "completed": {},
    }


def load_checkpoint() -> dict[str, Any]:
    if not CHECKPOINT_PATH.exists():
        print(
            "[INFO] No previous validator checkpoint found."
        )
        return empty_checkpoint()

    try:
        with CHECKPOINT_PATH.open(
            "r",
            encoding="utf-8",
        ) as file:
            checkpoint = json.load(file)

    except Exception as exc:
        print(
            "[WARN] Previous checkpoint could not be read:"
        )
        print(
            f"       {type(exc).__name__}: {exc}"
        )
        print(
            "[WARN] Starting validation without trusting "
            "the old checkpoint."
        )

        return empty_checkpoint()

    if not isinstance(checkpoint, dict):
        print(
            "[WARN] Invalid checkpoint structure. "
            "Starting fresh."
        )
        return empty_checkpoint()

    if (
        checkpoint.get("checkpoint_version")
        != CHECKPOINT_VERSION
    ):
        print(
            "[WARN] Checkpoint version mismatch. "
            "Starting fresh."
        )
        return empty_checkpoint()

    completed = checkpoint.get("completed")

    if not isinstance(completed, dict):
        checkpoint["completed"] = {}

    print(
        "[PASS] Previous validator checkpoint loaded."
    )
    print(
        f"       Completed records: "
        f"{len(checkpoint['completed']):,}"
    )

    return checkpoint


def save_checkpoint(
    checkpoint: dict[str, Any],
) -> None:
    checkpoint["updated_utc"] = utc_now_text()

    atomic_write_json(
        CHECKPOINT_PATH,
        checkpoint,
    )


def job_key(
    market: str,
    timeframe: str,
) -> str:
    return f"{market}|{timeframe}"


def get_job_paths(
    market: str,
    timeframe: str,
) -> tuple[Path, Path, Path]:
    return (
        OHLCV_DIR
        / timeframe
        / f"{market}.csv",

        FEATURE_DIR
        / timeframe
        / f"{market}.csv",

        SIGNAL_DIR
        / timeframe
        / f"{market}.csv",
    )


def current_input_hashes(
    market: str,
    timeframe: str,
) -> dict[str, str] | None:
    ohlcv_path, feature_path, signal_path = (
        get_job_paths(
            market,
            timeframe,
        )
    )

    paths = {
        "ohlcv_sha256": ohlcv_path,
        "feature_sha256": feature_path,
        "signal_sha256": signal_path,
    }

    hashes: dict[str, str] = {}

    for key, path in paths.items():
        if not path.exists() or not path.is_file():
            return None

        try:
            hashes[key] = file_sha256(path)
        except Exception:
            return None

    return hashes


def checkpoint_job_is_current(
    checkpoint: dict[str, Any],
    market: str,
    timeframe: str,
) -> tuple[bool, dict[str, Any] | None]:
    key = job_key(
        market,
        timeframe,
    )

    record = checkpoint.get(
        "completed",
        {},
    ).get(key)

    if not isinstance(record, dict):
        return False, None

    if record.get("passed") is not True:
        return False, None

    current_hashes = current_input_hashes(
        market,
        timeframe,
    )

    if current_hashes is None:
        return False, None

    for hash_key, current_hash in current_hashes.items():
        if record.get(hash_key) != current_hash:
            print(
                f"[RESUME] {market} {timeframe}: "
                f"input changed -> revalidate"
            )
            return False, None

    return True, record


def result_from_checkpoint(
    market: str,
    timeframe: str,
    record: dict[str, Any],
) -> ValidationResult:
    ohlcv_path, feature_path, signal_path = (
        get_job_paths(
            market,
            timeframe,
        )
    )

    return ValidationResult(
        market=market,
        timeframe=timeframe,
        ohlcv_path=ohlcv_path,
        feature_path=feature_path,
        signal_path=signal_path,
        passed=True,
        ohlcv_rows=int(
            record.get("ohlcv_rows", 0)
        ),
        feature_rows=int(
            record.get("feature_rows", 0)
        ),
        signal_rows=int(
            record.get("signal_rows", 0)
        ),
        setup_count=int(
            record.get("setup_count", 0)
        ),
        ready_count=int(
            record.get("ready_count", 0)
        ),
        trigger_count=int(
            record.get("trigger_count", 0)
        ),
        elapsed_seconds=0.0,
        skipped_resume=True,
    )


def mark_checkpoint_passed(
    checkpoint: dict[str, Any],
    result: ValidationResult,
) -> None:
    hashes = current_input_hashes(
        result.market,
        result.timeframe,
    )

    if hashes is None:
        print(
            "[WARN] Could not create resume record because "
            "input hashes were unavailable."
        )
        return

    key = job_key(
        result.market,
        result.timeframe,
    )

    checkpoint.setdefault(
        "completed",
        {},
    )[key] = {
        "market": result.market,
        "timeframe": result.timeframe,
        "passed": True,
        "completed_utc": utc_now_text(),
        "ohlcv_rows": result.ohlcv_rows,
        "feature_rows": result.feature_rows,
        "signal_rows": result.signal_rows,
        "setup_count": result.setup_count,
        "ready_count": result.ready_count,
        "trigger_count": result.trigger_count,
        **hashes,
    }

    save_checkpoint(checkpoint)


def remove_failed_checkpoint_record(
    checkpoint: dict[str, Any],
    market: str,
    timeframe: str,
) -> None:
    key = job_key(
        market,
        timeframe,
    )

    completed = checkpoint.setdefault(
        "completed",
        {},
    )

    if key in completed:
        del completed[key]
        save_checkpoint(checkpoint)


# ============================================================
# CSV READ
# ============================================================

def safe_read_csv(
    path: Path,
    label: str,
    result: ValidationResult,
) -> pd.DataFrame | None:
    if not path.exists():
        result.fail(
            f"{label} file does not exist: {path}"
        )
        return None

    if not path.is_file():
        result.fail(
            f"{label} path is not a file: {path}"
        )
        return None

    result.passed_message(
        f"{label} file exists "
        f"({file_size_text(path)})"
    )

    try:
        df = pd.read_csv(
            path,
            low_memory=False,
        )

    except Exception as exc:
        result.fail(
            f"{label} CSV read failed: "
            f"{type(exc).__name__}: {exc}"
        )
        return None

    result.passed_message(
        f"{label} dataframe rows={len(df):,}, "
        f"columns={len(df.columns):,}"
    )

    return df


# ============================================================
# TIMESTAMP PARSER
# ============================================================

def _numeric_timestamp_to_datetime(
    numeric: pd.Series,
) -> pd.Series:
    result = pd.Series(
        pd.NaT,
        index=numeric.index,
        dtype="datetime64[ns, UTC]",
    )

    valid = numeric.notna()

    if not valid.any():
        return result

    absolute = numeric.abs()

    seconds = (
        valid
        & (absolute < 1.0e11)
    )

    milliseconds = (
        valid
        & (absolute >= 1.0e11)
        & (absolute < 1.0e14)
    )

    microseconds = (
        valid
        & (absolute >= 1.0e14)
        & (absolute < 1.0e17)
    )

    nanoseconds = (
        valid
        & (absolute >= 1.0e17)
    )

    if seconds.any():
        result.loc[seconds] = pd.to_datetime(
            numeric.loc[seconds],
            unit="s",
            utc=True,
            errors="coerce",
        )

    if milliseconds.any():
        result.loc[milliseconds] = pd.to_datetime(
            numeric.loc[milliseconds],
            unit="ms",
            utc=True,
            errors="coerce",
        )

    if microseconds.any():
        result.loc[microseconds] = pd.to_datetime(
            numeric.loc[microseconds],
            unit="us",
            utc=True,
            errors="coerce",
        )

    if nanoseconds.any():
        result.loc[nanoseconds] = pd.to_datetime(
            numeric.loc[nanoseconds],
            unit="ns",
            utc=True,
            errors="coerce",
        )

    return result


def parse_timestamp_series(
    series: pd.Series,
) -> pd.Series:
    output = pd.Series(
        pd.NaT,
        index=series.index,
        dtype="datetime64[ns, UTC]",
    )

    if len(series) == 0:
        return output

    raw = series.copy()

    numeric = pd.to_numeric(
        raw,
        errors="coerce",
    )

    numeric_mask = numeric.notna()

    if numeric_mask.any():
        parsed_numeric = (
            _numeric_timestamp_to_datetime(
                numeric
            )
        )

        output.loc[numeric_mask] = (
            parsed_numeric.loc[numeric_mask]
        )

    remaining = (
        output.isna()
        & raw.notna()
    )

    if remaining.any():
        strings = (
            raw.loc[remaining]
            .astype(str)
            .str.strip()
        )

        strings = strings.replace(
            {
                "": np.nan,
                "nan": np.nan,
                "NaN": np.nan,
                "None": np.nan,
                "null": np.nan,
                "NULL": np.nan,
            }
        )

        parsed_strings = pd.to_datetime(
            strings,
            utc=True,
            errors="coerce",
        )

        output.loc[remaining] = parsed_strings

    return output


# ============================================================
# COLUMN VALIDATION
# ============================================================

def validate_unique_columns(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> None:
    duplicated = (
        pd.Index(df.columns)
        .duplicated(keep=False)
    )

    if duplicated.any():
        duplicates = (
            pd.Index(df.columns)[duplicated]
            .astype(str)
            .tolist()
        )

        result.fail(
            f"{label} duplicate column names: "
            f"{duplicates}"
        )
        return

    result.passed_message(
        f"{label} column names are unique."
    )


def validate_required_ohlc_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    missing = [
        column
        for column in REQUIRED_OHLC_COLUMNS
        if column not in df.columns
    ]

    if missing:
        result.fail(
            "OHLCV missing required columns: "
            + ", ".join(missing)
        )
        return

    result.passed_message(
        "OHLCV required OHLCV columns are present."
    )


# ============================================================
# TIMESTAMP VALIDATION
# ============================================================

def validate_timestamp_integrity(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> tuple[str | None, pd.Series | None]:
    timestamp_column = find_timestamp_column(df)

    if timestamp_column is None:
        result.fail(
            f"{label} has no supported timestamp column. "
            f"Expected one of: {TIMESTAMP_CANDIDATES}"
        )
        return None, None

    parsed = parse_timestamp_series(
        df[timestamp_column]
    )

    failures = int(
        parsed.isna().sum()
    )

    if failures:
        result.fail(
            f"{label} timestamp parse failures="
            f"{failures:,}"
        )
    else:
        result.passed_message(
            f"{label} timestamps parsed successfully."
        )

    valid = parsed.dropna()

    duplicates = int(
        valid.duplicated(
            keep=False
        ).sum()
    )

    if duplicates:
        result.fail(
            f"{label} duplicate timestamps="
            f"{duplicates:,}"
        )
    else:
        result.passed_message(
            f"{label} timestamps are unique."
        )

    if len(valid) > 1:
        if valid.is_monotonic_increasing:
            result.passed_message(
                f"{label} timestamps are chronological."
            )
        else:
            result.fail(
                f"{label} timestamps are not chronological."
            )

    if len(valid):
        print(
            f"[INFO] {label} timestamp range: "
            f"{valid.iloc[0]} -> {valid.iloc[-1]}"
        )

    return timestamp_column, parsed


# ============================================================
# ROW / TIMESTAMP ALIGNMENT
# ============================================================

def validate_row_counts(
    ohlcv: pd.DataFrame,
    feature: pd.DataFrame,
    signal: pd.DataFrame,
    result: ValidationResult,
) -> None:
    result.ohlcv_rows = len(ohlcv)
    result.feature_rows = len(feature)
    result.signal_rows = len(signal)

    if (
        result.ohlcv_rows
        == result.feature_rows
        == result.signal_rows
    ):
        result.passed_message(
            "OHLCV / Feature / Signal row counts are 1:1 "
            f"({result.signal_rows:,} rows)."
        )
    else:
        result.fail(
            "OHLCV / Feature / Signal row-count mismatch: "
            f"OHLCV={result.ohlcv_rows:,}, "
            f"Feature={result.feature_rows:,}, "
            f"Signal={result.signal_rows:,}"
        )


def validate_timestamp_alignment(
    ohlcv_ts: pd.Series | None,
    feature_ts: pd.Series | None,
    signal_ts: pd.Series | None,
    result: ValidationResult,
) -> None:
    if (
        ohlcv_ts is None
        or feature_ts is None
        or signal_ts is None
    ):
        result.fail(
            "Timestamp alignment could not be checked."
        )
        return

    if not (
        len(ohlcv_ts)
        == len(feature_ts)
        == len(signal_ts)
    ):
        result.fail(
            "Timestamp alignment skipped because "
            "row counts differ."
        )
        return

    if (
        ohlcv_ts.isna().any()
        or feature_ts.isna().any()
        or signal_ts.isna().any()
    ):
        result.fail(
            "Timestamp alignment cannot pass while "
            "parsed timestamps contain NaT."
        )
        return

    ohlcv_reset = ohlcv_ts.reset_index(
        drop=True
    )

    feature_equal = bool(
        ohlcv_reset.equals(
            feature_ts.reset_index(drop=True)
        )
    )

    signal_equal = bool(
        ohlcv_reset.equals(
            signal_ts.reset_index(drop=True)
        )
    )

    if feature_equal:
        result.passed_message(
            "Feature timestamps match OHLCV 1:1."
        )
    else:
        result.fail(
            "Feature timestamps do not match OHLCV 1:1."
        )

    if signal_equal:
        result.passed_message(
            "Signal timestamps match OHLCV 1:1."
        )
    else:
        result.fail(
            "Signal timestamps do not match OHLCV 1:1."
        )


# ============================================================
# OHLCV VALIDATION
# ============================================================

def numeric_series(
    df: pd.DataFrame,
    column: str,
) -> pd.Series:
    return pd.to_numeric(
        df[column],
        errors="coerce",
    )


def validate_ohlcv_values(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    missing = [
        column
        for column in REQUIRED_OHLC_COLUMNS
        if column not in df.columns
    ]

    if missing:
        return

    numeric = {
        column: numeric_series(
            df,
            column,
        )
        for column in REQUIRED_OHLC_COLUMNS
    }

    for column, series in numeric.items():
        invalid = int(
            series.isna().sum()
        )

        if invalid:
            result.fail(
                f"OHLCV {column} invalid/NaN values="
                f"{invalid:,}"
            )
        else:
            result.passed_message(
                f"OHLCV {column} numeric values valid."
            )

        values = series.to_numpy(
            dtype=float,
            na_value=np.nan,
        )

        non_finite = int(
            (~np.isfinite(values)).sum()
        )

        if non_finite:
            result.fail(
                f"OHLCV {column} non-finite values="
                f"{non_finite:,}"
            )

    open_price = numeric["open"]
    high_price = numeric["high"]
    low_price = numeric["low"]
    close_price = numeric["close"]
    volume = numeric["volume"]

    invalid_positive = (
        (open_price <= 0)
        | (high_price <= 0)
        | (low_price <= 0)
        | (close_price <= 0)
    )

    count = int(
        invalid_positive
        .fillna(True)
        .sum()
    )

    if count:
        result.fail(
            f"OHLCV non-positive price rows={count:,}"
        )
    else:
        result.passed_message(
            "OHLCV prices are positive."
        )

    negative_volume = int(
        (volume < 0)
        .fillna(False)
        .sum()
    )

    if negative_volume:
        result.fail(
            "OHLCV negative volume rows="
            f"{negative_volume:,}"
        )
    else:
        result.passed_message(
            "OHLCV volume is non-negative."
        )

    high_invalid = (
        (high_price < open_price)
        | (high_price < close_price)
        | (high_price < low_price)
    )

    high_count = int(
        high_invalid
        .fillna(False)
        .sum()
    )

    if high_count:
        result.fail(
            "OHLCV high relationship violations="
            f"{high_count:,}"
        )
    else:
        result.passed_message(
            "OHLCV high relationships are valid."
        )

    low_invalid = (
        (low_price > open_price)
        | (low_price > close_price)
        | (low_price > high_price)
    )

    low_count = int(
        low_invalid
        .fillna(False)
        .sum()
    )

    if low_count:
        result.fail(
            "OHLCV low relationship violations="
            f"{low_count:,}"
        )
    else:
        result.passed_message(
            "OHLCV low relationships are valid."
        )


# ============================================================
# NUMERIC VALIDATION
# ============================================================

def validate_numeric_infinite_values(
    df: pd.DataFrame,
    label: str,
    result: ValidationResult,
) -> None:
    numeric_df = df.select_dtypes(
        include=[np.number]
    )

    if numeric_df.empty:
        result.passed_message(
            f"No numeric {label} columns require "
            "infinite-value inspection."
        )
        return

    values = numeric_df.to_numpy(
        dtype=float,
        copy=False,
    )

    infinite_count = int(
        np.isinf(values).sum()
    )

    if infinite_count:
        result.fail(
            f"{label} contains infinite numeric values="
            f"{infinite_count:,}"
        )
    else:
        result.passed_message(
            f"No infinite values found in numeric "
            f"{label} columns."
        )


# ============================================================
# MA VALIDATION
# ============================================================

def is_ma_column(column: str) -> bool:
    lower = column.lower()

    for prefix in MA_PREFIXES:
        if lower.startswith(
            prefix + "_"
        ):
            return True

        if lower == prefix:
            return True

    return False


def validate_ma_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    ma_columns = [
        str(column)
        for column in df.columns
        if is_ma_column(
            str(column)
        )
    ]

    if not ma_columns:
        result.warn(
            "No MA-prefixed columns found. "
            "MA validation skipped."
        )
        return

    failures = 0

    for column in ma_columns:
        series = pd.to_numeric(
            df[column],
            errors="coerce",
        )

        finite_values = series.dropna()

        # Important:
        # short-history markets can legitimately have an
        # entirely NaN SMA112/SMA224 warm-up column.
        if finite_values.empty:
            continue

        array = finite_values.to_numpy(
            dtype=float
        )

        infinite = int(
            np.isinf(array).sum()
        )

        if infinite:
            result.fail(
                f"MA column '{column}' infinite values="
                f"{infinite:,}"
            )
            failures += 1

    if failures == 0:
        result.passed_message(
            "MA columns passed finite-value validation."
        )


# ============================================================
# SCORE VALIDATION
# ============================================================

def validate_score_columns(
    df: pd.DataFrame,
    result: ValidationResult,
) -> None:
    found = [
        column
        for column in SCORE_COLUMNS
        if column in df.columns
    ]

    if not found:
        result.warn(
            "No expected score columns found."
        )
        return

    for column in found:
        series = pd.to_numeric(
            df[column],
            errors="coerce",
        )

        invalid = int(
            series.isna().sum()
        )

        if invalid:
            result.fail(
                f"Score '{column}' invalid/NaN values="
                f"{invalid:,}"
            )
            continue

        infinite = int(
            np.isinf(
                series.to_numpy(
                    dtype=float
                )
            ).sum()
        )

        if infinite:
            result.fail(
                f"Score '{column}' infinite values="
                f"{infinite:,}"
            )

    result.passed_message(
        "Expected score columns inspected."
    )


# ============================================================
# OFFICIAL SIGNAL STATES
# ============================================================

def normalize_boolean_signal(
    series: pd.Series,
) -> tuple[pd.Series, list[str]]:
    output = pd.Series(
        False,
        index=series.index,
        dtype=bool,
    )

    invalid_values: list[str] = []

    for index, value in series.items():
        if pd.isna(value):
            invalid_values.append("NaN")
            continue

        if isinstance(
            value,
            (bool, np.bool_),
        ):
            output.at[index] = bool(value)
            continue

        if isinstance(
            value,
            (
                int,
                float,
                np.integer,
                np.floating,
            ),
        ):
            try:
                numeric_value = float(value)

                if math.isclose(
                    numeric_value,
                    1.0,
                    rel_tol=0.0,
                    abs_tol=1e-12,
                ):
                    output.at[index] = True
                    continue

                if math.isclose(
                    numeric_value,
                    0.0,
                    rel_tol=0.0,
                    abs_tol=1e-12,
                ):
                    output.at[index] = False
                    continue

                invalid_values.append(
                    str(value)
                )
                continue

            except Exception:
                invalid_values.append(
                    str(value)
                )
                continue

        text = str(
            value
        ).strip().lower()

        if text in TRUE_VALUES:
            output.at[index] = True
            continue

        if text in FALSE_VALUES:
            output.at[index] = False
            continue

        invalid_values.append(
            str(value)
        )

    return output, invalid_values


def validate_official_signal_states(
    df: pd.DataFrame,
    result: ValidationResult,
) -> dict[str, pd.Series]:
    missing = [
        column
        for column in OFFICIAL_STATE_COLUMNS
        if column not in df.columns
    ]

    if missing:
        result.fail(
            "Missing official detector state columns: "
            + ", ".join(missing)
        )
        return {}

    normalized: dict[str, pd.Series] = {}

    for column in OFFICIAL_STATE_COLUMNS:
        bool_series, invalid_values = (
            normalize_boolean_signal(
                df[column]
            )
        )

        normalized[column] = bool_series

        if invalid_values:
            unique_invalid = list(
                dict.fromkeys(
                    invalid_values
                )
            )

            result.fail(
                f"Condition '{column}' has invalid "
                f"binary values: "
                f"{unique_invalid[:20]}"
            )
            continue

        true_count = int(
            bool_series.sum()
        )

        false_count = int(
            len(bool_series) - true_count
        )

        print(
            f"[INFO] Condition '{column}': "
            f"true-like={true_count:,}, "
            f"false-like={false_count:,}"
        )

    if len(normalized) == 3:
        result.setup_count = int(
            normalized[
                "signal_setup"
            ].sum()
        )

        result.ready_count = int(
            normalized[
                "signal_ready"
            ].sum()
        )

        result.trigger_count = int(
            normalized[
                "signal_trigger"
            ].sum()
        )

        result.passed_message(
            "Official SETUP / READY / TRIGGER "
            "columns validated."
        )

    return normalized


# ============================================================
# SIGNAL STAGE
# ============================================================

def inspect_signal_stage(
    df: pd.DataFrame,
    official_states: dict[str, pd.Series],
    result: ValidationResult,
) -> None:
    if "signal_stage" not in df.columns:
        result.warn(
            "signal_stage column not present. "
            "Supplementary stage inspection skipped."
        )
        return

    stage = (
        df["signal_stage"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    counts = stage.value_counts(
        dropna=False
    )

    print(
        "[INFO] signal_stage distribution:"
    )

    for value, count in counts.head(30).items():
        display_value = (
            value
            if value
            else "<EMPTY>"
        )

        print(
            f"       {display_value}: {count:,}"
        )

    if official_states:
        result.passed_message(
            "signal_stage inspected separately from "
            "official state counts."
        )


# ============================================================
# FUTURE LEAKAGE
# ============================================================

def find_suspicious_future_columns(
    columns: Iterable[Any],
) -> list[str]:
    suspicious: list[str] = []

    for raw_column in columns:
        column = str(
            raw_column
        ).strip()

        lower = column.lower()

        if column in ALLOWED_NEXT_COLUMNS:
            continue

        for pattern in FORBIDDEN_FUTURE_PATTERNS:
            if pattern in lower:
                suspicious.append(
                    column
                )
                break

    return suspicious


def validate_future_leakage(
    feature: pd.DataFrame,
    signal: pd.DataFrame,
    result: ValidationResult,
) -> None:
    feature_suspicious = (
        find_suspicious_future_columns(
            feature.columns
        )
    )

    signal_suspicious = (
        find_suspicious_future_columns(
            signal.columns
        )
    )

    if feature_suspicious:
        result.fail(
            "Suspicious future/target Feature columns: "
            + ", ".join(
                feature_suspicious
            )
        )
    else:
        result.passed_message(
            "No suspicious future/target Feature "
            "columns detected."
        )

    if signal_suspicious:
        result.fail(
            "Suspicious future/target Signal columns: "
            + ", ".join(
                signal_suspicious
            )
        )
    else:
        result.passed_message(
            "No suspicious future/target Signal "
            "columns detected."
        )


# ============================================================
# SIGNAL TIMESTAMP MEMBERSHIP
# ============================================================

def validate_signal_timestamp_membership(
    ohlcv_ts: pd.Series | None,
    signal_ts: pd.Series | None,
    result: ValidationResult,
) -> None:
    if (
        ohlcv_ts is None
        or signal_ts is None
    ):
        return

    valid_ohlcv = ohlcv_ts.dropna()
    valid_signal = signal_ts.dropna()

    ohlcv_set = set(
        valid_ohlcv
        .astype("int64")
        .tolist()
    )

    signal_values = (
        valid_signal
        .astype("int64")
        .tolist()
    )

    missing_count = sum(
        1
        for value in signal_values
        if value not in ohlcv_set
    )

    if missing_count:
        result.fail(
            "Signal timestamps missing from OHLCV="
            f"{missing_count:,}"
        )
    else:
        result.passed_message(
            "Every valid Signal timestamp exists in OHLCV."
        )


# ============================================================
# SOURCE HASH
# ============================================================

def validate_hash_unchanged(
    path: Path,
    before_hash: str | None,
    label: str,
    result: ValidationResult,
) -> None:
    if before_hash is None:
        result.fail(
            f"{label} SHA256 before-validation hash "
            "was unavailable."
        )
        return

    if not path.exists():
        result.fail(
            f"{label} disappeared during validation."
        )
        return

    try:
        after_hash = file_sha256(
            path
        )

    except Exception as exc:
        result.fail(
            f"{label} SHA256 after-validation failed: "
            f"{type(exc).__name__}: {exc}"
        )
        return

    if after_hash == before_hash:
        result.passed_message(
            f"{label} SHA256 unchanged."
        )
    else:
        result.fail(
            f"{label} SHA256 changed during validation."
        )


# ============================================================
# PROJECT STRUCTURE
# ============================================================

def validate_project_structure() -> bool:
    print()
    separator("=")
    print("PROJECT STRUCTURE CHECK")
    separator("=")

    required_dirs = [
        DATA_DIR,
        OHLCV_DIR,
        FEATURE_DIR,
        SIGNAL_DIR,
    ]

    for timeframe in TIMEFRAMES:
        required_dirs.extend(
            [
                OHLCV_DIR / timeframe,
                FEATURE_DIR / timeframe,
                SIGNAL_DIR / timeframe,
            ]
        )

    passed = True

    for directory in required_dirs:
        if (
            directory.exists()
            and directory.is_dir()
        ):
            print(
                f"[PASS] {directory}"
            )
        else:
            print(
                f"[FAIL] Missing directory: {directory}"
            )
            passed = False

    return passed


# ============================================================
# SINGLE JOB
# ============================================================

def validate_one(
    market: str,
    timeframe: str,
) -> ValidationResult:
    started = time.perf_counter()

    (
        ohlcv_path,
        feature_path,
        signal_path,
    ) = get_job_paths(
        market,
        timeframe,
    )

    result = ValidationResult(
        market=market,
        timeframe=timeframe,
        ohlcv_path=ohlcv_path,
        feature_path=feature_path,
        signal_path=signal_path,
    )

    separator("-")
    print(
        f"[{timeframe.upper()}] {market}"
    )
    print(
        f"OHLCV  : {ohlcv_path}"
    )
    print(
        f"Feature: {feature_path}"
    )
    print(
        f"Signal : {signal_path}"
    )

    hashes_before: dict[str, str | None] = {
        "OHLCV": None,
        "Feature": None,
        "Signal": None,
    }

    for label, path in (
        ("OHLCV", ohlcv_path),
        ("Feature", feature_path),
        ("Signal", signal_path),
    ):
        if path.exists() and path.is_file():
            try:
                hashes_before[label] = (
                    file_sha256(path)
                )

            except Exception as exc:
                result.fail(
                    f"{label} SHA256 before-validation "
                    f"failed: "
                    f"{type(exc).__name__}: {exc}"
                )

    ohlcv = safe_read_csv(
        ohlcv_path,
        "OHLCV",
        result,
    )

    feature = safe_read_csv(
        feature_path,
        "Feature",
        result,
    )

    signal = safe_read_csv(
        signal_path,
        "Signal",
        result,
    )

    if (
        ohlcv is None
        or feature is None
        or signal is None
    ):
        result.elapsed_seconds = (
            time.perf_counter()
            - started
        )

        return result

    validate_unique_columns(
        ohlcv,
        "OHLCV",
        result,
    )

    validate_unique_columns(
        feature,
        "Feature",
        result,
    )

    validate_unique_columns(
        signal,
        "Signal",
        result,
    )

    validate_required_ohlc_columns(
        ohlcv,
        result,
    )

    _, ohlcv_ts = (
        validate_timestamp_integrity(
            ohlcv,
            "OHLCV",
            result,
        )
    )

    _, feature_ts = (
        validate_timestamp_integrity(
            feature,
            "Feature",
            result,
        )
    )

    _, signal_ts = (
        validate_timestamp_integrity(
            signal,
            "Signal",
            result,
        )
    )

    validate_row_counts(
        ohlcv,
        feature,
        signal,
        result,
    )

    validate_timestamp_alignment(
        ohlcv_ts,
        feature_ts,
        signal_ts,
        result,
    )

    validate_ohlcv_values(
        ohlcv,
        result,
    )

    validate_numeric_infinite_values(
        feature,
        "Feature",
        result,
    )

    validate_numeric_infinite_values(
        signal,
        "Signal",
        result,
    )

    validate_ma_columns(
        signal,
        result,
    )

    validate_score_columns(
        signal,
        result,
    )

    official_states = (
        validate_official_signal_states(
            signal,
            result,
        )
    )

    inspect_signal_stage(
        signal,
        official_states,
        result,
    )

    validate_future_leakage(
        feature,
        signal,
        result,
    )

    validate_signal_timestamp_membership(
        ohlcv_ts,
        signal_ts,
        result,
    )

    validate_hash_unchanged(
        ohlcv_path,
        hashes_before["OHLCV"],
        "OHLCV",
        result,
    )

    validate_hash_unchanged(
        feature_path,
        hashes_before["Feature"],
        "Feature",
        result,
    )

    validate_hash_unchanged(
        signal_path,
        hashes_before["Signal"],
        "Signal",
        result,
    )

    result.elapsed_seconds = (
        time.perf_counter()
        - started
    )

    print()
    print(
        f"Rows    : "
        f"OHLCV={result.ohlcv_rows:,} | "
        f"Feature={result.feature_rows:,} | "
        f"Signal={result.signal_rows:,}"
    )
    print(
        f"SETUP   : {result.setup_count:,}"
    )
    print(
        f"READY   : {result.ready_count:,}"
    )
    print(
        f"TRIGGER : {result.trigger_count:,}"
    )
    print(
        f"Elapsed : "
        f"{result.elapsed_seconds:.2f}s"
    )

    if result.passed:
        print("[RESULT] PASS")
    else:
        print("[RESULT] FAIL")

    return result


# ============================================================
# STATUS CSV
# ============================================================

def write_status_csv(
    results: list[ValidationResult],
) -> None:
    STATUS_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_path = STATUS_PATH.with_suffix(
        STATUS_PATH.suffix + ".tmp"
    )

    fieldnames = [
        "market",
        "timeframe",
        "passed",
        "resume_skipped",
        "ohlcv_rows",
        "feature_rows",
        "signal_rows",
        "setup_count",
        "ready_count",
        "trigger_count",
        "elapsed_seconds",
        "errors",
        "warnings",
    ]

    with temporary_path.open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as file:
        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for result in results:
            writer.writerow(
                {
                    "market": result.market,
                    "timeframe": result.timeframe,
                    "passed": result.passed,
                    "resume_skipped": result.skipped_resume,
                    "ohlcv_rows": result.ohlcv_rows,
                    "feature_rows": result.feature_rows,
                    "signal_rows": result.signal_rows,
                    "setup_count": result.setup_count,
                    "ready_count": result.ready_count,
                    "trigger_count": result.trigger_count,
                    "elapsed_seconds": (
                        f"{result.elapsed_seconds:.4f}"
                    ),
                    "errors": " | ".join(
                        result.errors
                    ),
                    "warnings": " | ".join(
                        result.warnings
                    ),
                }
            )

        file.flush()
        os.fsync(file.fileno())

    os.replace(
        temporary_path,
        STATUS_PATH,
    )


# ============================================================
# SUMMARY
# ============================================================

def print_summary(
    results: list[ValidationResult],
    markets: list[str],
    total_elapsed: float,
) -> bool:
    separator("=")
    print("FULL KRW 256 VALIDATOR SUMMARY")
    separator("=")

    passed_jobs = sum(
        1
        for result in results
        if result.passed
    )

    failed_jobs = (
        len(results)
        - passed_jobs
    )

    resumed_jobs = sum(
        1
        for result in results
        if result.skipped_resume
    )

    executed_jobs = (
        len(results)
        - resumed_jobs
    )

    total_ohlcv_rows = sum(
        result.ohlcv_rows
        for result in results
    )

    total_feature_rows = sum(
        result.feature_rows
        for result in results
    )

    total_signal_rows = sum(
        result.signal_rows
        for result in results
    )

    total_setup = sum(
        result.setup_count
        for result in results
    )

    total_ready = sum(
        result.ready_count
        for result in results
    )

    total_trigger = sum(
        result.trigger_count
        for result in results
    )

    print(
        f"Project          : {PROJECT_NAME}"
    )
    print(
        f"Validator        : {VALIDATOR_NAME}"
    )
    print(
        f"Execution mode   : FULL KRW MARKET"
    )
    print(
        f"Markets          : {len(markets):,}"
    )
    print(
        f"Timeframes       : {len(TIMEFRAMES):,}"
    )
    print(
        f"Validator jobs   : {len(results):,}"
    )
    print(
        f"Executed jobs    : {executed_jobs:,}"
    )
    print(
        f"Resume skipped   : {resumed_jobs:,}"
    )
    print(
        f"Passed jobs      : {passed_jobs:,}"
    )
    print(
        f"Failed jobs      : {failed_jobs:,}"
    )

    print()
    print("Rows:")
    print(
        f"  OHLCV          : {total_ohlcv_rows:,}"
    )
    print(
        f"  Feature        : {total_feature_rows:,}"
    )
    print(
        f"  Signal         : {total_signal_rows:,}"
    )

    print()
    print("256 Research States:")
    print(
        f"  SETUP          : {total_setup:,}"
    )
    print(
        f"  READY          : {total_ready:,}"
    )
    print(
        f"  TRIGGER        : {total_trigger:,}"
    )

    print()
    print("Validation:")
    print(
        "  File existence       : CHECKED"
    )
    print(
        "  CSV readability      : CHECKED"
    )
    print(
        "  Timestamp integrity  : CHECKED"
    )
    print(
        "  Unix ms timestamp    : SUPPORTED"
    )
    print(
        "  Feature/Signal 1:1   : CHECKED"
    )
    print(
        "  OHLC sanity          : CHECKED"
    )
    print(
        "  MA values            : CHECKED IF PRESENT"
    )
    print(
        "  Scores               : CHECKED IF PRESENT"
    )
    print(
        "  Research states      : OFFICIAL BINARY COLUMNS"
    )
    print(
        "  signal_stage         : SUPPLEMENTARY ONLY"
    )
    print(
        "  Future leakage       : CHECKED"
    )
    print(
        "  Source SHA256        : CHECKED"
    )

    print()
    print("Resume:")
    print(
        "  Checkpoint           : ENABLED"
    )
    print(
        "  Per-job save         : ENABLED"
    )
    print(
        "  Input hash verify    : ENABLED"
    )
    print(
        "  Changed input rerun  : ENABLED"
    )
    print(
        "  Failed job retry     : ENABLED"
    )

    print()
    print("Safety:")
    print(
        "  OHLCV modification   : DISABLED"
    )
    print(
        "  Feature modification : DISABLED"
    )
    print(
        "  Signal modification  : DISABLED"
    )
    print(
        "  Future labels        : DISABLED"
    )
    print(
        "  Prediction           : DISABLED"
    )
    print(
        "  Trading              : DISABLED"
    )
    print(
        "  Git reset            : DISABLED"
    )
    print(
        "  Git clean            : DISABLED"
    )
    print(
        "  Git commit           : DISABLED"
    )
    print(
        "  Git push             : DISABLED"
    )

    print()
    print(
        f"Elapsed total : "
        f"{total_elapsed:.2f}s"
    )

    separator("=")

    all_passed = (
        len(results) > 0
        and failed_jobs == 0
        and len(results)
        == len(markets) * len(TIMEFRAMES)
    )

    if all_passed:
        print(
            "[RESULT] FULL KRW 256 VALIDATOR PASSED"
        )
        print(
            f"[PASS] {len(markets):,} markets verified."
        )
        print(
            f"[PASS] {len(results):,} validator jobs verified."
        )
        print(
            "[PASS] OHLCV / Feature / Signal integrity verified."
        )
        print(
            "[PASS] Source data remained unchanged."
        )
        print(
            "[PASS] Resume checkpoint is current."
        )
        print(
            "[NEXT] 256 validation foundation completed."
        )
    else:
        print(
            "[RESULT] FULL KRW 256 VALIDATOR FAILED"
        )
        print(
            f"[FAIL] Failed jobs: {failed_jobs:,}"
        )
        print(
            "[STOP] Do NOT proceed to future-result labels."
        )
        print(
            "[NEXT] Fix failed jobs and run validator again."
        )

    separator("=")

    return all_passed


# ============================================================
# MAIN
# ============================================================

def main() -> int:
    total_started = time.perf_counter()

    print()
    separator("=")
    print(
        f"{PROJECT_NAME} - {VALIDATOR_NAME}"
    )
    print(
        "STEP 4 - FULL KRW 256 DETECTOR OUTPUT VALIDATION"
    )
    separator("=")

    print(
        f"Started UTC : {utc_now_text()}"
    )
    print(
        f"Base dir    : {BASE_DIR}"
    )

    print()
    print("Mode:")
    print(
        "  READ ONLY validation"
    )
    print(
        "  FULL KRW market auto-discovery"
    )
    print(
        "  h1 / h4 / d1"
    )
    print(
        "  Resume / checkpoint enabled"
    )
    print(
        "  SHA256-aware resume"
    )
    print(
        "  Changed inputs are revalidated"
    )
    print(
        "  Failed jobs are retried"
    )
    print(
        "  Feature / Signal 1:1 verification"
    )
    print(
        "  Unix timestamp unit auto-detection"
    )
    print(
        "  SETUP / READY / TRIGGER inspection"
    )
    print(
        "  Future-information leakage check"
    )
    print(
        "  No future labels"
    )
    print(
        "  No prediction"
    )
    print(
        "  No trading"
    )

    if not validate_project_structure():
        print()
        separator("=")
        print(
            "[RESULT] PROJECT STRUCTURE FAILED"
        )
        print(
            "[STOP] Required data directories are missing."
        )
        return 1

    markets = discover_markets()

    incomplete = discover_incomplete_markets(
        markets
    )

    print()
    separator("=")
    print("MARKET DISCOVERY")
    separator("=")

    print(
        f"Complete markets : {len(markets):,}"
    )
    print(
        f"Expected jobs    : "
        f"{len(markets) * len(TIMEFRAMES):,}"
    )

    if incomplete:
        print(
            f"[FAIL] Incomplete markets detected: "
            f"{len(incomplete):,}"
        )

        for market in incomplete[:50]:
            print(
                f"       {market}"
            )

        if len(incomplete) > 50:
            print(
                f"       ... and "
                f"{len(incomplete) - 50:,} more"
            )

        print()
        print(
            "[STOP] Every KRW market must have "
            "OHLCV / Feature / Signal files for "
            "h1 / h4 / d1."
        )
        return 1

    if not markets:
        print(
            "[FAIL] No complete KRW markets discovered."
        )
        return 1

    if len(markets) != 290:
        print(
            f"[WARN] Current complete market count is "
            f"{len(markets):,}, not 290."
        )
        print(
            "[WARN] Validation will use the actual complete "
            "market set discovered from the data."
        )
    else:
        print(
            "[PASS] 290 complete KRW markets discovered."
        )

    checkpoint = load_checkpoint()

    results: list[ValidationResult] = []

    total_jobs = (
        len(markets)
        * len(TIMEFRAMES)
    )

    job_number = 0

    try:
        for market in markets:
            for timeframe in TIMEFRAMES:
                job_number += 1

                print()
                separator("=")
                print(
                    f"[JOB {job_number:,}/{total_jobs:,}] "
                    f"{market} {timeframe}"
                )
                separator("=")

                resume_ok, record = (
                    checkpoint_job_is_current(
                        checkpoint,
                        market,
                        timeframe,
                    )
                )

                if (
                    resume_ok
                    and record is not None
                ):
                    result = result_from_checkpoint(
                        market,
                        timeframe,
                        record,
                    )

                    results.append(
                        result
                    )

                    print(
                        f"[RESUME] SKIP {market} {timeframe}"
                    )
                    print(
                        "[PASS] Previous validation is still "
                        "valid and all input SHA256 hashes match."
                    )

                    continue

                try:
                    result = validate_one(
                        market=market,
                        timeframe=timeframe,
                    )

                except KeyboardInterrupt:
                    raise

                except Exception as exc:
                    (
                        ohlcv_path,
                        feature_path,
                        signal_path,
                    ) = get_job_paths(
                        market,
                        timeframe,
                    )

                    result = ValidationResult(
                        market=market,
                        timeframe=timeframe,
                        ohlcv_path=ohlcv_path,
                        feature_path=feature_path,
                        signal_path=signal_path,
                        passed=False,
                    )

                    message = (
                        "Unexpected validator exception: "
                        f"{type(exc).__name__}: {exc}"
                    )

                    result.errors.append(
                        message
                    )

                    print(
                        f"[FAIL] {message}"
                    )

                results.append(
                    result
                )

                if result.passed:
                    mark_checkpoint_passed(
                        checkpoint,
                        result,
                    )

                    print(
                        "[CHECKPOINT] PASS saved."
                    )
                else:
                    remove_failed_checkpoint_record(
                        checkpoint,
                        market,
                        timeframe,
                    )

                    print(
                        "[CHECKPOINT] Failed job was NOT "
                        "marked completed."
                    )

                write_status_csv(
                    results
                )

    except KeyboardInterrupt:
        print()
        separator("=")
        print(
            "[STOP] Validation interrupted by user."
        )
        print(
            "[PASS] Completed PASS jobs are already "
            "stored in the checkpoint."
        )
        print(
            "[PASS] Run the same validator again to resume."
        )
        print(
            f"Checkpoint : {CHECKPOINT_PATH}"
        )
        print(
            f"Completed this run : "
            f"{len(results):,}/{total_jobs:,}"
        )
        separator("=")

        try:
            write_status_csv(
                results
            )
        except Exception:
            pass

        return 130

    total_elapsed = (
        time.perf_counter()
        - total_started
    )

    write_status_csv(
        results
    )

    all_passed = print_summary(
        results,
        markets,
        total_elapsed,
    )

    if all_passed:
        checkpoint[
            "full_validation_passed"
        ] = True

        checkpoint[
            "full_validation_completed_utc"
        ] = utc_now_text()

        checkpoint[
            "market_count"
        ] = len(markets)

        checkpoint[
            "job_count"
        ] = len(results)

        save_checkpoint(
            checkpoint
        )

        return 0

    checkpoint[
        "full_validation_passed"
    ] = False

    save_checkpoint(
        checkpoint
    )

    return 1


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    try:
        exit_code = main()

    except KeyboardInterrupt:
        print()
        print(
            "[STOP] Interrupted by user."
        )
        exit_code = 130

    except Exception as exc:
        print()
        separator("=")
        print(
            "[FATAL] validate_256.py crashed."
        )
        print(
            f"{type(exc).__name__}: {exc}"
        )
        separator("=")
        exit_code = 1

    sys.exit(exit_code)
